[project]
name = "hop3-cli"
version = "0.4.0.alpha1"
authors = [
    {name = "Stefane Fermigier", email = "sf@abilian.com"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.10"
dependencies = [
    # Configuration
    "toml<1.0.0,>=0.10.2",
    # Communication
    "jsonrpcclient<5.0.0,>=4.0.3",
    "requests<3.0.0,>=2.32.3",
    # Presentation
    "tabulate<1.0.0,>=0.9.0",
    "termcolor<3.0.0,>=2.4.0",
    "wasabi>=1.1.3",
    "sshtunnel>=0.4.0",
    "loguru>=0.7.3",
]
description = ""
readme = "README.md"

[project.scripts]
hop = "hop3_cli.main:main"

# ----------------------------------------

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/hop3_cli"]

# Was:
#[build-system]
#requires = ["pdm-backend"]
#build-backend = "pdm.backend"
#
#[tool.pdm.build]
#includes = ["src/hop3_cli"]
