[project]
name = "hop3-cli"
version = "0.1.0"

[tool.poetry]
name = "hop3-cli"
version = "0.1.0"
description = ""
authors = ["Stefane Fermigier <sf@abilian.com>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "hop3_cli", from = "src" },
]

[tool.poetry.scripts]
hop = "hop3_cli.main:main"

# Future implementation
# hop = "hop3_cli.new:main"

[tool.poetry.dependencies]
python = "^3.10"

platformdirs = "^4.2.2"
paramiko = "^3.4.0"
rpyc = "^6.0.0"
toml = "^0.10.2"
jsonrpcclient = "^4.0.3"
tabulate = "^0.9.0"
termcolor = "^2.4.0"
urllib3 = "^2.2.3"
requests = "^2.32.3"

# TODO: remove this dependency
devtools = "^0.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
