[project]
name = "hop3-cli"
version = "0.2.3"
authors = [
    {name = "Stefane Fermigier", email = "sf@abilian.com"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.10"
dependencies = [
    # Configuration
    "toml<1.0.0,>=0.10.2",
    # Communication
    "jsonrpcclient<5.0.0,>=4.0.3",
    "requests<3.0.0,>=2.32.3",
    # Presentation
    "tabulate<1.0.0,>=0.9.0",
    "termcolor<3.0.0,>=2.4.0",
    "wasabi>=1.1.3",
]
description = ""
readme = "README.md"

[project.scripts]
hop-cli = "hop3_cli.main:main"
hop-cli-static = "hop3_cli.static:main"
hop-cli-static2 = "hop3_cli.static2:main"

[tool.pdm.build]
includes = ["src/hop3_cli"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
