[program:peertube]
directory=/app/code/server
user=%(ENV_HOP3_USER)s
environment=HOME="/home/%(ENV_HOP3_USER)s",USER="%(ENV_HOP3_USER)s"
command=npm start
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
