#!/bin/bash
set -e

: "${PORT:?ERROR: PORT is required}"
: "${PGHOST:?ERROR: PGHOST is required}"

export DATABASE_URL="${DATABASE_URL:-postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}}"
export SECRET_KEY="${SECRET_KEY:-$(head -c 32 /dev/urandom | base64)}"
export BASE_URL="${BASE_URL:-http://localhost:${PORT}}"

cd /data

# bugsink_conf.py lives in /data so it persists. bugsink-manage /
# bugsink.wsgi both set DJANGO_SETTINGS_MODULE=bugsink_conf and add
# cwd to sys.path; the docker template handles DATABASE_URL parsing.
# Persist a random SECRET_KEY directly in the conf file so it survives
# container restarts (the docker template reads it from env otherwise).
if [ ! -f bugsink_conf.py ]; then
    bugsink-create-conf --template docker \
        --host localhost \
        --port "${PORT}" \
        -o bugsink_conf.py
    KEY=$(python -c "import secrets; print(secrets.token_urlsafe(50))")
    printf '\n# Generated by Hop3 on first deploy\nSECRET_KEY = "%s"\nALLOWED_HOSTS = ["*"]\n' "${KEY}" >> bugsink_conf.py
fi

bugsink-manage migrate --noinput

exec gunicorn bugsink.wsgi:application \
    --bind "0.0.0.0:${PORT}" \
    --pythonpath . \
    --access-logfile - \
    --error-logfile -
