# HedgeDoc - Collaborative Markdown Editor
# https://hedgedoc.org/

[metadata]
name = "hedgedoc"

[build]
builder = "docker"

[env]
NODE_ENV = "production"
CMD_ALLOW_ANONYMOUS = "true"
CMD_ALLOW_ANONYMOUS_EDITS = "true"
