# HedgeDoc - Collaborative Markdown Editor
# https://hedgedoc.org/

[app]
name = "hedgedoc"
builder = "docker"

[web]
port = 3000

[env]
NODE_ENV = "production"
CMD_ALLOW_ANONYMOUS = "true"
CMD_ALLOW_ANONYMOUS_EDITS = "true"
