preview = true

exclude = [
    "src/hop3/util/templating.py",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    "BLE", # flake8-blind-except
    "D", # pydocstyle
    "EM", # flake8-errmsg
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos

    # False positive, don't remove
    "S101", # Use of `assert` detected
    "COM812", # Missing trailing comma
    "PLR6104", # suggests using += when inapplicable
    "SIM108", # Use ternary operator
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "I001", # Import block is un-sorted or un-formatted
    "PD011", # Use `.to_numpy()` instead of `.values`
    "TRY003", # Avoid specifying long messages outside the exception class
    "PLW1514", # `pathlib.Path(...).write_text` without explicit `encoding` argument
    "TCH001", # Move import into a type-checking block
    "TCH002", # Move import into a type-checking block
    "TCH003", # Move import into a type-checking block

    # Fix these
    "C901", # Function is too complex
    "E501", # Line too long
    "PERF203",
    "PLC2801",
    "PLR0912",
    "PLR0913",
    "PLR0914",
    "PLR0915",
    "PLR6301",
    "PLW1510", # `subprocess.run` without explicit `check` argument
    "PT011",
    "PT017",
    "RET504",
    "RUF012",
]

[lint.mccabe]
max-complexity = 14
