preview = true

exclude = [
    "hop3-lib/src/hop3_lib/actors",
    "hop3-lib/src/hop3_lib/bus",
    "hop3-cli/src/hop3_cli/commands",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    "BLE", # flake8-blind-except
    "D", # pydocstyle
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos
    "DOC", # pydocstyle

    # False positive, don't remove
    "A005", # Module ... is shadowing a Python builtin module
    "COM812", # Missing trailing comma
    "INP001", # implicit namespace package
    "ISC001", # (The following rules may cause conflicts when used with the formatter)
    "PD011", # Use `.to_numpy()` instead of `.values`
    "PLC0415", # `import` should be at the top-level of a file
    "PLW1514", # `pathlib.Path(...).write_text` without explicit `encoding` argument
    "RET504", # Unnecessary assignment before `return` statement
    "RET505", # Unnecessary `else` after `return` statement"
    "S101", # Use of `assert` detected
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "SIM108", # Use ternary operator
    "TRY003", # Avoid specifying long messages outside the exception class

    # Fix these
    "E501", # Line too long
    "PERF203",
    "PGH003",
    "PLC1901",
    "PLC2801",
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments
    "PLR0914", # Too many local variables
    "PLR0915", # Too many statements
    "PLR6301", # Method could be a function
    "PLW1510", # `subprocess.run` without explicit `check` argument
    # Not sure why this one raises warnings
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]

[lint.mccabe]
# TODO: Set max-complexity = 10
max-complexity = 14

[lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
