preview = true

exclude = [
    "src/hop3/util/templating.py",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    "BLE", # flake8-blind-except
    "C90", # mccabe
    "D", # pydocstyle
    "EM", # flake8-errmsg
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos
    "TRY", # tryceratops

    # False positive, don't remove
    "S101", # Use of `assert` detected
    "COM812", # Missing trailing comma
    "PLR6104", # suggests using += when inapplicable
    "SIM108", # Use ternary operator
    "I001", # Import block is un-sorted or un-formatted
    "PD011", # Use `.to_numpy()` instead of `.values`


    # Fix these
    "C408",
    "C417",
    "E501",
    "FBT001",
    "FBT002",
    "FBT003",
    "PERF203",
    "PLC2801",
    "PLR0912",
    "PLR0913",
    "PLR0914",
    "PLR0915",
    "PLR0917",
    "PLR2004",
    "PLR6301",
    "PLW1510",
    "PLW1514",
    "PT011",
    "PT017",
    "PYI034",
    "RET504",
    "RUF012",
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "TCH001", # Move import into a type-checking block
    "TCH002", # Move import into a type-checking block
    "TCH003", # Move import into a type-checking block
    #
    #    "A002", # shadowing built-in
    #    "E722", # Bare except
    #    "ERA001", # Commented out code
    #    "F401", # 'module' imported but unused
    #    "I001", # Import block is un-sorted or un-formatted
    #    "PLR0913", # Too many arguments in function definition
    #    "PLR0917", # Too many positional arguments
    #    "PLR2004", # Magic value used in comparison
    #    "RET504", # Unnecessary variable assignment before `return` statement
    #    "RET505", # Unnecessary `else` after `return` statement
    #    "SLF001", # Private member accessed
    #    "T201", # `print` found
    #    "TRY003", # Avoid specifying long messages outside the exception class
    #    # Potential security issues
    #    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    #    # Temp
    #    "ARG002", # Unused argument '...'
    #    "E501", # Line too long
    #    "TRY300", # Consider moving this statement to an `else` block
]

[lint.mccabe]
max-complexity = 10
