preview = true
target-version = "py310"

exclude = [
    "apps",
    "scripts",
    "tasks.py",
    "docs",
    "installer/**/*.py",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Never
    "PD", # We're not using Pandas

    # Later (or never)
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "BLE", # flake8-blind-except
    "CPY", # Copyright
    "D", # pydocstyle
    "DOC", # pydocstyle
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos

    # False positive, don't remove
    "A004", # ... is shadowing a Python standard library module
    "A005", # ... is shadowing a Python builtin module
    "COM812", # Missing trailing comma
    "FURB113", # repeated-append
    "INP001", # implicit-namespace-package
    "ISC001", # (The following rules may cause conflicts when used with the formatter)
    "PGH003", # Use specific rule codes when ignoring type issues
    "PLC0414", # Import alias does not rename original package
    "PLC1901", # An empty string is falsey; consider using `not s` if this is intended
    "PLR2004", # Magic number
    "PLR6301", # Method could be a function
    "PLR0904", # too-many-public-methods
    "PLW1514", # `pathlib.Path(...).write_text` without explicit `encoding` argument
    "RET504", # Unnecessary assignment before `return` statement
    "S101", # Use of `assert` detected
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "SIM108", # Use ternary operator
    "TRY300", # Consider moving this statement to an `else` block
    "PERF401", #  7 - PERF401	manual-list-comprehension

    # Fix these
    "E501", #   	line-too-long
    "TC", # Move import into a type-checking block (conflicts with wireup)
    "F841", # 26 - F841   	unused-variable
    "FBT001", # 24 - FBT001 	boolean-type-hint-positional-argument
    "FBT002", # 16 - FBT002 	boolean-default-value-positional-argument
    "B904", # 15 - B904   	raise-without-from-inside-except
    "PLR0911", #  9 - PLR0911	too-many-return-statements
    "FBT003", #  5 - FBT003 	boolean-positional-value-in-call
    "RUF005", #  5 - RUF005 	collection-literal-concatenation
    "PLW0603", #  4 - PLW0603	global-statement
    "TRY301", #  4 - TRY301 	raise-within-try
    "PERF203", #  3 - PERF203	try-except-in-loop
    "PLC0415", #  3 - PLC0415	import-outside-top-level
    "B008", #  1 - B008   	function-call-in-default-argument
    "B909", #  1 - B909   	loop-iterator-mutation
    "PLW2901", #  1 - PLW2901	redefined-loop-name
    "RUF100", # Unused noqa
    "PLR0913", #	too-many-arguments
    "PLC0206", #	dict-index-missing-items
    "PLR0914", #	too-many-locals
    "PLR0917", #	too-many-positional-arguments
    "PT012",
    "C901", # ... is too complex (13 > 12)
    "PLR0912", # Too many branches (16 > 12)
    "SIM105", # Use `contextlib.suppress` instead of `try`-`except`-`pass`
]


[lint.mccabe]
# TODO: Set max-complexity = 10
max-complexity = 12

[lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
known-first-party = ["hop3"]

[lint.per-file-ignores]
"**/src/**/*.py" = [
    "PT", # Pytest warnings in source code are probably false positives

]
"**/tests/**/*.py" = [
    "INP001", # implicit namespace package
    "B017", #  	assert-raises-exception
    "PT011", # 	pytest-raises-too-broad
    "N806", #  	non-lowercase-variable-in-function
    "SLF001", #	private-member-access
    "PLR0915", #	too-many-statements
    "C901",    #	complex-structure
    "PLC2701", # Private name import
    "PLR0912", # too-many-branches
]
"**/noxfile.py" = [
    "INP001", # implicit namespace package
]
