preview = true

exclude = [
    "src/hop3/util/templating.py",
]

lint.select = [
    # Temp
    # "S", # flake8-bandit
    # "SIM", # flake8-simplify
    # "PTH", # flake8-use-pathlib
    # "ANN", # flake8-annotations
    # "D", # pydocstyle
    # "ARG", # flake8-unused-arguments
    # "C90", # mccabe
    # "BLE", # flake8-blind-except
    # "EM", # flake8-errmsg
    # "TRY", # tryceratops
    # "T20", # flake8-print
    # "B", # flake8-bugbear
    # "ERA", # eradicate

    "A", # flake8-builtins
    "AIR", # Airflow
    "ASYNC", # flake8-async
    "C4", # flake8-comprehensions
    "COM", # flake8-commas
    "CPY", # flake8-copyright
    "DJ", # flake8-django
    "DTZ", # flake8-datetimez
    "E", # pycodestyle
    "EXE", # flake8-executable
    "F", # Pyflakes
    "FA", # flake8-future-annotations
    "FBT", # flake8-boolean-trap
    "FLY", # flynt
    "FURB", # refurb
    "G", # flake8-logging-format
    "ICN", # flake8-import-conventions
    "INP", # flake8-no-pep420
    "INT", # flake8-gettext
    "ISC", # flake8-implicit-str-concat
    "LOG", # flake8-logging
    "N", # pep8-naming
    "PERF", # Perflint
    "PGH", # pygrep-hooks
    "PIE", # flake8-pie
    "PL", # Pylint
    "PT", # flake8-pytest-style
    "PYI", # flake8-pyi
    "Q", # flake8-quotes
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # Ruff-specific rules
    "SLF", # flake8-self
    "SLOT", # flake8-slots
    "T10", # flake8-debugger
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP", # pyupgrade
    "W", # pycodestyle
    "YTT", # flake8-2020
    # Don't use these
    # "FIX", # flake8-fixme
    # "TD", # flake8-todos
    # "NPY", # NumPy-specific rules
    # "PD", # pandas-vet
    # "I", # isort
]

lint.extend-ignore = [
    # False positive, don't remove
    "S101", # Use of `assert` detected
    # Fix these
    "C408",
    "C417",
    "E501",
    "FBT001",
    "FBT002",
    "FBT003",
    "PERF203",
    "PLC2801",
    "PLR0912",
    "PLR0914",
    "PLR0915",
    "PLR2004",
    "PLR6301",
    "PLW1510",
    "PLW1514",
    "PT011",
    "PT017",
    "PYI034",
    "RET504",
    "RUF012",
    "TCH001", # Move import into a type-checking block
    "TCH002", # Move import into a type-checking block
    "TCH003", # Move import into a type-checking block
#
#    "A002", # shadowing built-in
#    "E722", # Bare except
#    "ERA001", # Commented out code
#    "F401", # 'module' imported but unused
#    "I001", # Import block is un-sorted or un-formatted
#    "PLR0913", # Too many arguments in function definition
#    "PLR0917", # Too many positional arguments
#    "PLR2004", # Magic value used in comparison
#    "RET504", # Unnecessary variable assignment before `return` statement
#    "RET505", # Unnecessary `else` after `return` statement
#    "SLF001", # Private member accessed
#    "T201", # `print` found
#    "TRY003", # Avoid specifying long messages outside the exception class
#    # Potential security issues
#    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
#    # Temp
#    "ARG002", # Unused argument '...'
#    "E501", # Line too long
#    "TRY300", # Consider moving this statement to an `else` block
]

[lint.mccabe]
max-complexity = 10
