preview = true

exclude = [
    "hop3-agent/src/hop3/util/templating.py",
    "hop3-lib/src/hop3_lib/actors",
    "hop3-lib/src/hop3_lib/bus",
    "hop3-cli/src/hop3_cli/commands",
    "src/hop3_main",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    "BLE", # flake8-blind-except
    "D", # pydocstyle
    "EM", # flake8-errmsg
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos

    # False positive, don't remove
    "COM812", # Missing trailing comma
    "I001", # Import block is un-sorted or un-formatted
    "INP001", # implicit namespace package
    "PD011", # Use `.to_numpy()` instead of `.values`
    "PLC0415", # Consider using `f-string`
    "PLR6104", # suggests using += when inapplicable
    "PLW1514", # `pathlib.Path(...).write_text` without explicit `encoding` argument
    "RET505", # Unnecessary `else` after `return` statement"
    "S101", # Use of `assert` detected
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "SIM108", # Use ternary operator
    "TCH001", # Move import into a type-checking block
    "TCH002", # Move import into a type-checking block
    "TCH003", # Move import into a type-checking block
    "TRY003", # Avoid specifying long messages outside the exception class

    # Fix these
    "C901", # Function is too complex
    "E501", # Line too long
    "PERF203",
    "PLC2801",
    "PLC1901",
    "PLR0912",
    "PLR0913",
    "PLR0914",
    "PLR0915",
    "PLR6301",
    "PLW1510", # `subprocess.run` without explicit `check` argument
    "PT011",
    "PT017",
    "RET504",
    "RUF012",
    "FBT002", # Boolean default positional argument in function definition
    "PLR0917", # Too many positional arguments
    "PLR0911", # Too many return statements
    "DOC501", # Raised exception `ValueError` missing from docstring
]

[lint.mccabe]
max-complexity = 14
