preview = true
target-version = "py310"

exclude = [
    "apps",
    "scripts",
    "tasks.py",
    "docs",
    "demos",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Never
    "PD", # We're not using Pandas

    # Later (or never)
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "BLE", # flake8-blind-except
    "CPY", # Copyright
    "D", # pydocstyle
    "DOC", # pydocstyle
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos
    "FBT",

    # False positive, don't remove
    "A004", # ... is shadowing a Python standard library module
    "A005", # ... is shadowing a Python builtin module
    "COM812", # Missing trailing comma
    "FURB113", # repeated-append
    "INP001", # implicit-namespace-package
    "ISC001", # (The following rules may cause conflicts when used with the formatter)
    "PGH003", # Use specific rule codes when ignoring type issues
    "PLC0414", # Import alias does not rename original package
    "PLC1901", # An empty string is falsey; consider using `not s` if this is intended
    "PLR2004", # Magic number
    "PLR6301", # Method could be a function
    "PLR0904", # too-many-public-methods
    "PLW1514", # `pathlib.Path(...).write_text` without explicit `encoding` argument
    "RET504", # Unnecessary assignment before `return` statement
    "S101", # Use of `assert` detected
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "SIM108", # Use ternary operator
    "TRY300", # Consider moving this statement to an `else` block
    "PERF401", #  7 - PERF401	manual-list-comprehension
    "RUF067", # `__init__` module should only contain docstrings and re-exports
    "RUF070", # ...
    # Needed by the DI and SQLA frameworks
    "TC003", #  	[ ] typing-only-standard-library-import
    "TC002", #  	[ ] typing-only-third-party-import
    #
    # Fix this (later)
    #
    "E501", #   	[ ] line-too-long
    "TC001", #  	[ ] typing-only-first-party-import
    "PLR0913", #	[ ] too-many-arguments
    "PLR0917", #	[ ] too-many-positional-arguments
    "RUF100", # 	[*] unused-noqa
    "C901", #   	[ ] complex-structure
    "F841", #   	[ ] unused-variable
    "SIM105", # 	[ ] suppressible-exception
    "B904", #   	[ ] raise-without-from-inside-except
    "PERF203", #	[ ] try-except-in-loop
    "PLW1510", #	[ ] subprocess-run-without-check
    "TRY301", # 	[ ] raise-within-try
    "PLW0603", #	[ ] global-statement
    "RUF005", # 	[ ] collection-literal-concatenation
    "PLR0911", #	[ ] too-many-return-statements
    "PLR0914", #	[ ] too-many-locals
    "PLW2901", #	[ ] redefined-loop-name
    "SIM117", # 	[ ] multiple-with-statements
    "RUF001", # 	[ ] ambiguous-unicode-character-string
    "B008", #   	[ ] function-call-in-default-argument
    "B909", #   	[ ] loop-iterator-mutation
    "DTZ005", # 	[ ] call-datetime-now-without-tzinfo
    "E402", #   	[ ] module-import-not-at-top-of-file
    "PLC0206", #	[ ] dict-index-missing-items
]


[lint.mccabe]
# TODO: Set max-complexity = 10
# max-complexity = 12

[lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
known-first-party = ["hop3"]

[lint.per-file-ignores]
"**/src/**/*.py" = [
    "PT", # Pytest warnings in source code are probably false positives
]
"packages/hop3-server/src/hop3/orm/**/*.py" = [
    "TC",
]
"packages/hop3-tui/**/*.py" = [
    "FBT003",
]
"**/tests/**/*.py" = [
    "INP001", # implicit namespace package
    "B017", #  	assert-raises-exception
    "PT011", # 	pytest-raises-too-broad
    "N806", #  	non-lowercase-variable-in-function
    "SLF001", #	private-member-access
    "PLR0915", #	too-many-statements
    "C901",    #	complex-structure
    "PLC2701", # Private name import
    "PLR0912", # too-many-branches
    "RUF069", # Unreliable floating point equality comparison
    "PT012",
]
"**/noxfile.py" = [
    "INP001", # implicit namespace package
]
