[program:web]
directory=/app/code/redash
command=gunicorn -b 0.0.0.0:5000 --name redash -w%(ENV_REDASH_WEB_WORKERS)s redash.wsgi:app --max-requests 1000 --max-requests-jitter 100 --timeout 60
process_name=server
user=%(ENV_HOP3_USER)s
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
