; https://github.com/getredash/redash/blob/master/worker.conf#L4
[program:rq]
command=/app/code/redash/manage.py rq worker periodic emails default scheduled_queries queries schemas
directory=/app/code/redash
process_name=%(program_name)s-%(process_num)s
numprocs=%(ENV_WORKERS_COUNT)s
user=%(ENV_HOP3_USER)s
startsecs=300
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true

[eventlistener:rq_healthcheck]
serverurl=AUTO
command=/app/code/redash/manage.py rq healthcheck
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
events=TICK_60
