[program:worker_1]
priority=10
directory=/app/code
command=php /app/code/occ background-job:worker -v -t 3600 'OC\TaskProcessing\SynchronousBackgroundJob'
user=www-data
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker_2]
priority=10
directory=/app/code
command=php /app/code/occ background-job:worker -v -t 3600 'OC\TaskProcessing\SynchronousBackgroundJob'
user=www-data
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker_3]
priority=10
directory=/app/code
command=php /app/code/occ background-job:worker -v -t 3600 'OC\TaskProcessing\SynchronousBackgroundJob'
user=www-data
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
