[program:worker]
user=%(ENV_HOP3_USER)s
directory=/app/code
command=bundle exec good_job start
autorestart=true
autostart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
