# Copyright (c) 2023-2024, Abilian SAS
#
# SPDX-License-Identifier: BSD-3-Clause

image: debian/stable

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  # Python (this is Python 3.11)
  - python3-dev
  - python3-pip
  - python3-wheel
  # Libraries
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev

tasks:
  - setup: |
      sudo pip install --break-system-packages -U uv nox
      cd hop3
      uv sync

  - lint: |
      cd hop3
      uv run make lint

  - test: |
      cd hop3
      uv run inv test

  - nox: |
      cd hop3
      uv run nox -e pytest-3.11

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
    # to: builds@fermigier.com
