# Copyright (c) 2023-2024, Abilian SAS
#
# SPDX-License-Identifier: BSD-3-Clause

image: ubuntu/24.04

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  # Python
  - python3-dev
  - python3-pip
  - python3-wheel
  - tox
  # Libraries
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev

tasks:
  - setup: |
      sudo pip install -U pip setuptools wheel poetry nox
      cd hop3
      poetry install

  - lint: |
      cd hop3
      poetry run make lint

  - test: |
      cd hop3
      poetry run make test

triggers:
  - action: email
    condition: failure
    to: builds@fermigier.com
