# hop3.nix - Nix expression for Bugsink deployment
#
# Bugsink is on PyPI but not in nixpkgs. Install via pip inside a
# virtualenv during the Nix build. `__noChroot = true` is required
# because pip needs network access.

{ pkgs ? import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/50ab793786d9de88ee30ec4e4c24fb4236fc2674.tar.gz";
  sha256 = "1s2gr5rcyqvpr58vxdcb095mdhblij9bfzaximrva2243aal3dgx";
}) {} }:

let
  python = pkgs.python3;
  version = "2.1.2";

  app = pkgs.stdenv.mkDerivation {
    pname = "bugsink";
    inherit version;
    __noChroot = true;
    meta.description = "Self-hosted error tracking, Sentry SDK-compatible";

    dontUnpack = true;
    dontBuild = true;

    nativeBuildInputs = [ python pkgs.python3Packages.pip ];

    installPhase = ''
      mkdir -p $out/bin $out/venv $out/hop3

      ${python}/bin/python -m venv $out/venv
      # Pure-Python psycopg v3 (no [binary] extra). The binary wheels
      # for psycopg2-binary and psycopg[binary] both reference a
      # version-pinned libkrb5 (`libkrb5-fcafa220.so.3.3`) that isn't
      # installed alongside the wheel under the Nix-built Python venv,
      # so the C extension fails to load. The pure-Python impl loads
      # libpq.so.5 dynamically at runtime via LD_LIBRARY_PATH (set in
      # the wrapper below from pkgs.postgresql.lib).
      $out/venv/bin/pip install --no-cache-dir \
        "bugsink==${version}" \
        "gunicorn>=21.0" \
        "psycopg>=3.1"

      cat > $out/bin/bugsink-start << 'WRAPPER'
      #!/bin/sh
      set -e

      # Pip-installed C extensions need shared libs at runtime that
      # aren't on the host loader path under a Nix-built Python venv:
      #   - libpq.so.5         → psycopg (postgres client)
      #   - libkrb5            → psycopg (kerberos auth, transitive)
      #   - libstdc++.so.6     → symbolic._lowlevel (Sentry transitive
      #                          dep; bugsink pulls sentry-sdk)
      export LD_LIBRARY_PATH="${pkgs.postgresql.lib}/lib:${pkgs.krb5.lib}/lib:${pkgs.stdenv.cc.cc.lib}/lib:''${LD_LIBRARY_PATH:-}"

      export DATABASE_URL="''${DATABASE_URL:-postgresql://''${PGUSER}:''${PGPASSWORD}@''${PGHOST}:''${PGPORT}/''${PGDATABASE}}"
      export SECRET_KEY="''${SECRET_KEY:-$(head -c 32 /dev/urandom | base64)}"
      export BASE_URL="''${BASE_URL:-http://localhost:''${PORT:-8080}}"

      # bugsink_conf.py is the operator-facing settings module. Generate
      # on first run; bugsink-manage and bugsink.wsgi both set
      # DJANGO_SETTINGS_MODULE=bugsink_conf and add cwd to sys.path.
      # Persist SECRET_KEY in the file because env exports from here
      # don't reliably propagate to the uWSGI daemon.
      if [ ! -f bugsink_conf.py ]; then
        VENVBIN/bugsink-create-conf --template docker \
          --host localhost \
          --port "''${PORT:-8080}" \
          -o bugsink_conf.py
        KEY=$(VENVBIN/python -c "import secrets; print(secrets.token_urlsafe(50))")
        printf '\n# Generated by Hop3 on first deploy\nSECRET_KEY = "%s"\nALLOWED_HOSTS = ["*"]\n' "''${KEY}" >> bugsink_conf.py
      fi

      VENVBIN/bugsink-manage migrate --noinput

      exec VENVBIN/gunicorn bugsink.wsgi:application \
        --bind "0.0.0.0:''${PORT:-8080}" \
        --pythonpath . \
        --access-logfile - \
        --error-logfile -
      WRAPPER
      sed -i "s|VENVBIN|$out/venv/bin|g" $out/bin/bugsink-start
      chmod +x $out/bin/bugsink-start

      cat > $out/hop3/runtime.json << EOF
      {
        "workers": {
          "web": "$out/bin/bugsink-start"
        },
        "env": {},
        "path": [
          "$out/bin",
          "$out/venv/bin"
        ]
      }
      EOF
    '';
  };

in
{
  package = app;
  env = {};
}
