#!/bin/bash
# Bugsink setup: generate bugsink_conf.py (first run) then migrate.
set -e

: "${PGHOST:?ERROR: PGHOST is required}"

export DATABASE_URL="${DATABASE_URL:-postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}}"
export BASE_URL="${BASE_URL:-http://localhost:${PORT:-8080}}"

# bugsink_conf.py is the user settings module; bugsink-manage and
# bugsink.wsgi both set DJANGO_SETTINGS_MODULE=bugsink_conf and add
# cwd to sys.path. The docker template handles DATABASE_URL parsing.
#
# Bugsink's docker template reads SECRET_KEY from the environment, but
# env exports from this before-run script do not propagate to the
# uWSGI daemon. Persist a random SECRET_KEY directly into the generated
# conf file on first deploy so it survives across redeploys.
if [ ! -f bugsink_conf.py ]; then
    bugsink-create-conf --template docker \
        --host localhost \
        --port "${PORT:-8080}" \
        -o bugsink_conf.py
    KEY=$(python -c "import secrets; print(secrets.token_urlsafe(50))")
    printf '\n# Generated by Hop3 on first deploy\nSECRET_KEY = "%s"\nALLOWED_HOSTS = ["*"]\n' "${KEY}" >> bugsink_conf.py
fi

bugsink-manage migrate --noinput
