#!/bin/bash
# Bugsink setup: generate bugsink_conf.py (first run) then migrate.
set -e

: "${PGHOST:?ERROR: PGHOST is required}"

export DATABASE_URL="${DATABASE_URL:-postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}}"
export BASE_URL="${BASE_URL:-http://localhost:${PORT:-8080}}"

# bugsink_conf.py is the user settings module; bugsink-manage and
# bugsink.wsgi both set DJANGO_SETTINGS_MODULE=bugsink_conf and add
# cwd to sys.path. The docker template handles DATABASE_URL parsing.
#
# Bugsink's docker template reads SECRET_KEY from bugsink_conf.py. This conf file
# lives under src/, which the redeploy wipes and regenerates, so we must NOT mint
# a fresh key here — that would rotate SECRET_KEY on every redeploy, invalidating
# all sessions. Instead we write the stable ${SECRET_KEY} that Hop3 generates once
# on first deploy and re-injects unchanged on every redeploy
# ([env] SECRET_KEY = { generate = "urlsafe" } in hop3.toml, ADR 046).
if [ ! -f bugsink_conf.py ]; then
    : "${SECRET_KEY:?ERROR: SECRET_KEY is required (declare it as [env] generate in hop3.toml)}"
    bugsink-create-conf --template docker \
        --host localhost \
        --port "${PORT:-8080}" \
        -o bugsink_conf.py
    printf '\n# Generated by Hop3 on first deploy\nSECRET_KEY = "%s"\nALLOWED_HOSTS = ["*"]\n' "${SECRET_KEY}" >> bugsink_conf.py
fi

bugsink-manage migrate --noinput

# Bugsink keeps its background-task queue ("snappea") in a SEPARATE database
# (a SQLite queue), which `migrate` (default connection) does not touch — so
# without this the first task path 500s with "no such table: snappea_task".
# Idempotent; the snappea worker (see [run.workers]) then processes the queue.
bugsink-manage migrate --database=snappea --noinput

# Create the initial admin account from the credential Hop3 generated (ADR 056).
# Idempotent AND fail-loud: create only when no superuser exists yet, and let a
# real createsuperuser failure abort the deploy (set -e) rather than swallow it
# — a running app with no admin account is not a successful deploy. The
# HOP3_ADMIN_* vars are injected by the [admin] section; skip cleanly if unset
# (a deploy that predates ADR 056).
if [ -n "${HOP3_ADMIN_USER:-}" ] && [ -n "${HOP3_ADMIN_PASSWORD:-}" ]; then
    has_superuser=$(bugsink-manage shell -c \
        'from django.contrib.auth import get_user_model as g; print(1 if g().objects.filter(is_superuser=True).exists() else 0)' \
        2>/dev/null | tail -1)
    if [ "${has_superuser}" = "0" ]; then
        # Bugsink keys logins by username; email is a stored field.
        DJANGO_SUPERUSER_USERNAME="${HOP3_ADMIN_USER}" \
        DJANGO_SUPERUSER_EMAIL="${HOP3_ADMIN_EMAIL:-}" \
        DJANGO_SUPERUSER_PASSWORD="${HOP3_ADMIN_PASSWORD}" \
            bugsink-manage createsuperuser --noinput
    fi
fi
