apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: 127.0.0.1:5000/hello-world:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
