apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "hello-world.fullname" . }}
    - apiVersion: v1
      kind: Service
      name: {{ include "hello-world.fullname" . }}
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clustersAffinity }}
        - {{ . }}
        {{- end }}
