#!/usr/bin/env python3
"""
Build `bundle.pdf` from the individual experience reports.

Each report is converted to Typst with `md2typst`, then a generated
`bundle.typ` includes them all under `bundle-style.typ`. The style owns every
visual decision — including the page break before each report — so the parts
stay as close to md2typst's output as possible and nothing here has to know
what a heading looks like.

    ./build.py            # bundle.pdf
    ./build.py --keep     # …and leave build/ in place to inspect the Typst

`md2typst` emits a self-contained document: a `#let doc-*` preamble carrying the
report's YAML front matter, then a `#doc-make-title()` call, then the body. For
a bundle we want only the body — the visible title is each report's own `# H1`,
and a per-report centred title block would be a second, competing one. So the
preamble is cut. Nothing here reads the front matter: `hop3-tools catalog
reports` is what validates it, and a second reader of the same YAML would be a
second thing to keep in step.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUILD = HERE / "build"
STYLE = "bundle-style.typ"
PDF = HERE / "bundle.pdf"

TITLE = "Hop3 — Application Experience Reports"
SUBTITLE = (
    "Twenty applications packaged across four build paths, and what each one "
    "cost the platform"
)

#: md2typst's preamble ends here. Everything above is generated metadata and a
#: title block the bundle supplies itself.
PREAMBLE_END = re.compile(r"^#doc-make-title\(\)\s*$", re.MULTILINE)


def reports() -> list[Path]:
    """The aggregate first, then every current report, alphabetically.

    `withdrawn/` is not included: those applications are no longer in the
    corpus, and a bundle that presents them alongside current ones re-creates
    exactly the confusion withdrawing them resolved.
    """
    aggregate = HERE / "00-aggregate.md"
    rest = sorted(
        p
        for p in HERE.glob("*.md")
        if p.name != "TEMPLATE.md"
        and not p.name.startswith("00")
        # `_bundle.md` is `hop3-tools catalog reports --bundle` output: every
        # report concatenated. Including it puts the whole corpus in twice, and
        # the result looks like a plausible 123-page document. A build must not
        # consume its own output, so anything `_`-prefixed is generated and out.
        and not p.name.startswith("_")
    )
    return ([aggregate] if aggregate.exists() else []) + rest


def convert(md: Path, out_dir: Path) -> Path:
    """One report as a Typst fragment: md2typst output, preamble removed."""
    raw = out_dir / f"{md.stem}.raw.typ"
    subprocess.run(
        ["uv", "run", "md2typst", "-o", str(raw), str(md)],
        cwd=HERE.parents[1],
        check=True,
        capture_output=True,
        text=True,
    )
    text = raw.read_text()
    if text.lstrip().startswith("#let doc-"):
        # There is a preamble, so there must be a title call ending it. Fail
        # rather than emit a part with a stray centred title block: a bundle
        # that silently gains a second title per report is the kind of defect
        # nobody reads a 200-page PDF closely enough to catch.
        match = PREAMBLE_END.search(text)
        if not match:
            msg = (
                f"{md.name}: md2typst emitted a '#let doc-' preamble with no "
                f"'#doc-make-title()' line to end it. Its output format has "
                f"changed; update PREAMBLE_END."
            )
            raise SystemExit(msg)
        body = text[match.end() :].lstrip("\n")
    else:
        # No YAML front matter in the source (the aggregate), so md2typst emits
        # the body alone and there is nothing to strip.
        body = text

    # Parts live in build/, one level below the images they reference.
    body = body.replace('image("images/', 'image("../images/')

    part = out_dir / f"{md.stem}.typ"
    part.write_text(body)
    raw.unlink()
    return part


def bundle_typ(parts: list[Path]) -> str:
    """The master document: style, cover, then every part in order."""
    lines = [
        "// GENERATED by build.py — edit bundle-style.typ or the reports, not this.",
        f'#import "../{STYLE}": bundle',
        "",
        "#show: bundle.with(",
        f'  title: "{TITLE}",',
        f'  subtitle: "{SUBTITLE}",',
        f'  date: "{stamp()}",',
        '  status: "draft",',
        ")",
        "",
    ]
    lines.extend(f'#include "{p.name}"' for p in parts)
    return "\n".join(lines) + "\n"


def stamp() -> str:
    """The date of the newest report, not today's.

    A cover dated by the build would claim freshness the contents may not have;
    `git log` is the honest source and falls back to the file mtimes.
    """
    out = subprocess.run(
        ["git", "log", "-1", "--format=%cs", "--", str(HERE)],
        cwd=HERE.parents[1],
        capture_output=True,
        text=True,
        check=False,
    )
    date = out.stdout.strip()
    if date:
        return date
    newest = max(p.stat().st_mtime for p in reports())
    return dt.datetime.fromtimestamp(newest, tz=dt.UTC).date().isoformat()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--keep", action="store_true", help="leave build/ in place afterwards"
    )
    parser.add_argument("-o", "--output", type=Path, default=PDF)
    args = parser.parse_args()

    for tool in ("uv", "typst"):
        if not shutil.which(tool):
            msg = f"{tool} is not on PATH; cannot build the bundle"
            raise SystemExit(msg)

    docs = reports()
    if not docs:
        # An empty bundle is a 2-page PDF that looks like a successful build.
        msg = f"no reports found in {HERE}"
        raise SystemExit(msg)

    BUILD.mkdir(exist_ok=True)
    parts = [convert(md, BUILD) for md in docs]
    print(f"--> {len(parts)} report(s) converted")

    master = BUILD / "bundle.typ"
    master.write_text(bundle_typ(parts))

    # Root is the reports directory: Typst refuses to read above its root, and
    # the parts reach ../images/ from build/.
    subprocess.run(
        ["typst", "compile", "--root", str(HERE), str(master), str(args.output)],
        check=True,
    )
    shown = (
        args.output.relative_to(Path.cwd())
        if args.output.is_relative_to(Path.cwd())
        else args.output
    )
    print(f"--> Wrote {shown}")

    if not args.keep:
        shutil.rmtree(BUILD)
    return 0


if __name__ == "__main__":
    sys.exit(main())
