[project]
name = "hop3-server"
version = "0.2.3"
description = "Simple PaaS - Deploy and manage web applications on a single server"
authors = [
    { name = "Stefane Fermigier", email = "sf@abilian.com" },
]
readme = "README.md"

dependencies = [
    # Web / app server
    # "granian>=2,<3",
    "starlette>=0.40",
    "attrs >= 24.2",
    # "cattrs",
    # Plugins and DI
    "pluggy ~= 1.4",
    "wireup ~= 1.0",
    # Database
    "sqlalchemy ~= 2.0",
    "advanced-alchemy >= 0.21",
    # Misc
    "termcolor >= 2.5.0",
    # SBOM
    "cyclonedx-bom >= 5.1.1",
    "toml >= 0.10.2",
    # Utils
    "devtools",
    "granian>=2.2.0",
    "psycopg2>=2.9.10",
    "webargs>=8.6.0",
    "marshmallow>=4.0.0",
]

[dependency-groups]
dev = [
    "typing-extensions>=4.12.2",
]

[project.scripts]
hop-server = "hop3.server.cli:main"

# ----------------------------------------

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/hop3"]

# ----------------------------------------

[tool.pyright]
exclude = [
    "src/hop3/util/templating.py",
    "src/hop3/server/old_cli/",
]

# -----------------------------------------------------------------------------

[tool.deptry.per_rule_ignores]
# X defined as a dependency but not used in the codebase
DEP002 = [
    "cyclonedx-bom",
]
#DEP003 = [
#    "snoop",
#]
