#!/bin/bash
# Setup Gitea configuration from environment variables

set -e

PORT="${PORT:-8080}"
DB_TYPE="${DB_TYPE:-postgres}"
DB_HOST="${PGHOST:-localhost}"
DB_PORT="${PGPORT:-5432}"
DB_NAME="${PGDATABASE:-gitea}"
DB_USER="${PGUSER:-gitea}"
DB_PASS="${PGPASSWORD:-}"

# Security secrets are stable [env] { generate } values injected by Hop3 (ADR
# 046): generated once on first deploy and re-injected unchanged on every
# redeploy. We WRITE them into app.ini instead of letting Gitea mint its own,
# because the redeploy replaces this source tree (app.ini with it) — a secret
# generated here (or auto-generated by Gitea into app.ini) would rotate on
# every redeploy, making 2FA/encrypted data undecryptable (SECRET_KEY),
# invalidating OAuth2 tokens (JWT_SECRET) and breaking internal auth
# (INTERNAL_TOKEN). Fail loud if somehow absent (a generated var is always
# present on a real deploy).
SECRET_KEY="${SECRET_KEY:?SECRET_KEY not injected; declare it as an [env] generate secret in hop3.toml}"
INTERNAL_TOKEN="${INTERNAL_TOKEN:?INTERNAL_TOKEN not injected; declare it as an [env] generate secret in hop3.toml}"
JWT_SECRET="${JWT_SECRET:?JWT_SECRET not injected; declare it as an [env] generate secret in hop3.toml}"

mkdir -p custom/conf

cat > custom/conf/app.ini << EOF
[server]
HTTP_PORT = ${PORT}
ROOT_URL = ${HOP3_PUBLIC_URL:-http://localhost:${PORT}}/

[database]
DB_TYPE = ${DB_TYPE}
HOST = ${DB_HOST}:${DB_PORT}
NAME = ${DB_NAME}
USER = ${DB_USER}
PASSWD = ${DB_PASS}

[repository]
ROOT = data/gitea-repositories

[service]
; Disable open registration so a stranger can't seize the first-admin slot;
; Hop3 provisions the intended admin via [admin].create.
DISABLE_REGISTRATION = true

[log]
MODE = console
LEVEL = Info

[security]
INSTALL_LOCK = true
; Stable secrets injected by Hop3 ([env] { generate }, ADR 046). Written here so
; they survive the source-replacing redeploy instead of rotating each deploy.
SECRET_KEY = ${SECRET_KEY}
INTERNAL_TOKEN = ${INTERNAL_TOKEN}

[oauth2]
JWT_SECRET = ${JWT_SECRET}
EOF

echo "Gitea configuration created"
