ServerName %{HTTP_HOST}

<VirtualHost *:80>
    DocumentRoot /app/code

    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    CustomLog "|/bin/cat" proxy
    ErrorLog "|/bin/cat"

    <Directory /app/code/>
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # some directories must be protected
    # data directory is outside /app/code, so nothing to do
    <Directory /app/code/config>
        Options -FollowSymLinks
        AllowOverride None

        <IfModule mod_php.c>
            php_admin_flag engine off
        </IfModule>
    </Directory>
</VirtualHost>
