# Copyright (c) 2025-2026, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""
Docker deployment backend for local containers.

Trust model
-----------
This module is loaded *only* by ``hop3-deploy``, the developer-facing
deploy tool used to spin up a throwaway Docker container for local
testing and CI. It is **never** imported by ``hop3-install`` (the
production server installer) — see ``packages/hop3-installer/CLAUDE.md``
for the entry-point split.

The hardcoded ``E2E_TEST_SECRET_KEY`` below is the supervisor's
*fallback* JWT signing key, used only when the installer hasn't written
``/etc/hop3/secret-key`` (which the server reads first, and which the
installer normally generates). The harness doesn't assume this key: it
reads whichever key the container actually validates with
(``DockerTarget._read_server_secret_key``) and mints tokens with that.
Keeping a known fallback is still safe — the container is ephemeral and
bound to localhost ports. If this module is ever loaded in a context
where ``MODE=production``, that is a bug; we abort at backend
construction time rather than risk shipping the test key into a
real deploy.
"""

from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar

from hop3_installer.common import CommandResult, ServiceStartError

from .base import DeployBackend

if TYPE_CHECKING:
    from hop3_installer.deployer.config import DeployConfig

# E2E test secret key - must match hop3-testing/src/hop3_testing/targets/constants.py
# DO NOT change this string and DO NOT reuse it outside the developer
# Docker deploy backend; see the trust-model note at the top of the file.
E2E_TEST_SECRET_KEY = "e2e-test-secret-key-do-not-use-in-production"

# Where `hop3-fetch` keeps downloaded build inputs inside the container, and the
# named volume that backs it. On a real server the cache lives under the hop3
# home and persists by itself; here the container is thrown away between runs,
# so without a volume every catalog run re-downloads every tarball — which is
# what got this address rate-limited by GitHub in the first place.
#
# A named volume, not a bind mount: it survives `docker rm`, and `chown` works
# on it (a macOS bind mount presents its own ownership, so the hop3 user could
# not write there). Clear it with `docker volume rm hop3-download-cache`.
DOWNLOAD_CACHE_VOLUME = "hop3-download-cache"
DOWNLOAD_CACHE_PATH = "/var/cache/hop3-downloads"

# Labels stamped on every container this backend creates, so a later run can
# recognise one of ours and find out whether anybody still owns it.
MARKER_LABEL = "hop3.test.container"
OWNER_LABEL = "hop3.test.owner-pid"

# Supervisor configuration for Hop3 services in Docker
SUPERVISOR_CONFIG = f"""\
# Supervisor configuration for Hop3 services in Docker
# Auto-generated by hop3-deploy

# Privileged-operations daemon. The deploy path reloads nginx (and other
# privileged ops) through this daemon, NOT passwordless sudo -- proxy setup
# aborts loudly if its socket is absent. In production a hardened systemd unit
# runs it; under Docker (no systemd as PID 1) supervisor is the process manager.
# Runs as root and creates /run/hop3-rootd/socket with group hop3 so the
# hop3-user server can reach it. Started first (low priority) so it's up before
# the first deploy.
[program:hop3-rootd]
command=/home/hop3/venv/bin/hop3-rootd --socket-path /run/hop3-rootd/socket
autostart=true
autorestart=true
priority=1
stdout_logfile=/var/log/supervisor/hop3-rootd.log
stderr_logfile=/var/log/supervisor/hop3-rootd_err.log

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_err.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:uwsgi]
command=/home/hop3/venv/bin/uwsgi --emperor /home/hop3/uwsgi-enabled --uid hop3 --gid hop3
directory=/home/hop3
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/uwsgi.log
stderr_logfile=/var/log/supervisor/uwsgi_err.log

[program:hop3-server]
command=/home/hop3/venv/bin/hop3-server serve
directory=/home/hop3
user=hop3
autostart=true
autorestart=true
environment=HOME="/home/hop3",HOP3_SECRET_KEY="{E2E_TEST_SECRET_KEY}",HOP3_DB_URL="sqlite:////home/hop3/hop3.db",ACME_ENGINE="self-signed",HOP3_DOWNLOAD_CACHE="{DOWNLOAD_CACHE_PATH}"
stdout_logfile=/var/log/supervisor/hop3-server.log
stderr_logfile=/var/log/supervisor/hop3-server_err.log
"""


def _process_is_alive(pid_text: str) -> bool:
    """
    Whether the process that created a container is still running.

    Signal 0 performs the permission and existence checks without delivering
    anything. A PermissionError means the pid exists under another user, which
    still counts as alive. A recycled pid reads as alive and the conflict is
    reported instead of reclaimed — erring toward the older, manual behaviour,
    which is the safe direction to be wrong in.
    """
    try:
        os.kill(int(pid_text), 0)
    except (ProcessLookupError, ValueError):
        return False
    except PermissionError:
        return True
    return True


class DockerDeployBackend(DeployBackend):
    """
    Backend for deploying to local Docker containers.

    This backend builds a Docker image using a Dockerfile, leveraging
    Docker's layer caching for fast rebuilds. The image is built fresh
    each time, but Docker caches unchanged layers so subsequent builds
    are nearly instant if nothing changed.
    """

    name = "docker"

    # Image name for built test image
    TEST_IMAGE = "hop3-test:latest"

    # Required ports: (host_port, container_port, description)
    REQUIRED_PORTS: ClassVar[list[tuple[int, int, str]]] = [
        (8000, 8000, "Hop3 API"),
        (8080, 80, "HTTP"),
        (8443, 443, "HTTPS"),
    ]

    def __init__(self, config: DeployConfig) -> None:
        # Belt-and-suspenders interlock: this backend embeds a known JWT
        # signing key in its supervisor config (see E2E_TEST_SECRET_KEY).
        # Refuse to construct the backend if MODE=production so the key
        # can never reach a production-shaped deploy by accident.
        if os.environ.get("MODE", "").strip().lower() in {"production", "prod"}:
            msg = (
                "DockerDeployBackend is a developer-only deploy backend with a "
                "hardcoded E2E test signing key; it must not be used with "
                "MODE=production. Use the SSH backend or hop3-install instead."
            )
            raise RuntimeError(msg)

        super().__init__(config)
        self.container_name = config.docker_container
        self.image = self.TEST_IMAGE
        self._dockerfile_path = self._find_dockerfile()

    def _find_dockerfile(self) -> Path | None:
        """Find the Dockerfile for building the test image."""
        # Look for Dockerfile in known locations
        possible_paths = [
            self.config.project_root
            / "packages"
            / "hop3-installer"
            / "docker"
            / "Dockerfile.base",
            Path(__file__).parent.parent.parent.parent / "docker" / "Dockerfile.base",
        ]
        for path in possible_paths:
            if path.exists():
                return path
        return None

    def _build_image(self) -> bool:
        """
        Build the Docker image using docker build.

        Docker automatically uses layer caching, so unchanged layers
        are reused and rebuilds are fast.
        """
        if not self._dockerfile_path:
            print("  ✗ Dockerfile not found, falling back to direct apt-get install")
            return False

        print("  → Building Docker image (using layer cache)...")
        print(f"    Dockerfile: {self._dockerfile_path}")

        build_cmd = [
            "docker",
            "build",
            "-f",
            str(self._dockerfile_path),
            "-t",
            self.TEST_IMAGE,
            str(self.config.project_root),
        ]

        result = subprocess.run(
            build_cmd,
            capture_output=False,  # Show build output
            check=False,
        )

        if result.returncode != 0:
            print(f"  ✗ Docker build failed (exit code {result.returncode})")
            return False

        print(f"  ✓ Image built: {self.TEST_IMAGE}")
        return True

    def _docker_available(self) -> bool:
        """Check if Docker is available."""
        try:
            result = subprocess.run(
                ["docker", "info"],
                capture_output=True,
                text=True,
                check=False,
            )
            return result.returncode == 0
        except FileNotFoundError:
            return False

    def _container_exists(self) -> bool:
        """Check if the container exists."""
        result = subprocess.run(
            ["docker", "ps", "-a", "--filter", f"name=^{self.container_name}$", "-q"],
            capture_output=True,
            text=True,
            check=False,
        )
        return bool(result.stdout.strip())

    def _container_running(self) -> bool:
        """Check if the container is running."""
        result = subprocess.run(
            ["docker", "ps", "--filter", f"name=^{self.container_name}$", "-q"],
            capture_output=True,
            text=True,
            check=False,
        )
        return bool(result.stdout.strip())

    def _running_image(self) -> str | None:
        """The image the running container was created from, if it can be read."""
        result = subprocess.run(
            [
                "docker",
                "inspect",
                self.container_name,
                "--format",
                "{{.Config.Image}}",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        return result.stdout.strip() or None

    def _remove_container(self) -> None:
        """Remove the container if it exists."""
        subprocess.run(
            ["docker", "rm", "-f", self.container_name],
            capture_output=True,
            check=False,
        )

    def _check_ports_available(self) -> list[tuple[int, str, str]]:
        """
        Check if required ports are available.

        Returns:
            List of (port, container_name, description) for ports in use
        """
        conflicts: list[tuple[int, str, str]] = []

        # Check what's using our ports via docker ps
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}\t{{.Ports}}"],
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            return conflicts

        for line in result.stdout.strip().split("\n"):
            if not line:
                continue
            parts = line.split("\t", 1)
            if len(parts) < 2:
                continue
            container_name, ports_str = parts

            # Skip our own container (will be removed anyway)
            if container_name == self.container_name:
                continue

            # Check each required port
            for host_port, _container_port, desc in self.REQUIRED_PORTS:
                # Look for port mapping like "0.0.0.0:8080->80/tcp"
                if f":{host_port}->" in ports_str or f":{host_port}/" in ports_str:
                    conflicts.append((host_port, container_name, desc))

        return conflicts

    def _reclaim_orphans(self, conflicts: list[tuple[int, str, str]]) -> list[str]:
        """
        Remove conflicting containers this tool created whose run is gone.

        A run killed by Ctrl-C, a timeout or an OOM cannot tear its own
        container down, and the container keeps holding ports 8000/8080/8443.
        The next run — quite possibly a *different* harness, since `hop3-test`
        and the pytest e2e layer use different container names but the same
        host ports — then fails before it starts, and only a hand-typed
        `docker rm -f` clears it. Per the project's own rule, a leftover that
        blocks the next deploy is a platform bug, not something to tell the
        operator to go fix.

        Only containers carrying this backend's label are ever touched, and
        only when the process that created them is gone: a live run's container
        is somebody's work in progress, and taking it out from under them would
        be worse than the conflict. Unlabelled containers (someone else's, or
        one from an older build) are left alone too.

        Returns the names reclaimed.
        """
        reclaimed: list[str] = []
        for name in dict.fromkeys(container for _, container, _ in conflicts):
            owner = self._container_label(name, OWNER_LABEL)
            if owner is None:
                continue  # not ours — never touch it
            if _process_is_alive(owner):
                continue  # somebody is still using it; conflict is real
            print(
                f"  → Reclaiming '{name}': it belongs to hop3 run pid {owner}, "
                "which is no longer running (a killed run cannot clean up "
                "after itself)."
            )
            subprocess.run(
                ["docker", "rm", "-f", name], capture_output=True, check=False
            )
            reclaimed.append(name)
        return reclaimed

    def _container_label(self, name: str, label: str) -> str | None:
        """Return a label's value, or None if absent or the container is gone."""
        result = subprocess.run(
            [
                "docker",
                "inspect",
                "-f",
                f'{{{{index .Config.Labels "{label}"}}}}',
                name,
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            return None
        value = result.stdout.strip()
        # `docker inspect` prints "<no value>" for a label that is not set.
        return value if value and value != "<no value>" else None

    def _report_port_conflicts(self, conflicts: list[tuple[int, str, str]]) -> None:
        """Report port conflict error to user."""
        print("  ✗ Port conflict detected!")
        print()
        print("  The following ports are already in use by other containers:")
        for port, container, desc in conflicts:
            print(f"    - Port {port} ({desc}): used by container '{container}'")
        print()
        print("  To resolve this, either:")
        print(f"    1. Stop the conflicting container: docker stop {conflicts[0][1]}")
        print(f"    2. Remove it entirely: docker rm -f {conflicts[0][1]}")
        print()

    def _start_container(self) -> bool:
        """
        Start a new Docker container.

        Returns:
            True if container started successfully, False otherwise.
        """
        print(f"  → Starting container from {self.image}...")
        run_result = subprocess.run(
            [
                "docker",
                "run",
                "-d",
                # A real init as PID 1, so exited children get reaped.
                #
                # PID 1 was `sleep infinity`, which never calls wait(). Anything
                # that forked a helper and waited for it to disappear then hung
                # on a zombie: mysql-server-8.0's postinst starts a temporary
                # mysqld, shuts it down cleanly, and polls for the pid to go —
                # the pid stayed, so it reported "Unable to shut down server",
                # dpkg failed, and the whole install died three steps later
                # under an unrelated error about apt-utils. Any package whose
                # postinst does the same would have hit it.
                "--init",
                # rootd manages the host firewall through nftables — it opens
                # each app's fixed [[ports]] in the `inet hop3` table. That needs
                # CAP_NET_ADMIN, which a container does not get by default.
                #
                # This was invisible while `nftables` was missing from the
                # installer's package list: with no `nft` binary, rootd skipped
                # reconciliation and started. Installing the package made it try,
                # and `nft add table inet hop3` returned "Operation not
                # permitted" — on which rootd exits. The socket at
                # /run/hop3-rootd/socket never appeared and EVERY deploy failed
                # at proxy reload, which also goes through rootd.
                #
                # The container is standing in for a server that manages its own
                # firewall, so it needs the capability that implies. Without it,
                # apps declaring fixed ports (owncast, matrix-synapse) can never
                # be tested here at all.
                "--cap-add=NET_ADMIN",
                "--name",
                self.container_name,
                # Who owns this container. A run that is killed cannot clean up
                # after itself — SIGKILL leaves no chance to — so the next run
                # has to be able to tell an abandoned container from one a live
                # run is using. The pid is that signal; see _reclaim_orphans.
                "--label",
                f"{OWNER_LABEL}={os.getpid()}",
                "--label",
                f"{MARKER_LABEL}=1",
                "-v",
                f"{self.config.project_root}:/hop3:ro",
                "-v",
                f"{DOWNLOAD_CACHE_VOLUME}:{DOWNLOAD_CACHE_PATH}",
                "-p",
                "8000:8000",
                "-p",
                "8080:80",
                "-p",
                "8443:443",
                self.image,
                "sleep",
                "infinity",
            ],
            capture_output=True,
            text=True,
            check=False,
        )

        if run_result.returncode != 0:
            print("  ✗ Failed to start container")
            if run_result.stderr:
                print(f"  Error: {run_result.stderr.strip()}")
            return False
        return True

    def _wait_for_container_ready(self, timeout_seconds: int = 15) -> bool:
        """
        Wait for container to be running.

        Args:
            timeout_seconds: Maximum time to wait.

        Returns:
            True if container is ready, False if timeout.
        """
        for _ in range(timeout_seconds * 2):  # Check every 0.5s
            if self._container_running():
                return True
            time.sleep(0.5)

        print("  ✗ Container failed to start within timeout")
        return False

    def _install_fallback_packages(self) -> bool:
        """
        Install base packages when using fallback ubuntu image.

        Returns:
            True if packages installed successfully, False otherwise.
        """
        print(
            "  → Installing base packages in container (this may take a few minutes)..."
        )
        install_cmd = (
            "apt-get update && apt-get install -y python3 python3-venv git curl sudo"
        )
        exit_code = self.run_streaming(install_cmd)
        if exit_code != 0:
            print(f"  ✗ Failed to install base packages (exit code {exit_code})")
            return False
        print("  ✓ Base packages installed")
        return True

    def setup(self) -> bool:
        """
        Start Docker container for deployment.

        This method:
        1. Builds the Docker image using docker build (with layer caching)
        2. Starts a container from the built image

        Docker's layer caching means subsequent builds are fast if
        the Dockerfile hasn't changed.
        """
        if not self._docker_available():
            print("  ✗ Docker is not available")
            return False

        # Reuse a running container unless --clean was asked for: a second
        # deploy then hits the in-place UPDATE path (upgrade) instead of a
        # fresh install. --clean (or no running container) forces a rebuild.
        if self._container_running() and not self.config.clean_before:
            running = self._running_image()
            if running and running != self.image:
                # Reusing a container built from a different base silently
                # installs onto the wrong distribution, and the mismatch only
                # surfaces much later as a confusing package failure.
                print(
                    f"  → Container {self.container_name} runs {running}, "
                    f"but {self.image} was requested — recreating"
                )
                return self._create_fresh_container()
            print(f"  → Reusing running container {self.container_name} (no --clean)")
            return True

        return self._create_fresh_container()

    def _create_fresh_container(self) -> bool:
        """Drop any existing container and start a clean one."""
        # Drop any existing one FIRST so the port check and start don't
        # collide with a stale container of our own.
        self._remove_container()

        # Check for port conflicts (now that our own container is gone)
        conflicts = self._check_ports_available()
        if conflicts:
            # An abandoned container of ours is ours to clear; a live one is not.
            if self._reclaim_orphans(conflicts):
                conflicts = self._check_ports_available()
        if conflicts:
            self._report_port_conflicts(conflicts)
            return False

        # Build image using Dockerfile (with layer caching)
        image_built = self._build_image()

        # If build failed or no Dockerfile, fall back to ubuntu
        if not image_built:
            self.image = "ubuntu:24.04"
            print(f"  → Falling back to {self.image}")

        # Start and wait for container
        if not self._start_container():
            return False

        if not self._wait_for_container_ready():
            return False

        # If we fell back to ubuntu, install packages manually
        if not image_built:
            return self._install_fallback_packages()

        print("  ✓ Container ready (packages pre-installed via cached layers)")
        return True

    def teardown(self) -> None:
        """Stop and remove the container."""
        subprocess.run(
            ["docker", "rm", "-f", self.container_name],
            capture_output=True,
            check=False,
        )

    def run(
        self,
        command: str,
        *,
        check: bool = True,
        stdin: str | None = None,
    ) -> CommandResult:
        """Run a command in the container."""
        docker_cmd = [
            "docker",
            "exec",
            *(["-i"] if stdin is not None else []),
            self.container_name,
            "bash",
            "-c",
            command,
        ]

        result = subprocess.run(
            docker_cmd,
            input=stdin,
            capture_output=True,
            text=True,
            check=False,
        )

        cmd_result = CommandResult.from_subprocess(result)
        self._raise_if_failed(cmd_result, command, check=check)
        return cmd_result

    def run_streaming(
        self, command: str, *, quiet: bool = False, log_file: Path | None = None
    ) -> int:
        """Run a command with output handling based on mode."""
        docker_cmd = [
            "docker",
            "exec",
            "-e",
            "PYTHONUNBUFFERED=1",
            "-e",
            "DEBIAN_FRONTEND=noninteractive",
            self.container_name,
            "bash",
            "-c",
            command,
        ]

        if quiet:
            # Capture output for log file
            result = subprocess.run(
                docker_cmd, capture_output=True, text=True, check=False
            )
            if log_file:
                self._write_log_output(
                    log_file, command, result.returncode, result.stdout, result.stderr
                )
            return result.returncode

        # Stream directly to terminal
        result = subprocess.run(docker_cmd, check=False)  # type: ignore[assignment]
        return result.returncode

    def upload_file(self, local_path: Path, remote_path: str) -> bool:
        """Copy a file into the container."""
        result = subprocess.run(
            ["docker", "cp", str(local_path), f"{self.container_name}:{remote_path}"],
            capture_output=True,
            check=False,
        )
        return result.returncode == 0

    def upload_dir(self, local_path: Path, remote_path: str) -> bool:
        """Copy a directory into the container."""
        # docker cp works for directories too
        result = subprocess.run(
            ["docker", "cp", str(local_path), f"{self.container_name}:{remote_path}"],
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            # Fix permissions
            self.run(f"chmod -R a+rX {remote_path}", check=False)
        return result.returncode == 0

    def clean(self) -> None:
        """
        Clean the container for fresh installation.

        No addon storage to reclaim here, unlike the SSH backend: `--clean`
        forces `_create_fresh_container()`, so MySQL/PostgreSQL/Redis and their
        data are destroyed with the container itself. This is belt and braces on
        a container that is about to be replaced.
        """
        commands = [
            "systemctl stop hop3-server 2>/dev/null || true",
            "rm -rf /home/hop3",
            "userdel -r hop3 2>/dev/null || true",
            "groupdel hop3 2>/dev/null || true",
        ]

        for cmd in commands:
            self.run(cmd, check=False)

    def get_server_url(self) -> str:
        """Get the URL to access the server."""
        return "http://localhost:8000"

    def get_container_ip(self) -> str | None:
        """Get the container's internal IP address."""
        result = subprocess.run(
            [
                "docker",
                "inspect",
                "-f",
                "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}",
                self.container_name,
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None

    def service_restart_command(self, service: str) -> str:
        """
        Supervisor manages services in the container — there is no systemd.

        The upgrade path restarts hop3-server here; using ``systemctl`` would
        silently no-op (systemctl can't run without a systemd PID 1), leaving
        the old code serving while the deploy reports success.
        """
        return f"supervisorctl restart {service}"

    def service_logs_command(self, service: str) -> str:
        """Supervisor keeps the logs here; there is no journal in a container."""
        return f"supervisorctl tail -100 {service}"

    def start_services(self) -> None:
        """
        Start supervisor to manage services after Hop3 installation.

        This replaces systemd in Docker environments. Supervisor manages:
        - sshd: SSH server
        - nginx: Reverse proxy
        - uwsgi: Application processes (emperor mode)
        - hop3-server: Hop3 API server

        Raises:
            ServiceStartError: If services fail to start.
        """
        print("  → Setting up supervisor to manage services...")

        # Docker creates the volume's mountpoint root-owned, but builds run as
        # hop3 — so hand it over before anything tries to write a download there.
        # Non-recursive: existing entries were written by this same uid on an
        # earlier run.
        self.run(f"chown hop3:hop3 {DOWNLOAD_CACHE_PATH}")

        # Write supervisor config
        config_cmd = (
            f"cat > /etc/supervisor/conf.d/hop3.conf << 'EOF'\n{SUPERVISOR_CONFIG}EOF"
        )
        result = self.run(config_cmd, check=False)
        if not result.success:
            msg = "Failed to write supervisor config"
            print(f"  ✗ {msg}")
            raise ServiceStartError(msg)

        # Check if supervisord is already running
        result = self.run("pgrep -x supervisord", check=False)
        if result.success:
            # Supervisord is running, just reload config
            print("  → Reloading supervisor config...")
            result = self.run(
                "supervisorctl reread && supervisorctl update", check=False
            )
        else:
            # Start supervisord in background. It daemonizes (the config sets no
            # `nodaemon`), so this returns and the container keeps its own
            # long-running process as PID 1.
            #
            # There used to be a `pkill -f 'sleep infinity'` here, to "kill the
            # sleep process that's keeping the container alive". It never did:
            # `sleep infinity` WAS pid 1, and the kernel discards a signal sent
            # to pid 1 when pid 1 installed no handler for it. Under `--init`
            # tini is pid 1 and the sleep is an ordinary child, so the same line
            # would kill it for real — and tini exits when its child does,
            # taking the container down in the middle of its own deploy.
            print("  → Starting supervisord...")
            result = self.run(
                "supervisord -c /etc/supervisor/supervisord.conf",
                check=False,
            )

        if not result.success:
            msg = "Failed to start supervisor"
            print(f"  ✗ {msg}")
            raise ServiceStartError(msg)

        # Wait for services to start
        print("  → Waiting for services to start...")
        time.sleep(3)

        # Verify services are running
        result = self.run("supervisorctl status", check=False)
        if result.success:
            running_count = result.stdout.count("RUNNING")
            print(f"  ✓ Supervisor started ({running_count} services running)")
        else:
            print("  ⚠ Supervisor started but some services may have issues")
