#!/usr/bin/env python3
"""Generate /etc/hosts entries for Hop3 tutorial apps.

Usage:
    ./generate-hosts.py <hop3-server-ip> <domain>

Example:
    ./generate-hosts.py 192.168.1.100 hop3.dev

    # Then add output to /etc/hosts:
    sudo ./generate-hosts.py 192.168.1.100 hop3.dev >> /etc/hosts

    # And set the environment variable for tutotest:
    export HOP3_TEST_DOMAIN=hop3.dev

Output (append to /etc/hosts):
    192.168.1.100 hop3-tuto-bottle.hop3.dev hop3-tuto-flask.hop3.dev ...
"""

import sys
from pathlib import Path

# Tutorial app names (must match the 'id' in each tutorial's hop3.toml)
TUTORIAL_APPS = [
    # Python (12)
    "hop3-tuto-bottle",
    "hop3-tuto-django",
    "hop3-tuto-drf",
    "hop3-tuto-eve",
    "hop3-tuto-falcon",
    "hop3-tuto-fastapi",
    "hop3-tuto-flask",
    "hop3-tuto-litestar",
    "hop3-tuto-pyramid",
    "hop3-tuto-robyn",
    "hop3-tuto-sanic",
    "hop3-tuto-starlette",
    # JavaScript (7)
    "hop3-tuto-astro",
    "hop3-tuto-eleventy",
    "hop3-tuto-express",
    "hop3-tuto-fastify",
    "hop3-tuto-nestjs",
    "hop3-tuto-nextjs",
    "hop3-tuto-nuxtjs",
    # Ruby (3)
    "hop3-tuto-jekyll",
    "hop3-tuto-rails",
    "hop3-tuto-sinatra",
    # PHP (2)
    "hop3-tuto-laravel",
    "hop3-tuto-symfony",
    # Java (2)
    "hop3-tuto-quarkus",
    "hop3-tuto-spring-boot",
    # Go (3)
    "hop3-tuto-fiber",
    "hop3-tuto-gin",
    "hop3-tuto-hugo",
    # Rust (2)
    "hop3-tuto-actix-web",
    "hop3-tuto-axum",
    # Elixir (1)
    "hop3-tuto-phoenix",
    # .NET (1)
    "hop3-tuto-aspnet-core",
]


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    server_ip = sys.argv[1]
    domain = sys.argv[2]

    # Generate hostnames
    hostnames = [f"{app}.{domain}" for app in TUTORIAL_APPS]

    # Output in /etc/hosts format
    print(f"# Hop3 tutorial apps - add to /etc/hosts")
    print(f"# Generated by: {Path(__file__).name}")
    print(f"# Run tutotest with: HOP3_TEST_DOMAIN={domain} tutotest run <tutorial.md>")
    print(f"#")
    print(f"{server_ip} {' '.join(hostnames)}")
    print()
    print(f"# Total: {len(TUTORIAL_APPS)} tutorial apps")


if __name__ == "__main__":
    main()
