# Copyright (c) 2025-2026, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""Configuration for server installer."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from hop3_installer.common import env_bool, env_str

# Package configuration
PACKAGE_NAME = "hop3-server"
GIT_REPO = "https://github.com/abilian/hop3.git"
GIT_SUBDIR = "packages/hop3-server"
DEFAULT_BRANCH = "main"

# User configuration
HOP3_USER = "hop3"
HOP3_GROUP = "hop3"
HOME_DIR = Path("/home") / HOP3_USER
VENV_DIR = HOME_DIR / "venv"

# SSL certificate configuration
SSL_DIR = Path("/etc/hop3/ssl")
SSL_CERT = SSL_DIR / "hop3.crt"
SSL_KEY = SSL_DIR / "hop3.key"
SSL_CERT_VALIDITY_DAYS = 3650  # 10 years for self-signed certificates

# All available optional features
ALL_FEATURES = {"mysql", "redis", "docker"}

# Systemd service units
SYSTEMD_UNIT = """[Unit]
Description=Hop3 Server
After=network.target postgresql.service

[Service]
Type=simple
User=hop3
Group=hop3
WorkingDirectory=/home/hop3
EnvironmentFile=/etc/default/hop3
ExecStart=/home/hop3/venv/bin/hop3-server serve
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

UWSGI_UNIT = """[Unit]
Description=uWSGI Emperor for Hop3
After=network.target

[Service]
Type=notify
User=hop3
Group=hop3
ExecStart=/home/hop3/venv/bin/uwsgi --emperor /home/hop3/uwsgi-enabled --stats /tmp/hop3-uwsgi-stats.sock
Restart=always
KillSignal=SIGQUIT
NotifyAccess=all

[Install]
WantedBy=multi-user.target
"""

# Nginx configuration template
NGINX_CONFIG = """# Hop3 Server - Reverse Proxy Configuration
# Auto-generated by hop3 installer

# Redirect HTTP to HTTPS
server {{
    listen 80;
    server_name {server_name};

    location /.well-known/acme-challenge/ {{
        root /var/www/html;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# HTTPS server
server {{
    listen 443 ssl http2;
    server_name {server_name};

    ssl_certificate {ssl_cert};
    ssl_certificate_key {ssl_key};

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Proxy all requests to hop3-server
    location / {{
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {{
        root /var/www/html;
    }}
}}
"""

# Sudoers configuration (nginx reload only, no supervisor wildcards)
SUDOERS_CONTENT = """# Hop3 service management permissions
# Allow hop3 user to reload/restart nginx for deployments
hop3 ALL=(ALL) NOPASSWD: /usr/bin/systemctl reload nginx
hop3 ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart nginx
hop3 ALL=(ALL) NOPASSWD: /usr/sbin/nginx -s reload
hop3 ALL=(ALL) NOPASSWD: /usr/sbin/nginx -t
"""


@dataclass
class ServerInstallerConfig:
    """Configuration for server installer."""

    # Installation source
    version: str | None = None
    use_git: bool = False
    branch: str = DEFAULT_BRANCH
    local_path: str | None = None

    # Installation options
    force: bool = False
    skip_deps: bool = False
    skip_nginx: bool = False
    skip_postgres: bool = False
    skip_acme: bool = False
    domain: str | None = None
    verbose: bool = False

    # Optional features
    features: set[str] = field(default_factory=set)

    @property
    def with_mysql(self) -> bool:
        return "mysql" in self.features

    @property
    def with_redis(self) -> bool:
        return "redis" in self.features

    @property
    def with_docker(self) -> bool:
        return "docker" in self.features

    @classmethod
    def from_env(cls) -> ServerInstallerConfig:
        """Create config from environment variables."""
        features = parse_features(env_str("HOP3_WITH", ""))

        return cls(
            version=env_str("HOP3_VERSION"),
            use_git=env_bool("HOP3_GIT"),
            branch=env_str("HOP3_BRANCH", DEFAULT_BRANCH),
            local_path=env_str("HOP3_LOCAL_PACKAGE"),
            force=env_bool("HOP3_FORCE"),
            skip_deps=env_bool("HOP3_SKIP_DEPS"),
            skip_nginx=env_bool("HOP3_SKIP_NGINX"),
            skip_postgres=env_bool("HOP3_SKIP_POSTGRES"),
            skip_acme=env_bool("HOP3_SKIP_ACME"),
            domain=env_str("HOP3_DOMAIN"),
            verbose=env_bool("HOP3_VERBOSE"),
            features=features,
        )


def parse_features(features_str: str) -> set[str]:
    """Parse comma-separated feature list.

    Args:
        features_str: Comma-separated features (e.g., "mysql,redis" or "all")

    Returns:
        Set of feature names to install
    """
    if not features_str:
        return set()

    features_str = features_str.lower().strip()

    # Handle "all" keyword
    if features_str == "all":
        return ALL_FEATURES.copy()

    # Parse comma-separated list
    features = set()
    for feature in features_str.split(","):
        feature = feature.strip()
        if feature == "all":
            features.update(ALL_FEATURES)
        elif feature in ALL_FEATURES:
            features.add(feature)
        elif feature == "postgres":
            # PostgreSQL is always installed by default, ignore
            pass
        elif feature:
            # Unknown feature - will be warned about in main
            pass

    return features
