# Copyright (c) 2025-2026, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""Installation verification and final messages."""

from __future__ import annotations

import grp
import os
import pwd
from pathlib import Path

from hop3_installer.common import (
    Colors,
    has_systemd,
    print_detail,
    print_error,
    print_info,
    print_success,
    print_warning,
    process_manager_pending,
    run_cmd,
)
from hop3_installer.constants import (
    DEFAULT_ADMIN_EMAIL,
    HOME_DIR,
    HOP3_GROUP,
    HOP3_USER,
    SYSTEM_SSL_CERT,
    SYSTEM_SSL_KEY,
    VENV_DIR,
)

from .config import ServerInstallerConfig

# Keys this installer owns. Everything else in an existing hop3-server.toml is
# an operator addition (e.g. ACME_ENGINE / ACME_EMAIL, custom POSTGRES_PORT) and
# MUST survive a redeploy — see write_server_config.
_MANAGED_CONFIG_KEYS = (
    "HOP3_SECRET_KEY",
    "ADMIN_DOMAIN",
    "OPERATOR_EMAIL",
    "POSTGRES_HOST",
    "POSTGRES_SUPERUSER_PASSWORD",
    "MYSQL_HOST",
    "MYSQL_SUPERUSER",
    "MYSQL_SUPERUSER_PASSWORD",
)


def read_existing_server_config_value(key: str) -> str | None:
    """
    Return a top-level ``KEY = "value"`` from the existing hop3-server.toml.

    Lets a redeploy REUSE a secret the installer wrote on a prior run instead of
    rotating it: a rotated DB superuser password desyncs the role from the
    stored credential and breaks every client. Flat line parse (the file is flat
    key=value) — no TOML dependency, matching ``verify_mysql_config`` below.
    """
    config_file = HOME_DIR / "hop3-server.toml"
    try:
        content = config_file.read_text()
    except OSError:
        return None
    for line in content.splitlines():
        key_part, sep, value_part = line.partition("=")
        if sep and key_part.strip() == key:
            return value_part.strip().strip('"').strip("'") or None
    return None


def _preserved_operator_lines() -> list[str]:
    """
    Existing non-managed ``KEY = value`` lines (e.g. ACME_*) to carry over.

    Read BEFORE the file is rewritten so operator settings are not lost on
    redeploy. Comments are dropped (values are what matter); blank lines and
    managed keys are skipped.
    """
    config_file = HOME_DIR / "hop3-server.toml"
    try:
        content = config_file.read_text()
    except OSError:
        return []
    preserved: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key = stripped.partition("=")[0].strip()
        if key and key not in _MANAGED_CONFIG_KEYS:
            preserved.append(stripped)
    return preserved


def write_server_config(
    pg_password: str | None,
    mysql_password: str | None,
    domain: str | None,
    secret_key: str | None = None,
    operator_email: str | None = None,
) -> None:
    """
    Write hop3-server.toml configuration file.

    Idempotent on redeploy: operator-added keys (ACME_*, custom settings) are
    preserved, and the secrets passed in are the *reused* ones (see
    ``read_existing_server_config_value``), never freshly rotated values.

    A managed value not (re)generated this run is REUSED from the existing file
    rather than dropped: a plain redeploy — or one that omits ``--with mysql`` /
    ``--with postgres`` — must not wipe a working DB password (the service and
    role still exist on the box), the signing key, or the admin domain. Without
    this, the file is rebuilt from a template each run and any managed key whose
    value arrives as ``None`` silently vanishes.
    """
    # Reuse managed values not supplied this run (never rotate, never drop).
    secret_key = secret_key or read_existing_server_config_value("HOP3_SECRET_KEY")
    domain = domain or read_existing_server_config_value("ADMIN_DOMAIN")
    # OPERATOR_EMAIL is what `[admin].email = "operator"` recipes resolve to
    # (ADR 056). Without it every admin-bootstrap app fails to deploy, so a
    # fresh install must always have one; a placeholder is fine (the operator
    # overrides it), unlike ACME where Let's Encrypt rejects example.com.
    operator_email = (
        operator_email
        or read_existing_server_config_value("OPERATOR_EMAIL")
        or DEFAULT_ADMIN_EMAIL
    )
    pg_password = pg_password or read_existing_server_config_value(
        "POSTGRES_SUPERUSER_PASSWORD"
    )
    mysql_password = mysql_password or read_existing_server_config_value(
        "MYSQL_SUPERUSER_PASSWORD"
    )

    config_file = HOME_DIR / "hop3-server.toml"

    # Capture operator additions before we overwrite the file.
    preserved = _preserved_operator_lines()

    lines = [
        "# Hop3 Server Configuration",
        "# Auto-generated by installer",
        "",
    ]

    # Add secret key for JWT token signing
    if secret_key:
        lines.extend([
            "# Secret key for JWT token signing (required for authentication)",
            f'HOP3_SECRET_KEY = "{secret_key}"',
            "",
        ])

    if domain:
        lines.extend([
            "# Admin UI domain",
            f'ADMIN_DOMAIN = "{domain}"',
            "",
        ])

    lines.extend([
        '# Operator contact; resolves `[admin].email = "operator"` (ADR 056).',
        f'OPERATOR_EMAIL = "{operator_email}"',
        "",
    ])

    if pg_password:
        lines.extend([
            "# PostgreSQL admin connection settings",
            'POSTGRES_HOST = "127.0.0.1"',
            f'POSTGRES_SUPERUSER_PASSWORD = "{pg_password}"',
            "",
        ])

    if mysql_password:
        lines.extend([
            "# MySQL admin connection settings",
            'MYSQL_HOST = "127.0.0.1"',
            'MYSQL_SUPERUSER = "hop3"',
            f'MYSQL_SUPERUSER_PASSWORD = "{mysql_password}"',
            "",
        ])

    # Carry over anything the operator added (e.g. ACME_ENGINE / ACME_EMAIL) so a
    # redeploy never silently drops it.
    if preserved:
        lines.extend([
            "# Operator settings (preserved across redeploy)",
            *preserved,
            "",
        ])

    config_file.write_text("\n".join(lines))

    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(config_file, hop3_uid, hop3_gid)
    Path(config_file).chmod(0o600)

    print_success(f"Server configuration written to {config_file}")


def verify_mysql_config() -> bool:
    """
    Verify MySQL configuration is correctly set up.

    Checks that hop3 user can connect to MySQL and that
    the config file has the proper settings.

    Returns:
        True if MySQL is properly configured, False otherwise.
    """
    config_file = HOME_DIR / "hop3-server.toml"

    # Check that config file has MySQL password
    if not config_file.exists():
        print_warning("Config file not found")
        return False

    config_content = config_file.read_text()
    if "MYSQL_SUPERUSER_PASSWORD" not in config_content:
        print_warning("MySQL password not in config file")
        return False

    # Test MySQL connection as hop3 user using the config
    # Extract password from config
    mysql_password = None
    for line in config_content.split("\n"):
        if "MYSQL_SUPERUSER_PASSWORD" in line and "=" in line:
            # Parse: MYSQL_SUPERUSER_PASSWORD = "value"
            value = line.split("=", 1)[1].strip().strip('"')
            mysql_password = value
            break

    if not mysql_password:
        print_warning("Could not extract MySQL password from config")
        return False

    # Test connection with the hop3 MySQL user.
    # SECURITY: pass the password via MYSQL_PWD instead of -p{password}.
    # See notes/security.md §3.4.1.
    result = run_cmd(
        ["mysql", "-u", "hop3", "-e", "SELECT 1;"],
        check=False,
        capture=True,
        env={"MYSQL_PWD": mysql_password},
    )

    if result.returncode != 0:
        print_warning("MySQL connection test failed")
        if result.stderr:
            print_detail(result.stderr.strip()[:200])
        return False

    return True


def _verify_services() -> None:
    """Verify core services are running."""
    if process_manager_pending():
        print_info(
            "No process manager yet; the deployer starts and verifies "
            "hop3-server, nginx and uwsgi after this installer returns"
        )
        return

    if has_systemd():
        for service, name in [
            ("hop3-server", "hop3-server service"),
            ("hop3-rootd", "hop3-rootd service"),
            ("nginx", "nginx service"),
            ("uwsgi-hop3", "uwsgi-hop3 service"),
        ]:
            result = run_cmd(
                ["systemctl", "is-active", service], capture=True, check=False
            )
            if result.stdout.strip() == "active":
                print_success(f"{name} is running")
            else:
                print_warning(f"{name} is not running")
                print_detail(f"Check with: sudo systemctl status {service}")
    else:
        # Non-systemd: check supervisord-managed services
        for service, name in [
            ("hop3-server", "hop3-server"),
            ("nginx", "nginx"),
            ("uwsgi", "uwsgi"),
        ]:
            result = run_cmd(
                ["supervisorctl", "status", service], capture=True, check=False
            )
            if "RUNNING" in (result.stdout or ""):
                print_success(f"{name} is running")
            else:
                print_warning(f"{name} is not running")
                print_detail(f"Check with: supervisorctl status {service}")


def _is_postgres_running() -> bool:
    """
    Check if PostgreSQL is running, regardless of init system.

    Tries systemd first, then pg_isready (works for any init).
    """
    if has_systemd():
        result = run_cmd(
            ["systemctl", "is-active", "postgresql"], capture=True, check=False
        )
        return result.stdout.strip() == "active"

    # Non-systemd: use pg_isready which works regardless of how pg was started
    result = run_cmd(["pg_isready", "-q"], check=False)
    return result.returncode == 0


def _is_mysql_running() -> bool:
    """
    Check if MySQL is running, regardless of init system.

    The twin of `_is_postgres_running`, which this did not have: it asked
    `systemctl is-active` for mysql and then mariadb, and on a container both
    fail whatever the server is doing. So a run that had just reported "MySQL
    service started" and "MySQL connection verified successfully" three lines
    earlier ended with "MySQL service is not running" — and that warning set the
    exit code, failing the whole install.

    Without systemd there is no init system to ask, so this defers to the
    caller's `verify_mysql_config()` — which opens a real connection, and so
    answers "is MySQL running" more strictly than any liveness probe could.
    `mysqladmin ping` was the obvious candidate and is the wrong one twice over:
    it ships in `mysql-client` rather than the server package, and a probe that
    passes where the connection fails would only move the error later.
    """
    if not has_systemd():
        return True

    return any(
        run_cmd(
            ["systemctl", "is-active", service], capture=True, check=False
        ).stdout.strip()
        == "active"
        for service in ("mysql", "mariadb")
    )


def _verify_database_services(config_content: str) -> bool:
    """
    Verify database services are running and configured.

    Returns:
        True if all database services are OK, False otherwise.
    """
    all_ok = True

    if "POSTGRES_SUPERUSER_PASSWORD" in config_content:
        if _is_postgres_running():
            print_success("PostgreSQL service is running")
        else:
            print_warning("PostgreSQL service is not running")
            all_ok = False

    if "MYSQL_SUPERUSER_PASSWORD" in config_content:
        if _is_mysql_running():
            if verify_mysql_config():
                print_success("MySQL configuration verified")
            else:
                print_error("MySQL configuration test FAILED")
                all_ok = False
        else:
            print_warning("MySQL service is not running")
            all_ok = False

    return all_ok


def verify_installation(config: ServerInstallerConfig) -> bool:
    """Verify the installation."""
    hop_server = VENV_DIR / "bin" / "hop3-server"

    if not hop_server.exists():
        print_error("hop3-server not found")
        return False

    _verify_services()

    # Check SSL
    if SYSTEM_SSL_CERT.exists() and SYSTEM_SSL_KEY.exists():
        print_success("SSL certificate is configured")
    else:
        print_warning("SSL certificate not found")

    # Check databases if configured
    config_file = HOME_DIR / "hop3-server.toml"
    if config_file.exists():
        config_content = config_file.read_text()
        if not _verify_database_services(config_content):
            return False

    return True


def print_final_message(config: ServerInstallerConfig) -> None:
    """Print success message with next steps."""
    print()
    print(f"{Colors.GREEN}{Colors.BOLD}Installation complete!{Colors.RESET}")
    print()
    print(f"  {Colors.BOLD}User:{Colors.RESET}      {HOP3_USER}")
    print(f"  {Colors.BOLD}Home:{Colors.RESET}      {HOME_DIR}")
    print(f"  {Colors.BOLD}Venv:{Colors.RESET}      {VENV_DIR}")
    print()
    print(f"  {Colors.BOLD}Services:{Colors.RESET}")
    print("    sudo systemctl status hop3-server")
    print("    sudo systemctl status hop3-rootd")
    print("    sudo systemctl status uwsgi-hop3")
    print("    sudo systemctl status nginx")
    print()
    print(f"  {Colors.BOLD}Logs:{Colors.RESET}")
    print("    sudo journalctl -u hop3-server -f")
    print()
    print(f"  {Colors.BOLD}Next steps:{Colors.RESET}")
    print("    1. Add your SSH key:  ssh-copy-id hop3@your-server")
    print("    2. Deploy an app:     hop3 deploy --app your-app")
    print()
