# Copyright (c) 2025-2026, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""Installation verification and final messages."""

from __future__ import annotations

import grp
import os
import pwd
from pathlib import Path

from hop3_installer.common import (
    Colors,
    print_detail,
    print_error,
    print_success,
    print_warning,
    run_cmd,
)

from .config import (
    HOME_DIR,
    HOP3_GROUP,
    HOP3_USER,
    SSL_CERT,
    SSL_KEY,
    VENV_DIR,
    ServerInstallerConfig,
)


def write_server_config(
    pg_password: str | None,
    mysql_password: str | None,
    domain: str | None,
    secret_key: str | None = None,
) -> None:
    """Write hop3-server.toml configuration file."""
    config_file = HOME_DIR / "hop3-server.toml"

    lines = [
        "# Hop3 Server Configuration",
        "# Auto-generated by installer",
        "",
    ]

    # Add secret key for JWT token signing
    if secret_key:
        lines.extend([
            "# Secret key for JWT token signing (required for authentication)",
            f'HOP3_SECRET_KEY = "{secret_key}"',
            "",
        ])

    if domain:
        lines.extend([
            "# Admin UI domain",
            f'ADMIN_DOMAIN = "{domain}"',
            "",
        ])

    if pg_password:
        lines.extend([
            "# PostgreSQL admin connection settings",
            'POSTGRES_HOST = "127.0.0.1"',
            f'POSTGRES_SUPERUSER_PASSWORD = "{pg_password}"',
            "",
        ])

    if mysql_password:
        lines.extend([
            "# MySQL admin connection settings",
            'MYSQL_HOST = "127.0.0.1"',
            'MYSQL_SUPERUSER = "hop3"',
            f'MYSQL_SUPERUSER_PASSWORD = "{mysql_password}"',
            "",
        ])

    config_file.write_text("\n".join(lines))

    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(config_file, hop3_uid, hop3_gid)
    Path(config_file).chmod(0o600)

    print_success(f"Server configuration written to {config_file}")


def verify_mysql_config() -> bool:
    """Verify MySQL configuration is correctly set up.

    Checks that hop3 user can connect to MySQL and that
    the config file has the proper settings.

    Returns:
        True if MySQL is properly configured, False otherwise.
    """
    config_file = HOME_DIR / "hop3-server.toml"

    # Check that config file has MySQL password
    if not config_file.exists():
        print_warning("Config file not found")
        return False

    config_content = config_file.read_text()
    if "MYSQL_SUPERUSER_PASSWORD" not in config_content:
        print_warning("MySQL password not in config file")
        return False

    # Test MySQL connection as hop3 user using the config
    # Extract password from config
    mysql_password = None
    for line in config_content.split("\n"):
        if "MYSQL_SUPERUSER_PASSWORD" in line and "=" in line:
            # Parse: MYSQL_SUPERUSER_PASSWORD = "value"
            value = line.split("=", 1)[1].strip().strip('"')
            mysql_password = value
            break

    if not mysql_password:
        print_warning("Could not extract MySQL password from config")
        return False

    # Test connection with the hop3 MySQL user
    result = run_cmd(
        ["mysql", "-u", "hop3", f"-p{mysql_password}", "-e", "SELECT 1;"],
        check=False,
        capture=True,
    )

    if result.returncode != 0:
        print_warning("MySQL connection test failed")
        if result.stderr:
            print_detail(result.stderr.strip()[:200])
        return False

    return True


def _verify_services() -> None:
    """Verify core services are running."""
    for service, name in [
        ("hop3-server", "hop3-server service"),
        ("nginx", "nginx service"),
        ("uwsgi-hop3", "uwsgi-hop3 service"),
    ]:
        result = run_cmd(["systemctl", "is-active", service], capture=True, check=False)
        if result.stdout.strip() == "active":
            print_success(f"{name} is running")
        else:
            print_warning(f"{name} is not running")
            print_detail(f"Check with: sudo systemctl status {service}")


def _verify_database_services(config_content: str) -> bool:
    """Verify database services are running and configured.

    Returns:
        True if all database services are OK, False otherwise.
    """
    all_ok = True

    if "POSTGRES_SUPERUSER_PASSWORD" in config_content:
        result = run_cmd(
            ["systemctl", "is-active", "postgresql"],
            capture=True,
            check=False,
        )
        if result.stdout.strip() == "active":
            print_success("PostgreSQL service is running")
        else:
            print_warning("PostgreSQL service is not running")
            all_ok = False

    if "MYSQL_SUPERUSER_PASSWORD" in config_content:
        result = run_cmd(
            ["systemctl", "is-active", "mysql"],
            capture=True,
            check=False,
        )
        if result.returncode != 0:
            result = run_cmd(
                ["systemctl", "is-active", "mariadb"],
                capture=True,
                check=False,
            )
        if result.stdout.strip() == "active":
            if verify_mysql_config():
                print_success("MySQL configuration verified")
            else:
                print_error("MySQL configuration test FAILED")
                all_ok = False
        else:
            print_warning("MySQL service is not running")
            all_ok = False

    return all_ok


def verify_installation(config: ServerInstallerConfig) -> bool:
    """Verify the installation."""
    hop_server = VENV_DIR / "bin" / "hop3-server"

    if not hop_server.exists():
        print_error("hop3-server not found")
        return False

    _verify_services()

    # Check SSL
    if SSL_CERT.exists() and SSL_KEY.exists():
        print_success("SSL certificate is configured")
    else:
        print_warning("SSL certificate not found")

    # Check databases if configured
    config_file = HOME_DIR / "hop3-server.toml"
    if config_file.exists():
        config_content = config_file.read_text()
        if not _verify_database_services(config_content):
            return False

    return True


def print_final_message(config: ServerInstallerConfig) -> None:
    """Print success message with next steps."""
    print()
    print(f"{Colors.GREEN}{Colors.BOLD}Installation complete!{Colors.RESET}")
    print()
    print(f"  {Colors.BOLD}User:{Colors.RESET}      {HOP3_USER}")
    print(f"  {Colors.BOLD}Home:{Colors.RESET}      {HOME_DIR}")
    print(f"  {Colors.BOLD}Venv:{Colors.RESET}      {VENV_DIR}")
    print()
    print(f"  {Colors.BOLD}Services:{Colors.RESET}")
    print("    sudo systemctl status hop3-server")
    print("    sudo systemctl status uwsgi-hop3")
    print("    sudo systemctl status nginx")
    print()
    print(f"  {Colors.BOLD}Logs:{Colors.RESET}")
    print("    sudo journalctl -u hop3-server -f")
    print()
    print(f"  {Colors.BOLD}Next steps:{Colors.RESET}")
    print("    1. Add your SSH key:  ssh-copy-id hop3@your-server")
    print("    2. Deploy an app:     hop3 deploy your-app.git")
    print()
