preview = true
target-version = "py310"

exclude = [
    "apps",
    "scripts",
    "tasks.py",
    "docs",
    "demos",
]

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Never
    "PD", # We're not using Pandas

    # Later (or never)
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "BLE", # flake8-blind-except
    "CPY", # Copyright
    "D", # pydocstyle
    "DOC", # pydocstyle
    "ERA", # eradicate
    "FIX", # flake8-fixme
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "T20", # flake8-print
    "TD", # flake8-todos
    "FBT",
    "COM812", # 	[*] missing-trailing-comma
    "E501", #   	[ ] line-too-long
    "PLR2004", #	[ ] magic-value-comparison
    "TRY300", # 	[ ] try-consider-else
    "PLR6301", #	[ ] no-self-use
    "PLW2901", #	[ ] redefined-loop-name
    "DTZ005", # 	[ ] call-datetime-now-without-tzinfo
    "SLF001", # 	[ ] private-member-access
    "F841", #   	[ ] unused-variable
    "PERF203", #	[ ] try-except-in-loop
    "PLW1514", #	[ ] unspecified-encoding
    # "RUF059", # 	[ ] unused-unpacked-variable
    "SIM102", # 	[ ] collapsible-if
    # Fix
    "RUF012", # 	[ ] mutable-class-default
    "C901", #   	[ ] complex-structure
    "PLR0912", #	[ ] too-many-branches
    "PLR0916", #	[ ] too-many-boolean-expressions
]

[lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
known-first-party = ["hop3"]
