# Umami - Own Your Website Analytics

[metadata]
id = "umami"
version = "3.22.1"
upstream_version = "3.0.1"
title = "Umami"
author = "Umami Community"
description = "Umami is a simple, fast, privacy-focused alternative to Google Analytics."
website = "https://umami.is/"
license = "MIT"
tags = ["analytics", "tracker"]

[source]
type = "git"
url = "https://github.com/umami-software/umami.git"
tag = "v${upstream_version}"

[source.nodejs]
version = "20"

[build]
packages = ["nodejs"]
before-build = [
    "yarn install",
    "yarn build"
]

[run]
start = "/app/scripts/start.sh"
packages = ["nodejs"]

[port]
web = 3000

[healthcheck]
path = "/"
timeout = 30

[resources]
memory = "2048M"

[env]
NODE_ENV = "production"
FORCE_SSL = "1"
DISABLE_UPDATES = "1"
DATABASE_TYPE = "postgresql"

[[provider]]
name = "postgres"

[storage]
local = true
