#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024-2026 Abilian SAS <https://abilian.com>
# SPDX-License-Identifier: Apache-2.0
"""Publish Architecture Decision Records (ADRs) into the documentation site.

Source of truth lives in ``notes/adrs/`` (repo root). This script copies each
ADR into ``docs/src/developers/adrs/`` and, along the way, leverages the ADR
metadata to make the collection navigable:

1. **Per-ADR pages.** Each ADR keeps its authored body (and its hand-written
   preamble, with all its nuance). Links are rewritten so they keep working
   once published:
     * inter-ADR links resolve as sibling pages (filenames are preserved);
     * links to other, *unpublished* repo notes (e.g. ``../cli/foo.md``) become
       GitHub source URLs instead of dangling relative links.
   A generated **Relationships** footer is appended with linked
   *Supersedes* / *Superseded by* / *Related ADRs* entries — the
   *Superseded by* backlinks are computed by inverting every *Supersedes*.

2. **Index page** (``index.md``). The intro and the process/template reference
   material from ``000-readme.md`` are kept; the hand-maintained (and stale)
   index/by-type/by-status tables are replaced with tables generated from the
   live metadata, including an "ADRs by status" grouping.

3. **Navigation.** The ``Architecture Decision Records`` section of the
   Developers tab in ``zensical.toml`` is regenerated, grouping the ADRs by
   status. The block is delimited by sentinel comments so re-runs are
   idempotent.

The metadata is the bold-line preamble convention used by the ADRs, e.g.::

    # ADR 043: Unified Testing Architecture

    **Status**: Draft
    **Type**: Process
    **Supersedes**: ADR 026 (Dashboard UI Test Classification)
    **Related-ADRs**: 004 (development-tooling), 027 (...), 030 (...)
"""

from __future__ import annotations

import html
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

DOCS_DIR = Path(__file__).parent.parent
REPO_ROOT = DOCS_DIR.parent
SRC_DIR = REPO_ROOT / "notes" / "adrs"
DEST_DIR = DOCS_DIR / "src" / "developers" / "adrs"
ZENSICAL_FILE = DOCS_DIR / "zensical.toml"

GH_BLOB = "https://github.com/abilian/hop3/blob/main"
GENERATED_COMMENT = (
    "<!-- Generated file - DO NOT EDIT. Source: /notes/adrs/ -->\n\n"
)

# Display order of status groups (settled decisions first, drafts/inactive last).
# Any status not listed is appended, in first-seen order, after these.
STATUS_ORDER = [
    "Accepted",
    "Final",
    "Active",
    "Implemented",
    "Draft",
    "Deferred",
    "Superseded",
]

# Display order for the Type filter chips (most common first); the rest are
# appended alphabetically.
TYPE_ORDER = ["Feature", "Architecture", "Process", "Guideline", "Design"]

# Sentinels delimiting the generated nav block in zensical.toml.
NAV_START = "        # >>> ADRs (generated by convert_adrs.py) >>>"
NAV_END = "        # <<< ADRs (generated) <<<"
# The generated block is inserted just before this Developers-tab subsection.
NAV_ANCHOR = '        { "Testing" = ['

LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
# Preamble metadata lines. Accepts both the bare ``**Status**: X`` and the
# bulleted ``- **Status**: X`` form (the ADRs were normalised to a bullet list,
# which the bare-only pattern silently stopped matching — every ADR then read
# as status "Unknown" and the status-grouped nav collapsed).
META_LINE_RE = re.compile(
    r"^[ \t]*(?:[-*][ \t]+)?\*\*([^*]+)\*\*\s*:\s*(.+)$", re.MULTILINE
)


@dataclass
class Adr:
    """One ADR, parsed from its file."""

    num: int
    filename: str
    title: str
    status: str = ""  # canonical (first word)
    status_raw: str = ""
    type: str = ""
    created: str = ""
    updated: str = ""
    supersedes: list[int] = field(default_factory=list)
    related: list[int] = field(default_factory=list)
    superseded_by: list[int] = field(default_factory=list)

    @property
    def title_short(self) -> str:
        """Title without the leading ``ADR NNN:`` prefix."""
        return re.sub(r"^ADR\s+\d+\s*:\s*", "", self.title).strip()


def _header(body: str) -> str:
    """The region before the first ``## `` heading (where the preamble lives)."""
    m = re.search(r"^##\s", body, re.MULTILINE)
    return body[: m.start()] if m else body


def _nums(value: str, valid: set[int]) -> list[int]:
    """Extract ADR numbers referenced in a metadata value, in order, de-duped."""
    out: list[int] = []
    for tok in re.findall(r"\d{2,3}", value):
        n = int(tok)
        if n in valid and n not in out:
            out.append(n)
    return out


def parse_adr(path: Path) -> Adr | None:
    """Parse one ADR file into an :class:`Adr` (skips the readme/index)."""
    if path.name == "000-readme.md":
        return None
    m = re.match(r"(\d{3})-", path.name)
    if not m:
        return None
    body = path.read_text(encoding="utf-8")

    h1 = re.search(r"^#\s+(.+)$", body, re.MULTILINE)
    title = h1.group(1).strip() if h1 else path.stem

    meta: dict[str, str] = {}
    for mm in META_LINE_RE.finditer(_header(body)):
        key = re.sub(r"[\s_-]+", " ", mm.group(1).strip().lower())
        meta[key] = mm.group(2).strip()

    status_raw = meta.get("status", "")
    status = re.sub(r"[*_`]", "", status_raw).strip()
    status = status.split()[0].rstrip(":—-").strip() if status else "Unknown"

    return Adr(
        num=int(m.group(1)),
        filename=path.name,
        title=title,
        status=status,
        status_raw=status_raw,
        type=(meta.get("type", "").split()[0] if meta.get("type") else ""),
        created=meta.get("created", ""),
        updated=meta.get("updated", ""),
    )


def load_adrs() -> list[Adr]:
    """Load and cross-link every ADR (computing Superseded-by backlinks)."""
    adrs = [a for p in sorted(SRC_DIR.glob("*.md")) if (a := parse_adr(p))]
    by_num = {a.num: a for a in adrs}
    valid = set(by_num)

    # Second pass for relationships (needs the full set / valid numbers).
    for a in adrs:
        body = (SRC_DIR / a.filename).read_text(encoding="utf-8")
        meta: dict[str, str] = {}
        for mm in META_LINE_RE.finditer(_header(body)):
            key = re.sub(r"[\s_-]+", " ", mm.group(1).strip().lower())
            meta[key] = mm.group(2).strip()
        a.supersedes = _nums(meta.get("supersedes", ""), valid)
        related = meta.get("related adrs") or meta.get("related") or ""
        a.related = [n for n in _nums(related, valid) if n != a.num]
        for n in _nums(meta.get("superseded by", ""), valid):
            if n not in a.superseded_by:
                a.superseded_by.append(n)

    # Invert Supersedes -> Superseded-by backlinks.
    for a in adrs:
        for target in a.supersedes:
            t = by_num.get(target)
            if t and a.num not in t.superseded_by:
                t.superseded_by.append(a.num)
    return adrs


# --------------------------------------------------------------------------- #
# Link rewriting
# --------------------------------------------------------------------------- #
def rewrite_links(body: str, adr_files: set[str]) -> str:
    """Rewrite links so a published ADR page keeps working.

    Inter-ADR and external/anchor links are left untouched (siblings resolve);
    links to other repo notes become GitHub source URLs.
    """

    def repl(m: re.Match) -> str:
        text, target = m.group(1), m.group(2).strip()
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return m.group(0)
        base, _, anchor = target.partition("#")
        anchor = f"#{anchor}" if anchor else ""
        name = base.lstrip("./")
        if name in adr_files:  # inter-ADR sibling link
            return m.group(0)
        if name == "000-readme.md":
            return f"[{text}](index.md{anchor})"
        if base.endswith(".md"):  # link to an unpublished repo note
            repo_path = (SRC_DIR / base).resolve().relative_to(REPO_ROOT)
            return f"[{text}]({GH_BLOB}/{repo_path.as_posix()}{anchor})"
        return m.group(0)

    return LINK_RE.sub(repl, body)


def relationships_footer(adr: Adr, by_num: dict[int, Adr]) -> str:
    """Generated cross-link footer (Supersedes / Superseded by / Related)."""

    def links(nums: list[int]) -> str:
        return ", ".join(
            f"[{by_num[n].title}]({by_num[n].filename})"
            for n in nums
            if n in by_num
        )

    # Don't repeat a formal Supersedes/Superseded-by relation under "Related".
    formal = set(adr.supersedes) | set(adr.superseded_by)
    related = [n for n in adr.related if n not in formal]

    rows = []
    if adr.supersedes:
        rows.append(f"**Supersedes:** {links(adr.supersedes)}")
    if adr.superseded_by:
        rows.append(f"**Superseded by:** {links(sorted(adr.superseded_by))}")
    if related:
        rows.append(f"**Related ADRs:** {links(related)}")
    if not rows:
        return ""
    return "\n\n---\n\n" + "  \n".join(rows) + "\n"


def write_adr_page(adr: Adr, by_num: dict[int, Adr], adr_files: set[str]) -> None:
    body = (SRC_DIR / adr.filename).read_text(encoding="utf-8")
    body = rewrite_links(body, adr_files)
    body = body.rstrip() + relationships_footer(adr, by_num)
    # The ADRs are no longer in the nav, so the theme breadcrumb
    # (navigation.path) can't build a trail to them. Give each page a manual
    # one back to the Developers tab and the ADR index. Markdown links (not raw
    # HTML) so the build rewrites them to correct clean URLs; the md_in_html
    # wrapper carries the styling class.
    crumb = (
        '<nav class="adr-breadcrumb" markdown="span">'
        f"[Developers](../index.md) › [ADRs](index.md) › ADR {adr.num:03d}"
        "</nav>"
    )
    (DEST_DIR / adr.filename).write_text(
        f"{GENERATED_COMMENT}{crumb}\n\n{body}\n"
    )


# --------------------------------------------------------------------------- #
# Index page
# --------------------------------------------------------------------------- #
def grouped_by_status(adrs: list[Adr]) -> list[tuple[str, list[Adr]]]:
    """Return ``[(status, adrs)]`` in display order, ADRs sorted by number."""
    seen = {a.status for a in adrs}
    order = STATUS_ORDER + sorted(seen - set(STATUS_ORDER))
    groups = []
    for status in order:
        members = sorted(
            (a for a in adrs if a.status == status), key=lambda a: a.num
        )
        if members:
            groups.append((status, members))
    return groups


def _slug(value: str) -> str:
    """A CSS-class-safe slug for a type/status value."""
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "none"


def _badge(value: str, kind: str) -> str:
    """A colored pill for a type/status value (``kind`` is ``type``/``status``)."""
    if not value:
        return '<span class="adr-badge adr-none">—</span>'
    return f'<span class="adr-badge adr-{kind}-{_slug(value)}">{html.escape(value)}</span>'


def _ordered_distinct(values: set[str], order: list[str]) -> list[str]:
    """Distinct ``values`` with ``order`` first, then the rest alphabetically."""
    return [v for v in order if v in values] + sorted(values - set(order))


def _facet_chips(facet: str, label: str, values: list[str]) -> str:
    """A labelled row of filter chips (an ``All`` chip plus one per value)."""
    chips = [
        (
            '<button type="button" class="adr-chip is-active" '
            f'data-facet="{facet}" data-value="">All</button>'
        )
    ]
    for v in values:
        chips.append(
            f'<button type="button" class="adr-chip" data-facet="{facet}" '
            f'data-value="{html.escape(v, quote=True)}">{html.escape(v)}</button>'
        )
    return (
        f'<div class="adr-facet"><span class="adr-facet-label">{label}</span>'
        + "".join(chips)
        + "</div>"
    )


def generate_index(adrs: list[Adr]) -> str:
    """Build index.md: kept readme prose + a sortable/filterable ADR table.

    The table is emitted as raw HTML — rows carry ``data-*`` for the filter/sort
    JS (``docs/src/javascripts/adr-index.js``), and type/status render as colored
    badges. The individual ADRs are no longer expanded in the nav, so this page
    is how the collection is browsed.
    """
    readme = (SRC_DIR / "000-readme.md").read_text(encoding="utf-8")
    intro = readme.split("## ADR Index", 1)[0].rstrip()
    tail = ""
    if "## ADR Types" in readme:
        tail = "## ADR Types" + readme.split("## ADR Types", 1)[1].rstrip()

    types = _ordered_distinct({a.type for a in adrs if a.type}, TYPE_ORDER)
    statuses = _ordered_distinct({a.status for a in adrs if a.status}, STATUS_ORDER)

    rows = []
    for a in sorted(adrs, key=lambda a: a.num):
        href = a.filename.removesuffix(".md") + "/"  # zensical clean URLs
        title = html.escape(a.title_short)
        blob = html.escape(
            f"{a.num:03d} {a.title_short} {a.type} {a.status}".lower(), quote=True
        )
        rows.append(
            f'      <tr data-num="{a.num}"'
            f' data-type="{html.escape(a.type, quote=True)}"'
            f' data-status="{html.escape(a.status, quote=True)}"'
            f' data-title="{html.escape(a.title_short.lower(), quote=True)}"'
            f' data-search="{blob}">'
            f'<td class="adr-num"><a href="{href}">{a.num:03d}</a></td>'
            f'<td class="adr-title"><a href="{href}">{title}</a></td>'
            f'<td>{_badge(a.type, "type")}</td>'
            f'<td>{_badge(a.status, "status")}</td></tr>'
        )

    table = (
        '<div class="adr-index">\n'
        '  <div class="adr-controls">\n'
        '    <input type="search" class="adr-search" placeholder="Search ADRs…"'
        ' aria-label="Search ADRs">\n'
        f"    {_facet_chips('type', 'Type', types)}\n"
        f"    {_facet_chips('status', 'Status', statuses)}\n"
        "  </div>\n"
        '  <p class="adr-count" aria-live="polite"></p>\n'
        '  <table class="adr-table">\n'
        "    <thead>\n"
        '      <tr><th class="adr-sortable" data-key="num" aria-sort="ascending">#</th>'
        '<th class="adr-sortable" data-key="title">Title</th>'
        '<th class="adr-sortable" data-key="type">Type</th>'
        '<th class="adr-sortable" data-key="status">Status</th></tr>\n'
        "    </thead>\n"
        "    <tbody>\n" + "\n".join(rows) + "\n    </tbody>\n"
        "  </table>\n"
        "</div>"
    )

    parts = [GENERATED_COMMENT.strip(), "", intro, "", "## ADR Index", "", table, ""]
    if tail:
        parts += [tail, ""]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Navigation (zensical.toml)
# --------------------------------------------------------------------------- #
def generate_nav_block() -> str:
    """A single nav leaf pointing at the ADR Overview (index) page.

    The ADRs are browsed from that page — a sortable/filterable, color-badged
    table — rather than expanded as ~50 individual nav entries grouped by
    status (the old grouping is what broke when the metadata format changed).
    """
    entry = '        { "Architecture Decision Records" = "developers/adrs/index.md" },'
    return f"{NAV_START}\n{entry}\n{NAV_END}"


def update_nav() -> None:
    content = ZENSICAL_FILE.read_text(encoding="utf-8")
    # Drop any previously generated block (idempotent re-runs).
    content = re.sub(
        re.escape(NAV_START) + r".*?" + re.escape(NAV_END) + r"\n",
        "",
        content,
        flags=re.DOTALL,
    )
    if NAV_ANCHOR not in content:
        raise SystemExit(
            f"convert_adrs: nav anchor not found in {ZENSICAL_FILE}: {NAV_ANCHOR!r}"
        )
    block = generate_nav_block() + "\n"
    content = content.replace(NAV_ANCHOR, block + NAV_ANCHOR, 1)
    ZENSICAL_FILE.write_text(content, encoding="utf-8")


# --------------------------------------------------------------------------- #
def main() -> None:
    if not SRC_DIR.exists():
        raise SystemExit(f"convert_adrs: source not found: {SRC_DIR}")

    adrs = load_adrs()
    by_num = {a.num: a for a in adrs}
    adr_files = {a.filename for a in adrs} | {"000-readme.md"}

    if DEST_DIR.exists():
        shutil.rmtree(DEST_DIR)
    DEST_DIR.mkdir(parents=True)

    for adr in adrs:
        write_adr_page(adr, by_num, adr_files)
    (DEST_DIR / "index.md").write_text(generate_index(adrs), encoding="utf-8")
    update_nav()

    by_status = ", ".join(
        f"{s} {len(m)}" for s, m in grouped_by_status(adrs)
    )
    print(f"Published {len(adrs)} ADRs to {DEST_DIR}")
    print(f"  by status: {by_status}")
    print(f"Updated ADR navigation in {ZENSICAL_FILE}")


if __name__ == "__main__":
    main()
