[project]
name = "hop3-agent"
version = "0.3"
description = "Simple PaaS - Deploy and manage web applications on a single server"
authors = [
    { name = "Stefane Fermigier", email = "sf@abilian.com" },
]
readme = "README.md"

dependencies = [
    "attrs >= 24.2",
    # Plugins and DI
    "pluggy~=1.4",
    "wireup>=0.16.0",
    # Database
    "sqlalchemy ~= 2.0",
    "advanced-alchemy >= 0.21",
    "psycopg2 ~= 2.9",
    "flask-security-too ~= 5.5.2",
    # Misc
    "termcolor >= 2.5.0",
    # SBOM
    "cyclonedx-bom>=5.1.1",
]

[dependency-groups]
dev = [
    "typing-extensions>=4.12.2",
]

[project.scripts]
hop-agent = "hop3.main:main"

# ----------------------------------------

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/hop3"]

# ----------------------------------------

[tool.pyright]
exclude = [
    "src/hop3/util/templating.py",
]

# -----------------------------------------------------------------------------

[tool.deptry.per_rule_ignores]
# X defined as a dependency but not used in the codebase
DEP002 = [
    "cyclonedx-bom",
]
#DEP003 = [
#    "snoop",
#]
