[project]
name = "hop3-agent"
version = "0.2.2"
description = "Simple PaaS - Deploy and manage web applications on a single server"
authors = [
    { name = "Stefane Fermigier", email = "sf@abilian.com" },
]
readme = "README.md"

#packages = [
#    { include = "hop3", from = "src" },
#]
dependencies = [
    "attrs >= 24.2",
    "cleez >= 0.1.13",
    "click ~= 8.1",
    "pluggy ~= 1.4",
    # Database
    "sqlalchemy ~= 2.0",
    "advanced-alchemy >= 0.21",
    "psycopg2 ~= 2.9",
    "flask-security-too ~= 5.5.2",
]

[dependency-groups]
dev = [
    "typing-extensions>=4.12.2",
]

[project.scripts]
hop-agent = "hop3.main:main"

[tool.pyright]
exclude = [
    "src/hop3/util/templating.py",
]

[tool.coverage.report]
exclude_also = [
    "if typing.TYPE_CHECKING:",
    "if TYPE_CHECKING:",
]
