# Copyright (c) 2025-2026, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""Hop3 Installer package.

This package provides installers for the Hop3 CLI and Server components.
The installers use only the Python standard library for maximum portability.

For production use, single-file installer scripts are generated by the bundler.
"""

from __future__ import annotations

__version__ = "0.1.0"
