ServerName %{HTTP_HOST}

<VirtualHost *:8000>
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    CustomLog "|/bin/cat" proxy
    ErrorLog "|/bin/cat"

    DocumentRoot /app/code
    AllowEncodedSlashes On

    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined

    <Directory "/app/code/config">
        Require all denied
    </Directory>

    <Directory "/app/code/tmp">
        Require all denied
    </Directory>

    <Directory "/app/code/lang">
        Require all denied
    </Directory>

    <Directory /app/code>
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
