## Project info
#site_name: Hop3 doc
#site_description: The official website and documentation site for the Hop3 self-sovereign cloud platform project
#site_author: Abilian SAS
#site_url: https://hop3.cloud/
#
#docs_dir: src
#
#nav:
#  - Home:
#      - Introduction: index.md
#      - Installation: installation.md
#      - Funding: funding.md
#      - FAQ: faq.md
#  - Developers:
#    - "Contributing": dev/contributing.md
#    - "Getting started": dev/getting-started.md
#    - "Core Values": dev/core-values.md
#    - "Architecture / Design": dev/architecture.md
#    - "Governance": dev/governance.md
#    - "Code of Conduct": policies/code-of-conduct.md
#    - "Maintainers": dev/maintainers.md
#  - "API":
#    - "hop3-agent": api/hop3-agent.md
#  - News: news/index.md
#
### Navigation
##nav:
##  - Home:
##      - Introduction: index.md
##      - "Available apps": apps.md
##      - Funding: funding.md
##  - Users:
##      - Introduction: user/index.md
##      - Installation: user/install.md
##      - Command Line Interface: user/cli.md
##  - Developers:
##      - Introduction: dev/index.md
##      - "Nua as a R&D project": dev/r-and-d.md
##      - Architecture: dev/architecture.md
##      - Components:
##          - CLI: dev/components/cli.md
##          - Builder: dev/components/builder.md
##          - Orchestrator: dev/components/orchestrator.md
##      - "Specifications":
##          - "Specifications: Configuration": dev/specifications/configuration.md
##          - "Specification: App Images": dev/specifications/image.md
##      - API:
##          - "nua-lib API": dev/api/nua-lib.md
##          - "nua-agent API": dev/api/nua-agent.md
##          - "nua-build API": dev/api/nua-build.md
##          - "nua-orchestrator API": dev/api/nua-orchestrator.md
##      - Process and tools: dev/process-tools.md
##      - Contributing: dev/contributing.md
##      - Change log: dev/changelog.md
##      - Credits: dev/authors.md
#
## Copyright
#copyright: Copyright &copy; 2021-2024 Abilian SAS
#
## Repository
#repo_name: 'abilian/hop3'
#repo_url: 'https://github.com/abilian/hop3'
#edit_uri: 'https://github.com/abilian/hop3-doc/blob/master/src/'
#
## Configuration
#theme:
#  name: material
#  custom_dir: overrides
#  icon:
#    logo: material/book-open-page-variant
#  language: en
#  palette:
#    - media: "(prefers-color-scheme: light)"
#      scheme: default
#      # primary: dark-blue
#      # accent: purple
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      primary: cyan
#      accent: purple
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode
#  font:
#    text: Roboto
#    code: Roboto Mono
#  features:
#    - navigation.tabs
#    - navigation.top
#    # - navigation.instant
#
#extra:
#  homepage: https://hop3.cloud
#  generator: false
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/abilian/hop3
#    - icon: fontawesome/brands/twitter
#      link: https://x.com/abilianhq
#  analytics:
#    provider: custom
#
#extra_css:
#    - stylesheets/theme.css
#    - stylesheets/extra.css
#
## Extensions
#markdown_extensions:
#  - meta
#  - footnotes
#  - admonition
#  - toc:
#      permalink: true
#  - smarty
#  - sane_lists
#  - nl2br
#  - fenced_code
#  - pymdownx.highlight
#  - pymdownx.magiclink
#  - pymdownx.tasklist
#  - codehilite:
#      css_class: highlight
#
#plugins:
#  - search
#  - include-markdown
#  - roamlinks
#
##  - blog:
##      blog_dir: news
##      archive_name: Archive
##      archive: true
##      archive_date_format: yyyy
##      archive_toc: true
#
##  - with-pdf:
##      author: Stefane Fermigier
##      copyright: © 2021-2024 Abilian
##      cover: true
##      back_cover: false
##      cover_title: Hop3
##      cover_subtitle: Self-sovereign cloud platform
##      enabled_if_env: ENABLE_PDF_EXPORT
#
#  - mkdocstrings:
#      handlers:
#        python:
#          paths: [
#            "../hop3-agent/src/",
##            "../nua-agent/src/",
##            "../nua-build/src/",
##            "../nua-orchestrator/src/",
#          ]
#          options:
#            heading_level: 3
#            separate_signature: true
#            filters: [ "!^_" ]
#            show_object_full_path: false
#            members_order: source
#            line_length: 88
#            show_bases: false
#            show_source: false
#            merge_init_into_class: true
#            docstring_options:
#              ignore_init_summary: false
#              trim_doctest_flags: true
##            docstring_options:
##              ignore_init_summary: true
#            group_by_category: true
#            signature_crossrefs: true
#            show_root_toc_entry: false
#            show_inheritance_diagram: true
#
#      #    custom_template_path: TEMPLATES PATH
#      #
#      #toc_title: TOC TITLE TEXT
#      #heading_shift: false
#      #toc_level: 3
#      #ordered_chapter_level: 2
#      #excludes_children:
#      #    - 'release-notes/:upgrading'
#      #    - 'release-notes/:changelog'
#      #
#      #exclude_pages:
#      #    - 'bugs/'
#      #    - 'appendix/contribute/'
#      #convert_iframe:
#      #    - src: IFRAME SRC
#      #      img: POSTER IMAGE URL
#      #      text: ALTERNATE TEXT
#      #    - src: ...
#      #two_columns_level: 3
#      #
#      #render_js: true
#      #headless_chrome_path: headless-chromium
#      #
#      #output_path: any-place/document.pdf
#      #
#      #debug_html: true
#      #show_anchors: true
#      #verbose: true
