# prefork MPM
<IfModule mpm_prefork_module>
    StartServers             2
    MinSpareServers          2
    MaxSpareServers          4
    MaxRequestWorkers       20
    MaxConnectionsPerChild   0
</IfModule>
