replicas: 1

# clustersAffinity is where Karmada will deploy the application.
# This value is injected by the SMO based on its placement decision.
clustersAffinity:
- cluster1-master

# serviceImportClusters defines which clusters need to import this service
# for cross-cluster communication.
serviceImportClusters: []

service:
  port: 8080

resources:
  limits:
    cpu: "200m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"
