#!/usr/bin/env python3
# Copyright (c) 2025, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""
Hop3 Server Installer

A single-file installer for the Hop3 Server.
Uses only Python standard library for maximum portability.
Must be run as root.

Usage:
    curl -LsSf https://hop3.cloud/install-server.py | sudo python3 -
    curl -LsSf https://hop3.cloud/install-server.py | sudo python3 - --git
    sudo python3 install-server.py --help
"""

from __future__ import annotations

# =============================================================================
# Version Check (must run before any 3.10+ features are used at runtime)
# =============================================================================
import sys

MIN_PYTHON = (3, 10)

if sys.version_info < MIN_PYTHON:
    print(f"Error: Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required")
    print(f"Found: Python {sys.version_info.major}.{sys.version_info.minor}")
    print()
    print("Please install a newer Python version:")
    print("  Ubuntu/Debian: sudo apt install python3.11")
    print("  Fedora:        sudo dnf install python3.11")
    sys.exit(1)

# =============================================================================
# Imports (standard library only)
# =============================================================================
# ruff: noqa: E402 - imports must come after version check

import argparse
import grp
import itertools
import os
import pwd
import secrets
import shutil
import subprocess
import threading
import time
from pathlib import Path

# =============================================================================
# Configuration
# =============================================================================

PACKAGE_NAME = "hop3-server"
GIT_REPO = "https://github.com/abilian/hop3.git"
GIT_SUBDIR = "packages/hop3-server"
DEFAULT_BRANCH = "main"

HOP3_USER = "hop3"
HOP3_GROUP = "hop3"
HOME_DIR = Path("/home") / HOP3_USER
VENV_DIR = HOME_DIR / "venv"

# System dependencies by distribution
DEBIAN_PACKAGES = [
    "bc",
    "git",
    "sudo",
    "cron",
    "build-essential",
    "libpcre3-dev",
    "zlib1g-dev",
    "nginx",
    "postgresql",
    "postgresql-contrib",
    "python3-dev",
    "python3-pip",
    "python3-venv",
    "curl",
    "wget",
    "rsync",
    "socat",
    "libjpeg-dev",
    "libpng-dev",
    "libwebp-dev",
    "libpq-dev",
    "libffi-dev",
    "libssl-dev",
]

FEDORA_PACKAGES = [
    "bc",
    "git",
    "sudo",
    "cronie",
    "gcc",
    "gcc-c++",
    "make",
    "pcre-devel",
    "zlib-devel",
    "nginx",
    "postgresql-server",
    "postgresql-contrib",
    "python3-devel",
    "python3-pip",
    "curl",
    "wget",
    "rsync",
    "socat",
    "libjpeg-devel",
    "libpng-devel",
    "libwebp-devel",
    "libpq-devel",
    "libffi-devel",
    "openssl-devel",
]

# Systemd service units
SYSTEMD_UNIT = """[Unit]
Description=Hop3 Server
After=network.target postgresql.service

[Service]
Type=simple
User=hop3
Group=hop3
WorkingDirectory=/home/hop3
ExecStart=/home/hop3/venv/bin/hop-server serve
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

UWSGI_UNIT = """[Unit]
Description=uWSGI Emperor for Hop3
After=network.target

[Service]
Type=notify
User=hop3
Group=hop3
ExecStart=/home/hop3/venv/bin/uwsgi --emperor /home/hop3/uwsgi-enabled --stats /tmp/hop3-uwsgi-stats.sock
Restart=always
KillSignal=SIGQUIT
NotifyAccess=all

[Install]
WantedBy=multi-user.target
"""

# SSL certificate paths
SSL_DIR = Path("/etc/hop3/ssl")
SSL_CERT = SSL_DIR / "hop3.crt"
SSL_KEY = SSL_DIR / "hop3.key"

# Nginx configuration template for hop3-server reverse proxy
# {server_name} will be replaced with domain or "_" for catch-all
# {ssl_cert} and {ssl_key} will be replaced with certificate paths
NGINX_CONFIG = """# Hop3 Server - Reverse Proxy Configuration
# Auto-generated by hop3 installer

# Redirect HTTP to HTTPS
server {{
    listen 80;
    server_name {server_name};

    location /.well-known/acme-challenge/ {{
        root /var/www/html;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# HTTPS server
server {{
    listen 443 ssl http2;
    server_name {server_name};

    ssl_certificate {ssl_cert};
    ssl_certificate_key {ssl_key};

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Hop3 Server API (JSON-RPC)
    location /rpc {{
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }}

    # Hop3 Server Web UI (if enabled)
    location /hop3/ {{
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    # Health check endpoint
    location /health {{
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }}

    # Default: serve static files or return 404
    location / {{
        root /var/www/html;
        try_files $uri $uri/ =404;
    }}
}}
"""

# =============================================================================
# Terminal Output
# =============================================================================


class Colors:
    """ANSI color codes."""

    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    YELLOW = "\033[0;33m"
    BLUE = "\033[0;34m"
    CYAN = "\033[0;36m"

    @classmethod
    def disable(cls) -> None:
        for attr in ["RESET", "BOLD", "DIM", "RED", "GREEN", "YELLOW", "BLUE", "CYAN"]:
            setattr(cls, attr, "")


# Disable colors if not a TTY
if not sys.stdout.isatty():
    Colors.disable()


def print_header(title: str) -> None:
    """Print a styled header."""
    print()
    print(f"{Colors.BOLD}{Colors.CYAN}{title}{Colors.RESET}")
    print(f"{Colors.DIM}{'=' * len(title)}{Colors.RESET}")
    print()


def print_step(step: int, total: int, message: str) -> None:
    """Print a step indicator."""
    print(f"\n{Colors.BOLD}[{step}/{total}]{Colors.RESET} {message}")


def print_success(message: str) -> None:
    """Print a success message."""
    print(f"      {Colors.GREEN}✓{Colors.RESET} {message}")


def print_info(message: str) -> None:
    """Print an info message."""
    print(f"      {Colors.BLUE}ℹ{Colors.RESET} {message}")


def print_warning(message: str) -> None:
    """Print a warning message."""
    print(f"      {Colors.YELLOW}⚠{Colors.RESET} {message}")


def print_error(message: str) -> None:
    """Print an error message."""
    print(f"      {Colors.RED}✗{Colors.RESET} {message}", file=sys.stderr)


def print_detail(message: str) -> None:
    """Print a detail/sub-item."""
    print(f"        {Colors.DIM}{message}{Colors.RESET}")


# =============================================================================
# Spinner for Long Operations
# =============================================================================


class Spinner:
    """A simple terminal spinner for long-running operations."""

    CHARS = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

    def __init__(self, message: str):
        self.message = message
        self.spinning = False
        self.thread: threading.Thread | None = None

    def __enter__(self) -> Spinner:
        if sys.stdout.isatty():
            self.spinning = True
            self.thread = threading.Thread(target=self._spin, daemon=True)
            self.thread.start()
        else:
            print(f"      ... {self.message}")
        return self

    def __exit__(self, *args) -> None:
        self.spinning = False
        if self.thread:
            self.thread.join(timeout=0.5)
        if sys.stdout.isatty():
            print(f"\r{' ' * (len(self.message) + 12)}\r", end="")

    def _spin(self) -> None:
        for char in itertools.cycle(self.CHARS):
            if not self.spinning:
                break
            print(
                f"\r      {Colors.CYAN}{char}{Colors.RESET} {self.message}",
                end="",
                flush=True,
            )
            time.sleep(0.08)


# =============================================================================
# Command Execution
# =============================================================================


class CommandError(Exception):
    """Raised when a command fails."""

    def __init__(self, cmd: list[str], returncode: int, stderr: str):
        self.cmd = cmd
        self.returncode = returncode
        self.stderr = stderr
        super().__init__(f"Command failed: {' '.join(cmd)}")


def run_cmd(
    cmd: list[str],
    capture: bool = True,
    check: bool = True,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess:
    """Run a command and return the result."""
    run_env = os.environ.copy()
    if env:
        run_env.update(env)

    result = subprocess.run(
        cmd,
        check=False,
        capture_output=capture,
        text=True,
        env=run_env,
    )

    if check and result.returncode != 0:
        raise CommandError(cmd, result.returncode, result.stderr or "")

    return result


def run_as_hop3(cmd: str) -> subprocess.CompletedProcess:
    """Run a command as the hop3 user."""
    return run_cmd(["su", "-", HOP3_USER, "-c", cmd])


def cmd_exists(cmd: str) -> bool:
    """Check if a command exists in PATH."""
    return shutil.which(cmd) is not None


# =============================================================================
# System Detection
# =============================================================================


def detect_distro() -> str:
    """Detect the Linux distribution. Returns 'debian', 'fedora', or 'unknown'."""
    os_release = Path("/etc/os-release")
    if os_release.exists():
        content = os_release.read_text()
        if any(d in content.lower() for d in ["ubuntu", "debian", "mint", "pop"]):
            return "debian"
        if any(
            d in content.lower() for d in ["fedora", "rhel", "centos", "rocky", "alma"]
        ):
            return "fedora"
        if "arch" in content.lower():
            return "arch"
    return "unknown"


def user_exists(username: str) -> bool:
    """Check if a user exists."""
    try:
        pwd.getpwnam(username)
        return True
    except KeyError:
        return False


def group_exists(groupname: str) -> bool:
    """Check if a group exists."""
    try:
        grp.getgrnam(groupname)
        return True
    except KeyError:
        return False


# =============================================================================
# Installation Steps
# =============================================================================


def install_system_deps(distro: str, skip: bool) -> None:
    """Install system dependencies."""
    if skip:
        print_info("Skipping system dependencies (--skip-deps)")
        return

    if distro == "debian":
        with Spinner("Updating package lists..."):
            run_cmd(["apt-get", "update", "-qq"])
        with Spinner("Installing packages (this may take a while)..."):
            run_cmd(
                ["apt-get", "install", "-y", "-qq"] + DEBIAN_PACKAGES,
                env={"DEBIAN_FRONTEND": "noninteractive"},
            )
        print_success(f"Installed {len(DEBIAN_PACKAGES)} packages")

    elif distro == "fedora":
        with Spinner("Installing packages (this may take a while)..."):
            run_cmd(["dnf", "install", "-y", "-q"] + FEDORA_PACKAGES)
        print_success(f"Installed {len(FEDORA_PACKAGES)} packages")

    else:
        print_warning(f"Unknown distro '{distro}', skipping package installation")
        print_detail("You may need to install dependencies manually")


def create_user_and_group() -> None:
    """Create the hop3 user and group."""
    # Create group
    if not group_exists(HOP3_GROUP):
        run_cmd(["groupadd", HOP3_GROUP])
        print_success(f"Created group: {HOP3_GROUP}")
    else:
        print_info(f"Group {HOP3_GROUP} already exists")

    # Create user
    if not user_exists(HOP3_USER):
        run_cmd(
            [
                "useradd",
                "-m",
                "-g",
                HOP3_GROUP,
                "-s",
                "/bin/bash",
                "-d",
                str(HOME_DIR),
                HOP3_USER,
            ]
        )
        print_success(f"Created user: {HOP3_USER}")
    else:
        print_info(f"User {HOP3_USER} already exists")

    # Ensure home directory exists with correct permissions
    if not HOME_DIR.exists():
        HOME_DIR.mkdir(parents=True, exist_ok=True)
        print_info(f"Created home directory: {HOME_DIR}")

    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(HOME_DIR, hop3_uid, hop3_gid)
    os.chmod(HOME_DIR, 0o755)

    # Add www-data to hop3 group
    if user_exists("www-data"):
        run_cmd(["usermod", "-a", "-G", HOP3_GROUP, "www-data"], check=False)
        print_info("Added www-data to hop3 group")


def create_virtual_environment() -> None:
    """Create Python virtual environment."""
    if VENV_DIR.exists():
        shutil.rmtree(VENV_DIR)

    with Spinner("Creating virtual environment..."):
        run_as_hop3(f"python3 -m venv {VENV_DIR}")

    print_success(f"Virtual environment created at {VENV_DIR}")


def install_package(
    version: str | None,
    use_git: bool,
    branch: str,
    local_path: str | None,
    verbose: bool,
) -> None:
    """Install the hop3-server package."""
    pip = f"{VENV_DIR}/bin/pip"

    # Upgrade pip
    with Spinner("Upgrading pip..."):
        run_as_hop3(f"{pip} install --upgrade pip")

    # Determine what to install
    if local_path:
        package_spec = local_path
        source_desc = f"local path ({local_path})"
    elif use_git:
        with Spinner("Installing build tools..."):
            run_as_hop3(f"{pip} install uv")
        package_spec = f"git+{GIT_REPO}@{branch}#subdirectory={GIT_SUBDIR}"
        source_desc = f"git ({branch} branch)"
    elif version:
        package_spec = f"{PACKAGE_NAME}=={version}"
        source_desc = f"PyPI (version {version})"
    else:
        package_spec = PACKAGE_NAME
        source_desc = "PyPI (latest)"

    # Install
    with Spinner(f"Installing hop3-server from {source_desc}..."):
        run_as_hop3(f"{pip} install '{package_spec}'")

    print_success("hop3-server installed successfully")


def run_hop3_setup() -> None:
    """Run hop3 setup command."""
    hop_server = f"{VENV_DIR}/bin/hop-server"

    with Spinner("Running initial setup..."):
        run_as_hop3(f"{hop_server} setup")

    print_success("Hop3 initial setup complete")


def setup_ssh_keys() -> None:
    """Copy root SSH keys to hop3 user if available."""
    root_keys = Path("/root/.ssh/authorized_keys")

    if not root_keys.exists():
        print_info("No root SSH keys found, skipping")
        return

    content = root_keys.read_text().strip()
    if not content:
        print_info("Root SSH keys file is empty, skipping")
        return

    hop_server = f"{VENV_DIR}/bin/hop-server"
    temp_keys = Path("/tmp/root_authorized_keys")

    try:
        # Copy keys to temp location
        shutil.copy2(root_keys, temp_keys)
        hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
        hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
        os.chown(temp_keys, hop3_uid, hop3_gid)

        # Run setup:ssh
        run_as_hop3(f"{hop_server} setup:ssh {temp_keys}")
        print_success("SSH keys configured")
    except CommandError:
        print_warning("Could not configure SSH keys (invalid format?)")
    finally:
        if temp_keys.exists():
            temp_keys.unlink()


def setup_systemd() -> None:
    """Install and enable systemd services."""
    # Hop3 server service
    service_path = Path("/etc/systemd/system/hop3-server.service")
    service_path.write_text(SYSTEMD_UNIT)

    # uWSGI service
    uwsgi_path = Path("/etc/systemd/system/uwsgi-hop3.service")
    uwsgi_path.write_text(UWSGI_UNIT)

    # Reload and enable
    run_cmd(["systemctl", "daemon-reload"])
    run_cmd(["systemctl", "enable", "hop3-server"], check=False)
    run_cmd(["systemctl", "enable", "uwsgi-hop3"], check=False)
    run_cmd(["systemctl", "start", "hop3-server"], check=False)

    print_success("Systemd services configured")


def setup_nginx(skip: bool, domain: str | None = None) -> None:
    """Configure nginx as reverse proxy for hop3-server."""
    if skip:
        print_info("Skipping nginx setup (--skip-nginx)")
        return

    # Determine server name
    server_name = domain if domain else "_"

    # Generate nginx config
    nginx_config = NGINX_CONFIG.format(
        server_name=server_name,
        ssl_cert=str(SSL_CERT),
        ssl_key=str(SSL_KEY),
    )

    # Write config file
    nginx_config_path = Path("/etc/nginx/sites-available/hop3")
    nginx_enabled_path = Path("/etc/nginx/sites-enabled/hop3")

    # For Fedora/RHEL, use conf.d instead
    if not Path("/etc/nginx/sites-available").exists():
        nginx_config_path = Path("/etc/nginx/conf.d/hop3.conf")
        nginx_enabled_path = None  # No symlink needed

    nginx_config_path.parent.mkdir(parents=True, exist_ok=True)
    nginx_config_path.write_text(nginx_config)
    print_success(f"Nginx config written to {nginx_config_path}")

    # Create symlink if using sites-available/sites-enabled
    if nginx_enabled_path:
        nginx_enabled_path.parent.mkdir(parents=True, exist_ok=True)
        if nginx_enabled_path.exists() or nginx_enabled_path.is_symlink():
            nginx_enabled_path.unlink()
        nginx_enabled_path.symlink_to(nginx_config_path)
        print_success("Nginx site enabled")

        # Remove default site if exists
        default_site = Path("/etc/nginx/sites-enabled/default")
        if default_site.exists() or default_site.is_symlink():
            default_site.unlink()
            print_info("Removed default nginx site")

    # Add include for app-specific nginx configs in /home/hop3/nginx/
    _add_hop3_nginx_include()

    # Test nginx config
    try:
        run_cmd(["nginx", "-t"])
        print_success("Nginx configuration is valid")
    except CommandError as e:
        print_error(f"Nginx configuration test failed: {e.stderr[:200]}")
        return

    # Enable and start/reload nginx
    run_cmd(["systemctl", "enable", "nginx"], check=False)
    run_cmd(["systemctl", "restart", "nginx"], check=False)
    print_success("Nginx enabled and started")


def _add_hop3_nginx_include() -> None:
    """Add include directive for hop3 app configs to nginx.conf."""
    nginx_conf = Path("/etc/nginx/nginx.conf")
    include_line = "include /home/hop3/nginx/*.conf;"

    if not nginx_conf.exists():
        print_warning("nginx.conf not found, skipping app include setup")
        return

    content = nginx_conf.read_text()

    # Check if already present
    if include_line in content:
        print_info("Hop3 app nginx include already configured")
        return

    # Create the nginx directory for app configs
    hop3_nginx_dir = HOME_DIR / "nginx"
    hop3_nginx_dir.mkdir(parents=True, exist_ok=True)
    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(hop3_nginx_dir, hop3_uid, hop3_gid)

    # Find the right place to add the include (after sites-enabled or conf.d include)
    # Look for existing include patterns in the http block
    lines = content.split("\n")
    new_lines = []
    include_added = False

    for i, line in enumerate(lines):
        new_lines.append(line)
        # Add after sites-enabled or conf.d include
        if not include_added and "include" in line:
            if "sites-enabled" in line or "conf.d" in line:
                # Preserve indentation
                indent = len(line) - len(line.lstrip())
                new_lines.append(" " * indent + include_line)
                include_added = True

    if include_added:
        nginx_conf.write_text("\n".join(new_lines))
        print_success("Added hop3 app nginx include to nginx.conf")
    else:
        print_warning("Could not find suitable location for nginx include")


def setup_postgres(skip: bool, distro: str) -> str | None:
    """Configure PostgreSQL.

    Returns:
        The generated postgres superuser password, or None if skipped.
    """
    if skip:
        print_info("Skipping PostgreSQL setup (--skip-postgres)")
        return None

    # Initialize PostgreSQL on Fedora
    if distro == "fedora":
        if not Path("/var/lib/pgsql/data/pg_hba.conf").exists():
            run_cmd(["postgresql-setup", "--initdb"], check=False)

    run_cmd(["systemctl", "enable", "postgresql"], check=False)
    run_cmd(["systemctl", "start", "postgresql"], check=False)

    # Create role and database for hop3 user
    try:
        run_cmd(
            ["su", "-", "postgres", "-c", f"createuser --createdb {HOP3_USER}"],
            check=False,
        )
        run_cmd(
            ["su", "-", "postgres", "-c", f"createdb -O {HOP3_USER} hop3"],
            check=False,
        )
        print_success("PostgreSQL role and database created")
    except CommandError:
        print_info("PostgreSQL role/database may already exist")

    # Set a password for the postgres superuser
    # This is needed for hop3-server to create addon databases via TCP connection
    pg_password = "hop3_" + secrets.token_hex(16)

    # Use psql to set the password (peer auth works since we're root -> postgres user)
    sql_cmd = f"ALTER USER postgres PASSWORD '{pg_password}';"
    result = run_cmd(
        ["su", "-", "postgres", "-c", f'psql -c "{sql_cmd}"'],
        check=False,
    )
    if result.returncode == 0:
        print_success("PostgreSQL superuser password configured")
    else:
        print_warning("Could not set PostgreSQL superuser password")
        return None

    # Configure PostgreSQL to accept connections from Docker containers
    # Docker containers connect via host.docker.internal which routes to 172.17.x.x
    _configure_postgres_for_docker(distro)

    return pg_password


def _configure_postgres_for_docker(distro: str) -> None:
    """Configure PostgreSQL to accept connections from Docker containers.

    This modifies postgresql.conf and pg_hba.conf to:
    1. Listen on all interfaces (not just localhost)
    2. Allow password auth from Docker bridge network (172.17.0.0/16)
    """
    # Find PostgreSQL config directory
    if distro == "fedora":
        pg_conf_dir = Path("/var/lib/pgsql/data")
    else:  # debian
        # Find the postgresql version directory
        pg_dirs = list(Path("/etc/postgresql").glob("*/main"))
        if not pg_dirs:
            print_warning("Could not find PostgreSQL config directory")
            return
        pg_conf_dir = pg_dirs[0]

    pg_conf = pg_conf_dir / "postgresql.conf"
    pg_hba = pg_conf_dir / "pg_hba.conf"

    if not pg_conf.exists():
        print_warning(f"PostgreSQL config not found at {pg_conf}")
        return

    # Update listen_addresses to accept connections from Docker
    conf_content = pg_conf.read_text()
    if "listen_addresses = '*'" not in conf_content:
        # Comment out existing listen_addresses and add new one
        new_lines = []
        for line in conf_content.split("\n"):
            if line.strip().startswith("listen_addresses"):
                new_lines.append(f"# {line}  # commented by hop3 installer")
            else:
                new_lines.append(line)
        new_lines.append("")
        new_lines.append("# Added by hop3 installer for Docker container access")
        new_lines.append("listen_addresses = '*'")
        pg_conf.write_text("\n".join(new_lines))
        print_success("PostgreSQL configured to listen on all interfaces")

    # Add pg_hba.conf rule for Docker networks
    # 172.16.0.0/12 covers all Docker networks (172.16.x.x - 172.31.x.x)
    # including default bridge (172.17.x.x) and docker-compose networks (172.18+)
    hba_content = pg_hba.read_text()
    docker_rule = "host    all    all    172.16.0.0/12    scram-sha-256"
    if "172.16.0.0/12" not in hba_content:
        # Add rule before the first "host" line (after local rules)
        new_lines = []
        docker_rule_added = False
        for line in hba_content.split("\n"):
            # Add Docker rule before first host rule
            if not docker_rule_added and line.strip().startswith("host"):
                new_lines.append(
                    "# Added by hop3 installer for Docker container access"
                )
                new_lines.append(docker_rule)
                new_lines.append("")
                docker_rule_added = True
            new_lines.append(line)
        # If no host rules found, add at end
        if not docker_rule_added:
            new_lines.append("")
            new_lines.append("# Added by hop3 installer for Docker container access")
            new_lines.append(docker_rule)
        pg_hba.write_text("\n".join(new_lines))
        print_success("PostgreSQL configured to accept Docker container connections")

    # Restart PostgreSQL to apply changes
    run_cmd(["systemctl", "restart", "postgresql"], check=False)
    print_success("PostgreSQL restarted with new configuration")


def write_server_config(pg_password: str | None) -> None:
    """Write hop3-server.toml configuration file.

    This configures hop3-server with:
    - PostgreSQL connection settings (host, password)
    """
    config_file = HOME_DIR / "hop3-server.toml"

    # Build config content
    lines = [
        "# Hop3 Server Configuration",
        "# Auto-generated by installer",
        "",
    ]

    if pg_password:
        lines.extend(
            [
                "# PostgreSQL admin connection settings",
                "# Use 127.0.0.1 (TCP) instead of localhost (Unix socket) for password auth",
                'POSTGRES_HOST = "127.0.0.1"',
                f'POSTGRES_SUPERUSER_PASSWORD = "{pg_password}"',
                "",
            ]
        )

    config_file.write_text("\n".join(lines))

    # Set ownership to hop3 user
    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(config_file, hop3_uid, hop3_gid)
    os.chmod(config_file, 0o600)  # Secure - contains password

    print_success(f"Server configuration written to {config_file}")


def setup_acme(skip: bool) -> None:
    """Install acme.sh for Let's Encrypt."""
    if skip:
        print_info("Skipping ACME setup (--skip-acme)")
        return

    acme_sh = HOME_DIR / ".acme.sh" / "acme.sh"

    if acme_sh.exists():
        print_info("acme.sh already installed")
        return

    with Spinner("Installing acme.sh..."):
        # Download
        run_as_hop3(
            "curl -fsSL https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh -o /tmp/acme.sh"
        )
        # Install (must run from /tmp)
        run_as_hop3("cd /tmp && bash acme.sh --install")
        run_cmd(["rm", "-f", "/tmp/acme.sh"])

    # Set default CA
    if acme_sh.exists():
        run_as_hop3(f"bash {acme_sh} --set-default-ca --server letsencrypt")
        print_success("acme.sh installed and configured")
    else:
        print_warning("acme.sh installation may have failed")


def setup_ssl_selfsigned() -> None:
    """Generate a self-signed SSL certificate for hop3-server."""
    if SSL_CERT.exists() and SSL_KEY.exists():
        print_info("SSL certificates already exist")
        return

    # Create SSL directory
    SSL_DIR.mkdir(parents=True, exist_ok=True)

    with Spinner("Generating self-signed SSL certificate..."):
        # Generate self-signed certificate valid for 10 years
        run_cmd(
            [
                "openssl",
                "req",
                "-x509",
                "-nodes",
                "-days",
                "3650",
                "-newkey",
                "rsa:2048",
                "-keyout",
                str(SSL_KEY),
                "-out",
                str(SSL_CERT),
                "-subj",
                "/CN=hop3-server/O=Hop3/C=US",
                "-addext",
                "subjectAltName=DNS:localhost,IP:127.0.0.1",
            ]
        )

    # Set permissions
    os.chmod(SSL_KEY, 0o600)
    os.chmod(SSL_CERT, 0o644)

    print_success("Self-signed SSL certificate generated")
    print_detail(f"Certificate: {SSL_CERT}")
    print_detail(f"Private key: {SSL_KEY}")


def setup_letsencrypt(domain: str) -> bool:
    """Request a Let's Encrypt certificate using acme.sh."""
    acme_sh = HOME_DIR / ".acme.sh" / "acme.sh"

    if not acme_sh.exists():
        print_error("acme.sh not installed, cannot request Let's Encrypt certificate")
        return False

    # Create webroot directory
    webroot = Path("/var/www/html")
    webroot.mkdir(parents=True, exist_ok=True)

    print_info(f"Requesting Let's Encrypt certificate for {domain}...")

    with Spinner("Requesting certificate (this may take a minute)..."):
        try:
            # Issue certificate using webroot mode
            run_as_hop3(
                f"bash {acme_sh} --issue -d {domain} -w {webroot} --keylength 2048"
            )
        except CommandError as e:
            print_error(f"Failed to request certificate: {e.stderr[:200]}")
            return False

    # Install certificate to hop3 SSL directory
    SSL_DIR.mkdir(parents=True, exist_ok=True)

    try:
        run_as_hop3(
            f"bash {acme_sh} --install-cert -d {domain} "
            f"--key-file {SSL_KEY} "
            f"--fullchain-file {SSL_CERT} "
            f"--reloadcmd 'sudo systemctl reload nginx'"
        )
    except CommandError as e:
        print_error(f"Failed to install certificate: {e.stderr[:200]}")
        return False

    # Set permissions
    os.chmod(SSL_KEY, 0o600)
    os.chmod(SSL_CERT, 0o644)

    print_success(f"Let's Encrypt certificate installed for {domain}")
    return True


def verify_installation() -> bool:
    """Verify the installation."""
    hop_server = VENV_DIR / "bin" / "hop-server"

    if not hop_server.exists():
        print_error("hop-server not found")
        return False

    # Check hop3-server service status
    result = run_cmd(
        ["systemctl", "is-active", "hop3-server"], capture=True, check=False
    )
    if result.stdout.strip() == "active":
        print_success("hop3-server service is running")
    else:
        print_warning("hop3-server service is not running")
        print_detail("Check with: sudo systemctl status hop3-server")

    # Check nginx service status
    result = run_cmd(["systemctl", "is-active", "nginx"], capture=True, check=False)
    if result.stdout.strip() == "active":
        print_success("nginx service is running")
    else:
        print_warning("nginx service is not running")
        print_detail("Check with: sudo systemctl status nginx")

    # Check SSL certificate exists
    if SSL_CERT.exists() and SSL_KEY.exists():
        print_success("SSL certificate is configured")
    else:
        print_warning("SSL certificate not found")

    return True


def print_final_message(domain: str | None = None) -> None:
    """Print success message with next steps."""
    print()
    print(f"{Colors.GREEN}{Colors.BOLD}Installation complete!{Colors.RESET}")
    print()
    print(f"  {Colors.BOLD}User:{Colors.RESET}      {HOP3_USER}")
    print(f"  {Colors.BOLD}Home:{Colors.RESET}      {HOME_DIR}")
    print(f"  {Colors.BOLD}Venv:{Colors.RESET}      {VENV_DIR}")
    print()
    print(f"  {Colors.BOLD}SSL:{Colors.RESET}")
    if domain:
        print(f"    Domain:      {domain}")
        print("    Certificate: Let's Encrypt (auto-renewed)")
    else:
        print(f"    Certificate: Self-signed ({SSL_CERT})")
        print("    Note:        Use --domain to enable Let's Encrypt")
    print()
    print(f"  {Colors.BOLD}Services:{Colors.RESET}")
    print("    sudo systemctl status hop3-server")
    print("    sudo systemctl status uwsgi-hop3")
    print("    sudo systemctl status nginx")
    print()
    print(f"  {Colors.BOLD}API endpoint:{Colors.RESET}")
    if domain:
        print(f"    https://{domain}/rpc")
    else:
        print("    https://<server-ip>/rpc")
    print()
    print(f"  {Colors.BOLD}Next steps:{Colors.RESET}")
    print("    1. Add your SSH key:  ssh-copy-id hop3@your-server")
    print("    2. Deploy an app:     hop3 deploy your-app.git")
    if not domain:
        print("    3. Configure a domain: re-run with --domain your.domain.com")
    print()
    print(f"  {Colors.BOLD}Logs:{Colors.RESET}")
    print("    sudo journalctl -u hop3-server -f")
    print()


# =============================================================================
# CLI Argument Parsing
# =============================================================================


def create_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    parser = argparse.ArgumentParser(
        prog="install-server.py",
        description="Install the Hop3 Server. Must be run as root.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  sudo python3 install-server.py                  Install with self-signed cert
  sudo python3 install-server.py --domain hop3.example.com
                                                  Install with Let's Encrypt cert
  sudo python3 install-server.py --git            Install from git (main branch)
  sudo python3 install-server.py --git --branch x Install from git (x branch)
  sudo python3 install-server.py --skip-postgres  Skip PostgreSQL setup

SSL Certificates:
  By default, a self-signed certificate is generated. To use Let's Encrypt,
  provide a domain name with --domain. The server must be accessible on ports
  80 and 443, and the domain must point to this server's IP address.

Environment Variables:
  HOP3_VERSION          Install specific version
  HOP3_GIT              Install from git (1 or true)
  HOP3_BRANCH           Git branch (default: main)
  HOP3_LOCAL_PACKAGE    Install from local path
  HOP3_DOMAIN           Domain for Let's Encrypt certificate
  HOP3_SKIP_DEPS        Skip system dependencies
  HOP3_SKIP_NGINX       Skip nginx setup
  HOP3_SKIP_POSTGRES    Skip PostgreSQL setup
  HOP3_SKIP_ACME        Skip ACME/Let's Encrypt setup
""",
    )

    parser.add_argument(
        "--version",
        metavar="VERSION",
        default=os.environ.get("HOP3_VERSION"),
        help="Install a specific version (e.g., 0.4.0)",
    )

    parser.add_argument(
        "--git",
        action="store_true",
        default=os.environ.get("HOP3_GIT", "").lower() in ("1", "true"),
        help="Install from git repository",
    )

    parser.add_argument(
        "--branch",
        metavar="BRANCH",
        default=os.environ.get("HOP3_BRANCH", DEFAULT_BRANCH),
        help=f"Git branch to install from (default: {DEFAULT_BRANCH})",
    )

    parser.add_argument(
        "--local-path",
        metavar="PATH",
        default=os.environ.get("HOP3_LOCAL_PACKAGE"),
        help="Install from a local directory",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        default=os.environ.get("HOP3_FORCE", "").lower() in ("1", "true"),
        help="Force reinstall even if already installed",
    )

    parser.add_argument(
        "--skip-deps",
        action="store_true",
        default=os.environ.get("HOP3_SKIP_DEPS", "").lower() in ("1", "true"),
        help="Skip system dependency installation",
    )

    parser.add_argument(
        "--skip-nginx",
        action="store_true",
        default=os.environ.get("HOP3_SKIP_NGINX", "").lower() in ("1", "true"),
        help="Skip nginx setup",
    )

    parser.add_argument(
        "--skip-postgres",
        action="store_true",
        default=os.environ.get("HOP3_SKIP_POSTGRES", "").lower() in ("1", "true"),
        help="Skip PostgreSQL setup",
    )

    parser.add_argument(
        "--skip-acme",
        action="store_true",
        default=os.environ.get("HOP3_SKIP_ACME", "").lower() in ("1", "true"),
        help="Skip ACME/Let's Encrypt setup",
    )

    parser.add_argument(
        "--domain",
        metavar="DOMAIN",
        default=os.environ.get("HOP3_DOMAIN"),
        help="Domain name for Let's Encrypt certificate (e.g., hop3.example.com)",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        default=os.environ.get("HOP3_VERBOSE", "").lower() in ("1", "true"),
        help="Show verbose output",
    )

    return parser


# =============================================================================
# Main
# =============================================================================


def main() -> int:
    """Main entry point. Returns exit code."""
    parser = create_parser()
    args = parser.parse_args()

    # Header
    print_header("Hop3 Server Installer")

    # Check root
    if os.geteuid() != 0:
        print_error("This installer must be run as root")
        print_detail("Use: sudo python3 install-server.py")
        return 1

    # Detect distro
    distro = detect_distro()
    print_info(f"Detected distribution: {distro}")

    total_steps = 12

    # Show configuration
    if args.domain:
        print_info(f"Domain: {args.domain} (will request Let's Encrypt certificate)")
    else:
        print_info("No domain specified (will use self-signed certificate)")

    # Step 1: System dependencies
    print_step(1, total_steps, "Installing system dependencies...")
    try:
        install_system_deps(distro, args.skip_deps)
    except CommandError as e:
        print_error(f"Failed to install dependencies: {e.stderr[:200]}")
        return 1

    # Step 2: Create user
    print_step(2, total_steps, "Creating hop3 user and group...")
    try:
        create_user_and_group()
    except CommandError as e:
        print_error(f"Failed to create user: {e.stderr}")
        return 1

    # Step 3: Virtual environment
    print_step(3, total_steps, "Creating virtual environment...")
    try:
        create_virtual_environment()
    except CommandError as e:
        print_error(f"Failed to create venv: {e.stderr}")
        return 1

    # Step 4: Install package
    print_step(4, total_steps, "Installing hop3-server...")
    try:
        install_package(
            version=args.version,
            use_git=args.git,
            branch=args.branch,
            local_path=args.local_path,
            verbose=args.verbose,
        )
    except CommandError as e:
        print_error("Failed to install hop3-server")
        if args.verbose:
            print_detail(e.stderr[:500])
        return 1

    # Step 5: Run setup
    print_step(5, total_steps, "Running initial setup...")
    try:
        run_hop3_setup()
    except CommandError as e:
        print_error(f"Setup failed: {e.stderr[:200]}")
        return 1

    # Step 6: SSH keys
    print_step(6, total_steps, "Configuring SSH keys...")
    setup_ssh_keys()

    # Step 7: Systemd
    print_step(7, total_steps, "Setting up systemd services...")
    try:
        setup_systemd()
    except CommandError as e:
        print_warning(f"Systemd setup issue: {e.stderr[:100]}")

    # Step 8: SSL certificates (self-signed first, Let's Encrypt later if domain provided)
    print_step(8, total_steps, "Setting up SSL certificates...")
    try:
        setup_ssl_selfsigned()
    except CommandError as e:
        print_warning(f"SSL setup issue: {e.stderr[:100]}")

    # Step 9: Nginx (needs SSL cert first)
    print_step(9, total_steps, "Configuring nginx reverse proxy...")
    try:
        setup_nginx(args.skip_nginx, args.domain)
    except CommandError as e:
        print_warning(f"Nginx setup issue: {e.stderr[:100]}")

    # Step 10: PostgreSQL
    print_step(10, total_steps, "Configuring PostgreSQL...")
    pg_password = None
    try:
        pg_password = setup_postgres(args.skip_postgres, distro)
    except CommandError as e:
        print_warning(f"PostgreSQL setup issue: {e.stderr[:100]}")

    # Step 11: Write server configuration
    print_step(11, total_steps, "Writing server configuration...")
    try:
        write_server_config(pg_password)
    except Exception as e:
        print_warning(f"Config write issue: {e}")

    # Step 12: ACME/Let's Encrypt
    print_step(12, total_steps, "Setting up ACME/Let's Encrypt...")
    try:
        # Always install acme.sh for future use
        setup_acme(args.skip_acme)

        # If domain provided, request Let's Encrypt certificate
        if args.domain and not args.skip_acme:
            if setup_letsencrypt(args.domain):
                # Reload nginx to use the new certificate
                run_cmd(["systemctl", "reload", "nginx"], check=False)
                print_success("Nginx reloaded with Let's Encrypt certificate")
    except CommandError as e:
        print_warning(f"ACME setup issue: {e.stderr[:100]}")

    # Verify
    print()
    verify_installation()

    # Success
    print_final_message(args.domain)

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nInstallation cancelled.")
        sys.exit(130)
    except Exception as e:
        print(f"\n{Colors.RED}Error:{Colors.RESET} {e}", file=sys.stderr)
        sys.exit(1)
