#!/usr/bin/env python3
# Copyright (c) 2025, Abilian SAS
# SPDX-License-Identifier: Apache-2.0
"""
Hop3 Server Installer - Install the Hop3 server

Usage:
    curl -LsSf https://hop3.cloud/install-server.py | sudo python3 -
    curl -LsSf https://hop3.cloud/install-server.py | sudo python3 - --git
    sudo python3 install-server.py --help

Generated by hop3-installer bundler on 2025-12-24 23:26:50
"""

from __future__ import annotations

# =============================================================================
# Version Check (must run before any 3.10+ features are used at runtime)
# =============================================================================
import sys

MIN_PYTHON = (3, 10)

if sys.version_info < MIN_PYTHON:
    print(f"Error: Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required")
    print(f"Found: Python {sys.version_info.major}.{sys.version_info.minor}")
    print()
    print("Please install a newer Python version:")
    print("  Ubuntu/Debian: sudo apt install python3.11")
    print("  Fedora:        sudo dnf install python3.11")
    print("  macOS:         brew install python@3.11")
    sys.exit(1)

# =============================================================================
# Imports (standard library only)
# =============================================================================
# ruff: noqa: E402 - imports must come after version check


import argparse
import grp
import itertools
import os
import pwd
import secrets
import shutil
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path


# =============================================================================
# Module: common
# =============================================================================

# =============================================================================
# Terminal Colors
# =============================================================================


class Colors:
    """ANSI color codes for terminal output."""

    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    YELLOW = "\033[0;33m"
    BLUE = "\033[0;34m"
    CYAN = "\033[0;36m"

    @classmethod
    def disable(cls) -> None:
        """Disable all colors (for non-TTY output)."""
        for attr in ["RESET", "BOLD", "DIM", "RED", "GREEN", "YELLOW", "BLUE", "CYAN"]:
            setattr(cls, attr, "")


# Disable colors if not a TTY
if not sys.stdout.isatty():
    Colors.disable()


# =============================================================================
# Output Functions
# =============================================================================


def print_header(title: str) -> None:
    """Print a styled header."""
    print()
    print(f"{Colors.BOLD}{Colors.CYAN}{title}{Colors.RESET}")
    print(f"{Colors.DIM}{'=' * len(title)}{Colors.RESET}")
    print()


def print_step(step: int, total: int, message: str) -> None:
    """Print a step indicator."""
    print(f"\n{Colors.BOLD}[{step}/{total}]{Colors.RESET} {message}")


def print_success(message: str) -> None:
    """Print a success message."""
    print(f"      {Colors.GREEN}✓{Colors.RESET} {message}")


def print_info(message: str) -> None:
    """Print an info message."""
    print(f"      {Colors.BLUE}ℹ{Colors.RESET} {message}")


def print_warning(message: str) -> None:
    """Print a warning message."""
    print(f"      {Colors.YELLOW}⚠{Colors.RESET} {message}")


def print_error(message: str) -> None:
    """Print an error message."""
    print(f"      {Colors.RED}✗{Colors.RESET} {message}", file=sys.stderr)


def print_detail(message: str) -> None:
    """Print a detail/sub-item."""
    print(f"        {Colors.DIM}{message}{Colors.RESET}")


# =============================================================================
# Spinner for Long Operations
# =============================================================================


class Spinner:
    """A simple terminal spinner for long-running operations.

    Usage:
        with Spinner("Installing packages..."):
            # long operation
            pass
    """

    CHARS = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

    def __init__(self, message: str):
        self.message = message
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None

    def __enter__(self) -> Spinner:
        if sys.stdout.isatty():
            self._stop_event.clear()
            self._thread = threading.Thread(target=self._spin, daemon=True)
            self._thread.start()
        else:
            print(f"      ... {self.message}")
        return self

    def __exit__(self, *args) -> None:
        self._stop_event.set()
        if self._thread:
            self._thread.join(timeout=0.5)
        if sys.stdout.isatty():
            # Clear the spinner line
            print(f"\r{' ' * (len(self.message) + 12)}\r", end="")

    def _spin(self) -> None:
        for char in itertools.cycle(self.CHARS):
            if self._stop_event.is_set():
                break
            print(
                f"\r      {Colors.CYAN}{char}{Colors.RESET} {self.message}",
                end="",
                flush=True,
            )
            time.sleep(0.08)


# =============================================================================
# Command Execution
# =============================================================================


@dataclass
class CommandError(Exception):
    """Raised when a command fails."""

    cmd: list[str]
    returncode: int
    stderr: str
    stdout: str = ""

    def __str__(self) -> str:
        return f"Command failed: {' '.join(self.cmd)}"


def run_cmd(
    cmd: list[str],
    capture: bool = True,
    check: bool = True,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess:
    """Run a command and return the result.

    Args:
        cmd: Command and arguments to run
        capture: Whether to capture stdout/stderr
        check: Whether to raise CommandError on non-zero exit
        env: Additional environment variables

    Returns:
        CompletedProcess with returncode, stdout, stderr

    Raises:
        CommandError: If check=True and command returns non-zero
    """
    run_env = os.environ.copy()
    if env:
        run_env.update(env)

    result = subprocess.run(
        cmd,
        check=False,
        capture_output=capture,
        text=True,
        env=run_env,
    )

    if check and result.returncode != 0:
        raise CommandError(
            cmd=cmd,
            returncode=result.returncode,
            stderr=result.stderr or "",
            stdout=result.stdout or "",
        )

    return result


def cmd_exists(cmd: str) -> bool:
    """Check if a command exists in PATH."""
    return shutil.which(cmd) is not None


# =============================================================================
# System Detection
# =============================================================================


def detect_distro() -> str:
    """Detect the Linux distribution.

    Returns:
        'debian' for Debian-based distros (Ubuntu, Mint, Pop!_OS)
        'fedora' for Red Hat-based distros (Fedora, RHEL, CentOS, Rocky, Alma)
        'arch' for Arch Linux
        'unknown' for unrecognized distributions
    """
    os_release = Path("/etc/os-release")
    if os_release.exists():
        content = os_release.read_text().lower()
        if any(d in content for d in ["ubuntu", "debian", "mint", "pop"]):
            return "debian"
        if any(d in content for d in ["fedora", "rhel", "centos", "rocky", "alma"]):
            return "fedora"
        if "arch" in content:
            return "arch"
    return "unknown"


def get_current_shell() -> str | None:
    """Detect the current shell.

    Returns:
        'bash', 'zsh', 'fish', or None if unrecognized
    """
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    if "fish" in shell:
        return "fish"
    if "bash" in shell:
        return "bash"
    return None


# =============================================================================
# Version Check Helper
# =============================================================================


MIN_PYTHON = (3, 10)


def check_python_version() -> None:
    """Check that Python version meets minimum requirements.

    Exits with error message if Python version is too old.
    """
    if sys.version_info < MIN_PYTHON:
        print(f"Error: Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required")
        print(f"Found: Python {sys.version_info.major}.{sys.version_info.minor}")
        print()
        print("Please install a newer Python version:")
        print("  Ubuntu/Debian: sudo apt install python3.11")
        print("  Fedora:        sudo dnf install python3.11")
        print("  macOS:         brew install python@3.11")
        sys.exit(1)


# =============================================================================
# Module: server.config
# =============================================================================

# Package configuration
PACKAGE_NAME = "hop3-server"
GIT_REPO = "https://github.com/abilian/hop3.git"
GIT_SUBDIR = "packages/hop3-server"
DEFAULT_BRANCH = "main"

# User configuration
HOP3_USER = "hop3"
HOP3_GROUP = "hop3"
HOME_DIR = Path("/home") / HOP3_USER
VENV_DIR = HOME_DIR / "venv"

# SSL certificate paths
SSL_DIR = Path("/etc/hop3/ssl")
SSL_CERT = SSL_DIR / "hop3.crt"
SSL_KEY = SSL_DIR / "hop3.key"

# System dependencies by distribution
# Note: npm is handled separately to avoid conflicts with NodeSource's nodejs
DEBIAN_PACKAGES = [
    "bc",
    "git",
    "sudo",
    "cron",
    "build-essential",
    "libpcre3-dev",
    "zlib1g-dev",
    "nginx",
    "postgresql",
    "postgresql-contrib",
    # Python toolchain
    "python3-dev",
    "python3-pip",
    "python3-venv",
    "python3-virtualenv",
    "python3-setuptools",
    # Node.js toolchain
    "nodejs",
    # Ruby toolchain
    "ruby",
    "ruby-dev",
    "ruby-bundler",
    "libyaml-dev",
    "libgmp-dev",
    # Go toolchain
    "golang-go",
    # Elixir toolchain
    "elixir",
    "erlang",
    # PHP toolchain
    "php",
    "php-cli",
    "php-mbstring",
    "php-xml",
    "php-curl",
    "php-zip",
    "php-pgsql",
    "php-mysql",
    "php-intl",
    "composer",
    # Java toolchain
    "default-jdk",
    "maven",
    # Common utilities
    "curl",
    "wget",
    "rsync",
    "socat",
    "libjpeg-dev",
    "libpng-dev",
    "libwebp-dev",
    "libpq-dev",
    "libffi-dev",
    "libssl-dev",
]

FEDORA_PACKAGES = [
    "bc",
    "git",
    "sudo",
    "cronie",
    "gcc",
    "gcc-c++",
    "make",
    "pcre-devel",
    "zlib-devel",
    "nginx",
    "postgresql-server",
    "postgresql-contrib",
    # Python toolchain
    "python3-devel",
    "python3-pip",
    "python3-virtualenv",
    "python3-setuptools",
    # Node.js toolchain
    "nodejs",
    # Ruby toolchain
    "ruby",
    "ruby-devel",
    "rubygem-bundler",
    "libyaml-devel",
    "gmp-devel",
    # Go toolchain
    "golang",
    # Elixir toolchain
    "elixir",
    "erlang",
    # PHP toolchain
    "php",
    "php-cli",
    "php-mbstring",
    "php-xml",
    "php-curl",
    "php-zip",
    "php-pgsql",
    "php-mysqlnd",
    "php-intl",
    "composer",
    # Java toolchain
    "java-17-openjdk-devel",
    "maven",
    # Common utilities
    "curl",
    "wget",
    "rsync",
    "socat",
    "openssl",  # CLI tool for SSL certificate generation
    "libjpeg-devel",
    "libpng-devel",
    "libwebp-devel",
    "libpq-devel",
    "libffi-devel",
    "openssl-devel",
]

# Optional packages
DEBIAN_MYSQL_PACKAGES = ["mysql-server", "mysql-client", "libmysqlclient-dev"]
FEDORA_MYSQL_PACKAGES = ["mysql-server", "mysql-devel"]

DEBIAN_REDIS_PACKAGES = ["redis-server"]
FEDORA_REDIS_PACKAGES = ["redis"]

DEBIAN_DOCKER_PACKAGES = ["docker.io", "docker-buildx", "docker-compose-v2"]
FEDORA_DOCKER_PACKAGES = ["docker", "docker-buildx-plugin", "docker-compose-plugin"]

# All available optional features
ALL_FEATURES = {"mysql", "redis", "docker"}

# Systemd service units
SYSTEMD_UNIT = """[Unit]
Description=Hop3 Server
After=network.target postgresql.service

[Service]
Type=simple
User=hop3
Group=hop3
WorkingDirectory=/home/hop3
ExecStart=/home/hop3/venv/bin/hop-server serve
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

UWSGI_UNIT = """[Unit]
Description=uWSGI Emperor for Hop3
After=network.target

[Service]
Type=notify
User=hop3
Group=hop3
ExecStart=/home/hop3/venv/bin/uwsgi --emperor /home/hop3/uwsgi-enabled --stats /tmp/hop3-uwsgi-stats.sock
Restart=always
KillSignal=SIGQUIT
NotifyAccess=all

[Install]
WantedBy=multi-user.target
"""

# Nginx configuration template
NGINX_CONFIG = """# Hop3 Server - Reverse Proxy Configuration
# Auto-generated by hop3 installer

# Redirect HTTP to HTTPS
server {{
    listen 80;
    server_name {server_name};

    location /.well-known/acme-challenge/ {{
        root /var/www/html;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# HTTPS server
server {{
    listen 443 ssl http2;
    server_name {server_name};

    ssl_certificate {ssl_cert};
    ssl_certificate_key {ssl_key};

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Proxy all requests to hop3-server
    location / {{
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {{
        root /var/www/html;
    }}
}}
"""

# Sudoers configuration (nginx reload only, no supervisor wildcards)
SUDOERS_CONTENT = """# Hop3 service management permissions
# Allow hop3 user to reload/restart nginx for deployments
hop3 ALL=(ALL) NOPASSWD: /usr/bin/systemctl reload nginx
hop3 ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart nginx
hop3 ALL=(ALL) NOPASSWD: /usr/sbin/nginx -s reload
hop3 ALL=(ALL) NOPASSWD: /usr/sbin/nginx -t
"""


@dataclass
class ServerInstallerConfig:
    """Configuration for server installer."""

    # Installation source
    version: str | None = None
    use_git: bool = False
    branch: str = DEFAULT_BRANCH
    local_path: str | None = None

    # Installation options
    force: bool = False
    skip_deps: bool = False
    skip_nginx: bool = False
    skip_postgres: bool = False
    skip_acme: bool = False
    domain: str | None = None
    verbose: bool = False

    # Optional features
    features: set[str] = field(default_factory=set)

    @property
    def with_mysql(self) -> bool:
        return "mysql" in self.features

    @property
    def with_redis(self) -> bool:
        return "redis" in self.features

    @property
    def with_docker(self) -> bool:
        return "docker" in self.features

    @classmethod
    def from_env(cls) -> ServerInstallerConfig:
        """Create config from environment variables."""
        features_str = os.environ.get("HOP3_WITH", "")
        features = parse_features(features_str)

        return cls(
            version=os.environ.get("HOP3_VERSION"),
            use_git=os.environ.get("HOP3_GIT", "").lower() in ("1", "true"),
            branch=os.environ.get("HOP3_BRANCH", DEFAULT_BRANCH),
            local_path=os.environ.get("HOP3_LOCAL_PACKAGE"),
            force=os.environ.get("HOP3_FORCE", "").lower() in ("1", "true"),
            skip_deps=os.environ.get("HOP3_SKIP_DEPS", "").lower() in ("1", "true"),
            skip_nginx=os.environ.get("HOP3_SKIP_NGINX", "").lower() in ("1", "true"),
            skip_postgres=os.environ.get("HOP3_SKIP_POSTGRES", "").lower()
            in ("1", "true"),
            skip_acme=os.environ.get("HOP3_SKIP_ACME", "").lower() in ("1", "true"),
            domain=os.environ.get("HOP3_DOMAIN"),
            verbose=os.environ.get("HOP3_VERBOSE", "").lower() in ("1", "true"),
            features=features,
        )


def parse_features(features_str: str) -> set[str]:
    """Parse comma-separated feature list.

    Args:
        features_str: Comma-separated features (e.g., "mysql,redis" or "all")

    Returns:
        Set of feature names to install
    """
    if not features_str:
        return set()

    features_str = features_str.lower().strip()

    # Handle "all" keyword
    if features_str == "all":
        return ALL_FEATURES.copy()

    # Parse comma-separated list
    features = set()
    for feature in features_str.split(","):
        feature = feature.strip()
        if feature == "all":
            features.update(ALL_FEATURES)
        elif feature in ALL_FEATURES:
            features.add(feature)
        elif feature == "postgres":
            # PostgreSQL is always installed by default, ignore
            pass
        elif feature:
            # Unknown feature - will be warned about in main
            pass

    return features


# =============================================================================
# Module: server.installer
# =============================================================================

# =============================================================================
# User/Group Management
# =============================================================================


def user_exists(username: str) -> bool:
    """Check if a user exists."""
    try:
        pwd.getpwnam(username)
        return True
    except KeyError:
        return False


def group_exists(groupname: str) -> bool:
    """Check if a group exists."""
    try:
        grp.getgrnam(groupname)
        return True
    except KeyError:
        return False


def run_as_hop3(cmd: str) -> subprocess.CompletedProcess:
    """Run a command as the hop3 user."""
    return run_cmd(["su", "-", HOP3_USER, "-c", cmd])


# =============================================================================
# System Dependencies
# =============================================================================


def install_system_deps(distro: str, config: ServerInstallerConfig) -> None:
    """Install system dependencies."""
    if config.skip_deps:
        print_info("Skipping system dependencies (--skip-deps)")
        return

    if distro == "debian":
        _install_debian_deps(config)
    elif distro == "fedora":
        _install_fedora_deps(config)
    else:
        print_warning(f"Unknown distro '{distro}', skipping package installation")
        print_detail("You may need to install dependencies manually")


def _install_debian_deps(config: ServerInstallerConfig) -> None:
    """Install Debian/Ubuntu dependencies."""
    with Spinner("Updating package lists..."):
        run_cmd(["apt-get", "update", "-q"])

    with Spinner("Installing base packages (this may take a while)..."):
        result = run_cmd(
            ["apt-get", "install", "-y"] + DEBIAN_PACKAGES,
            env={"DEBIAN_FRONTEND": "noninteractive"},
            check=False,
        )

    if result.returncode != 0:
        print_error("Base package installation failed")
        if result.stderr:
            for line in result.stderr.strip().split("\n")[-10:]:
                print_detail(line)
        raise CommandError(
            ["apt-get", "install"] + DEBIAN_PACKAGES,
            result.returncode,
            result.stderr or "",
        )

    print_success(f"Installed {len(DEBIAN_PACKAGES)} base packages")

    # Handle npm separately
    if not cmd_exists("npm"):
        print_info("npm not found, installing from Ubuntu repos...")
        with Spinner("Installing npm..."):
            result = run_cmd(
                ["apt-get", "install", "-y", "npm"],
                env={"DEBIAN_FRONTEND": "noninteractive"},
                check=False,
            )
        if result.returncode == 0:
            print_success("npm installed")
        else:
            print_warning("npm installation failed (may conflict with NodeSource)")
    else:
        print_success("npm already available")

    # Optional packages
    if config.with_docker:
        _install_optional_packages(
            "Docker", DEBIAN_DOCKER_PACKAGES, "apt-get", "DEBIAN_FRONTEND"
        )

    if config.with_mysql:
        if not cmd_exists("mysql"):
            _install_optional_packages(
                "MySQL", DEBIAN_MYSQL_PACKAGES, "apt-get", "DEBIAN_FRONTEND"
            )
        else:
            print_success("MySQL already installed")

    if config.with_redis:
        if not cmd_exists("redis-server"):
            _install_optional_packages(
                "Redis", DEBIAN_REDIS_PACKAGES, "apt-get", "DEBIAN_FRONTEND"
            )
        else:
            print_success("Redis already installed")


def _install_fedora_deps(config: ServerInstallerConfig) -> None:
    """Install Fedora/RHEL dependencies."""
    with Spinner("Installing base packages (this may take a while)..."):
        result = run_cmd(["dnf", "install", "-y"] + FEDORA_PACKAGES, check=False)

    if result.returncode != 0:
        print_error("Base package installation failed")
        if result.stderr:
            for line in result.stderr.strip().split("\n")[-10:]:
                print_detail(line)
        raise CommandError(
            ["dnf", "install"] + FEDORA_PACKAGES,
            result.returncode,
            result.stderr or "",
        )

    print_success(f"Installed {len(FEDORA_PACKAGES)} base packages")

    # Handle npm separately
    if not cmd_exists("npm"):
        with Spinner("Installing npm..."):
            result = run_cmd(["dnf", "install", "-y", "npm"], check=False)
        if result.returncode == 0:
            print_success("npm installed")
        else:
            print_warning("npm installation failed")
    else:
        print_success("npm already available")

    # Optional packages
    if config.with_docker:
        _install_optional_packages("Docker", FEDORA_DOCKER_PACKAGES, "dnf", None)

    if config.with_mysql:
        if not cmd_exists("mysql"):
            _install_optional_packages("MySQL", FEDORA_MYSQL_PACKAGES, "dnf", None)
        else:
            print_success("MySQL already installed")

    if config.with_redis:
        if not cmd_exists("redis-server"):
            _install_optional_packages("Redis", FEDORA_REDIS_PACKAGES, "dnf", None)
        else:
            print_success("Redis already installed")


def _install_optional_packages(
    name: str,
    packages: list[str],
    pkg_manager: str,
    env_var: str | None,
) -> None:
    """Install optional packages."""
    with Spinner(f"Installing {name} packages..."):
        env = {env_var: "noninteractive"} if env_var else None
        result = run_cmd(
            [pkg_manager, "install", "-y"] + packages,
            env=env,
            check=False,
        )
    if result.returncode == 0:
        print_success(f"{name} packages installed")
    else:
        print_warning(f"{name} installation failed")
        if result.stderr:
            for line in result.stderr.strip().split("\n")[-5:]:
                print_detail(line)


# =============================================================================
# User Setup
# =============================================================================


def create_user_and_group() -> None:
    """Create the hop3 user and group."""
    # Create group
    if not group_exists(HOP3_GROUP):
        run_cmd(["groupadd", HOP3_GROUP])
        print_success(f"Created group: {HOP3_GROUP}")
    else:
        print_info(f"Group {HOP3_GROUP} already exists")

    # Create user
    if not user_exists(HOP3_USER):
        run_cmd(
            [
                "useradd",
                "-m",
                "-g",
                HOP3_GROUP,
                "-s",
                "/bin/bash",
                "-d",
                str(HOME_DIR),
                HOP3_USER,
            ]
        )
        print_success(f"Created user: {HOP3_USER}")
    else:
        print_info(f"User {HOP3_USER} already exists")

    # Ensure home directory exists with correct permissions
    if not HOME_DIR.exists():
        HOME_DIR.mkdir(parents=True, exist_ok=True)
        print_info(f"Created home directory: {HOME_DIR}")

    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(HOME_DIR, hop3_uid, hop3_gid)
    os.chmod(HOME_DIR, 0o755)

    # Add www-data to hop3 group
    if user_exists("www-data"):
        run_cmd(["usermod", "-a", "-G", HOP3_GROUP, "www-data"], check=False)
        print_info("Added www-data to hop3 group")


# =============================================================================
# Virtual Environment and Package Installation
# =============================================================================


def create_virtual_environment() -> None:
    """Create Python virtual environment."""
    if VENV_DIR.exists():
        shutil.rmtree(VENV_DIR)

    with Spinner("Creating virtual environment..."):
        run_as_hop3(f"python3 -m venv {VENV_DIR}")

    print_success(f"Virtual environment created at {VENV_DIR}")


def install_package(config: ServerInstallerConfig) -> None:
    """Install the hop3-server package."""
    pip = f"{VENV_DIR}/bin/pip"

    # Upgrade pip
    with Spinner("Upgrading pip..."):
        run_as_hop3(f"{pip} install --upgrade pip")

    # Determine what to install
    if config.local_path:
        package_spec = config.local_path
        source_desc = f"local path ({config.local_path})"
    elif config.use_git:
        with Spinner("Installing build tools..."):
            run_as_hop3(f"{pip} install uv")
        package_spec = f"git+{GIT_REPO}@{config.branch}#subdirectory={GIT_SUBDIR}"
        source_desc = f"git ({config.branch} branch)"
    elif config.version:
        package_spec = f"{PACKAGE_NAME}=={config.version}"
        source_desc = f"PyPI (version {config.version})"
    else:
        package_spec = PACKAGE_NAME
        source_desc = "PyPI (latest)"

    # Install
    with Spinner(f"Installing hop3-server from {source_desc}..."):
        run_as_hop3(f"{pip} install '{package_spec}'")

    print_success("hop3-server installed successfully")


def run_hop3_setup() -> None:
    """Run hop3 setup command."""
    hop_server = f"{VENV_DIR}/bin/hop-server"

    with Spinner("Running initial setup..."):
        run_as_hop3(f"{hop_server} setup")

    print_success("Hop3 initial setup complete")


def setup_ssh_keys() -> None:
    """Copy root SSH keys to hop3 user if available."""
    root_keys = Path("/root/.ssh/authorized_keys")

    if not root_keys.exists():
        print_info("No root SSH keys found, skipping")
        return

    content = root_keys.read_text().strip()
    if not content:
        print_info("Root SSH keys file is empty, skipping")
        return

    hop_server = f"{VENV_DIR}/bin/hop-server"
    temp_keys = Path("/tmp/root_authorized_keys")

    try:
        # Copy keys to temp location
        shutil.copy2(root_keys, temp_keys)
        hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
        hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
        os.chown(temp_keys, hop3_uid, hop3_gid)

        # Run setup:ssh
        run_as_hop3(f"{hop_server} setup:ssh {temp_keys}")
        print_success("SSH keys configured")
    except CommandError:
        print_warning("Could not configure SSH keys (invalid format?)")
    finally:
        if temp_keys.exists():
            temp_keys.unlink()


# =============================================================================
# Systemd Services
# =============================================================================


def setup_systemd() -> None:
    """Install and enable systemd services."""
    # Hop3 server service
    service_path = Path("/etc/systemd/system/hop3-server.service")
    service_path.write_text(SYSTEMD_UNIT)

    # uWSGI service
    uwsgi_path = Path("/etc/systemd/system/uwsgi-hop3.service")
    uwsgi_path.write_text(UWSGI_UNIT)

    # Reload and enable
    run_cmd(["systemctl", "daemon-reload"])
    run_cmd(["systemctl", "enable", "hop3-server"], check=False)
    run_cmd(["systemctl", "enable", "uwsgi-hop3"], check=False)
    run_cmd(["systemctl", "start", "hop3-server"], check=False)
    run_cmd(["systemctl", "start", "uwsgi-hop3"], check=False)

    print_success("Systemd services configured")


# =============================================================================
# SSL Certificates
# =============================================================================


def setup_ssl_selfsigned() -> None:
    """Generate a self-signed SSL certificate."""
    if SSL_CERT.exists() and SSL_KEY.exists():
        print_info("SSL certificates already exist")
        return

    # Create SSL directory
    SSL_DIR.mkdir(parents=True, exist_ok=True)

    with Spinner("Generating self-signed SSL certificate..."):
        run_cmd(
            [
                "openssl",
                "req",
                "-x509",
                "-nodes",
                "-days",
                "3650",
                "-newkey",
                "rsa:2048",
                "-keyout",
                str(SSL_KEY),
                "-out",
                str(SSL_CERT),
                "-subj",
                "/CN=hop3-server/O=Hop3/C=US",
                "-addext",
                "subjectAltName=DNS:localhost,IP:127.0.0.1",
            ]
        )

    os.chmod(SSL_KEY, 0o600)
    os.chmod(SSL_CERT, 0o644)

    print_success("Self-signed SSL certificate generated")
    print_detail(f"Certificate: {SSL_CERT}")
    print_detail(f"Private key: {SSL_KEY}")


# =============================================================================
# Nginx Configuration
# =============================================================================


def setup_nginx(config: ServerInstallerConfig) -> None:
    """Configure nginx as reverse proxy."""
    if config.skip_nginx:
        print_info("Skipping nginx setup (--skip-nginx)")
        return

    # Determine server name
    server_name = config.domain if config.domain else "_"

    # Generate nginx config
    nginx_config = NGINX_CONFIG.format(
        server_name=server_name,
        ssl_cert=str(SSL_CERT),
        ssl_key=str(SSL_KEY),
    )

    # Write config file
    nginx_config_path = Path("/etc/nginx/sites-available/hop3")
    nginx_enabled_path: Path | None = Path("/etc/nginx/sites-enabled/hop3")

    # For Fedora/RHEL, use conf.d instead
    if not Path("/etc/nginx/sites-available").exists():
        nginx_config_path = Path("/etc/nginx/conf.d/hop3.conf")
        nginx_enabled_path = None

    nginx_config_path.parent.mkdir(parents=True, exist_ok=True)
    nginx_config_path.write_text(nginx_config)
    print_success(f"Nginx config written to {nginx_config_path}")

    # Create symlink if using sites-available/sites-enabled
    if nginx_enabled_path:
        nginx_enabled_path.parent.mkdir(parents=True, exist_ok=True)
        if nginx_enabled_path.exists() or nginx_enabled_path.is_symlink():
            nginx_enabled_path.unlink()
        nginx_enabled_path.symlink_to(nginx_config_path)
        print_success("Nginx site enabled")

        # Remove default site if exists
        default_site = Path("/etc/nginx/sites-enabled/default")
        if default_site.exists() or default_site.is_symlink():
            default_site.unlink()
            print_info("Removed default nginx site")

    # Add include for app-specific configs
    _add_hop3_nginx_include()

    # Test nginx config
    try:
        run_cmd(["nginx", "-t"])
        print_success("Nginx configuration is valid")
    except CommandError as e:
        print_error(f"Nginx configuration test failed: {e.stderr[:200]}")
        return

    # Configure sudoers
    setup_sudoers()

    # Enable and start nginx
    run_cmd(["systemctl", "enable", "nginx"], check=False)
    run_cmd(["systemctl", "restart", "nginx"], check=False)
    print_success("Nginx enabled and started")


def _add_hop3_nginx_include() -> None:
    """Add include directive for hop3 app configs to nginx.conf."""
    nginx_conf = Path("/etc/nginx/nginx.conf")
    include_line = "include /home/hop3/nginx/*.conf;"

    if not nginx_conf.exists():
        print_warning("nginx.conf not found, skipping app include setup")
        return

    content = nginx_conf.read_text()

    if include_line in content:
        print_info("Hop3 app nginx include already configured")
        return

    # Create the nginx directory for app configs
    hop3_nginx_dir = HOME_DIR / "nginx"
    hop3_nginx_dir.mkdir(parents=True, exist_ok=True)
    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(hop3_nginx_dir, hop3_uid, hop3_gid)

    # Find the right place to add the include
    lines = content.split("\n")
    new_lines = []
    include_added = False

    for line in lines:
        new_lines.append(line)
        if not include_added and "include" in line:
            if "sites-enabled" in line or "conf.d" in line:
                indent = len(line) - len(line.lstrip())
                new_lines.append(" " * indent + include_line)
                include_added = True

    if include_added:
        nginx_conf.write_text("\n".join(new_lines))
        print_success("Added hop3 app nginx include to nginx.conf")
    else:
        print_warning("Could not find suitable location for nginx include")


def disable_apache2() -> None:
    """Disable Apache2 if running to free up ports 80/443 for nginx.

    On Debian-based systems, Apache2 is often pre-installed or installed
    as a dependency. It binds to ports 80/443 which prevents nginx from
    working as the reverse proxy.
    """
    # Check if apache2 service exists
    result = run_cmd(["systemctl", "is-active", "apache2"], check=False)

    if result.returncode == 0:
        # Apache2 is running, stop and disable it
        print_info("Apache2 is running, stopping and disabling...")
        run_cmd(["systemctl", "stop", "apache2"], check=False)
        run_cmd(["systemctl", "disable", "apache2"], check=False)
        print_success("Apache2 stopped and disabled")
    else:
        # Also check for httpd (Fedora/RHEL)
        result = run_cmd(["systemctl", "is-active", "httpd"], check=False)
        if result.returncode == 0:
            print_info("httpd is running, stopping and disabling...")
            run_cmd(["systemctl", "stop", "httpd"], check=False)
            run_cmd(["systemctl", "disable", "httpd"], check=False)
            print_success("httpd stopped and disabled")
        else:
            print_info("No conflicting web server found")


def setup_sudoers() -> None:
    """Configure sudo permissions for hop3 user."""
    sudoers_file = Path("/etc/sudoers.d/hop3")

    try:
        sudoers_file.write_text(SUDOERS_CONTENT)
        os.chmod(sudoers_file, 0o440)

        # Validate with visudo
        result = subprocess.run(
            ["visudo", "-c", "-f", str(sudoers_file)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print_warning(f"Invalid sudoers file: {result.stderr}")
            sudoers_file.unlink()
            return

        print_success("Sudoers configured for hop3 service management")
    except Exception as e:
        print_warning(f"Could not configure sudoers: {e}")


# =============================================================================
# MySQL
# =============================================================================


def get_debian_mysql_credentials() -> tuple[str, str] | None:
    """Get MySQL credentials from Debian maintenance file.

    On Debian/Ubuntu, /etc/mysql/debian.cnf contains credentials for
    the debian-sys-maint user which has full privileges.

    Returns:
        Tuple of (user, password) or None if not available.
    """
    debian_cnf = Path("/etc/mysql/debian.cnf")
    if not debian_cnf.exists():
        return None

    try:
        content = debian_cnf.read_text()
        user = None
        password = None
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("user"):
                user = line.split("=")[1].strip()
            elif line.startswith("password"):
                password = line.split("=")[1].strip()
            if user and password:
                return (user, password)
    except Exception:
        pass
    return None


def reset_mysql_root_auth() -> bool:
    """Reset MySQL root authentication to socket auth.

    Uses Debian maintenance user or skip-grant-tables as fallback.

    Returns:
        True if reset was successful, False otherwise.
    """
    import time

    print_detail("Attempting to reset MySQL root authentication...")

    # Method 1: Try using Debian maintenance user
    creds = get_debian_mysql_credentials()
    if creds:
        user, password = creds
        print_detail(f"Using Debian maintenance user: {user}")
        result = run_cmd(
            ["mysql", f"-u{user}", f"-p{password}", "-e",
             "ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket; FLUSH PRIVILEGES;"],
            check=False,
        )
        if result.returncode == 0:
            print_detail("Reset via debian-sys-maint succeeded")
            return True

    # Method 2: Use skip-grant-tables (more invasive but reliable)
    print_detail("Trying skip-grant-tables method...")

    # Stop MySQL
    run_cmd(["systemctl", "stop", "mysql"], check=False)
    run_cmd(["systemctl", "stop", "mariadb"], check=False)
    time.sleep(2)

    # Start MySQL without authentication
    run_cmd(
        ["mysqld", "--skip-grant-tables", "--skip-networking", "--user=mysql"],
        check=False,
        timeout=5,  # This will timeout as mysqld runs in foreground, that's OK
    )
    time.sleep(3)

    # Reset root authentication
    result = run_cmd(
        ["mysql", "-e", "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;"],
        check=False,
    )

    # Kill the mysqld process
    run_cmd(["pkill", "-f", "skip-grant-tables"], check=False)
    time.sleep(2)

    # Restart MySQL normally
    run_cmd(["systemctl", "start", "mysql"], check=False)
    if run_cmd(["systemctl", "is-active", "mysql"], check=False).returncode != 0:
        run_cmd(["systemctl", "start", "mariadb"], check=False)
    time.sleep(2)

    return result.returncode == 0


def setup_mysql(config: ServerInstallerConfig, distro: str) -> str | None:
    """Configure MySQL.

    Returns:
        The generated MySQL password for hop3 user, or None if skipped/failed.
    """
    if not config.with_mysql:
        return None

    print_info("Configuring MySQL...")

    # Start MySQL service
    run_cmd(["systemctl", "enable", "mysql"], check=False)
    result = run_cmd(["systemctl", "start", "mysql"], check=False)

    if result.returncode != 0:
        # Try mariadb service name (some distros use this)
        run_cmd(["systemctl", "enable", "mariadb"], check=False)
        result = run_cmd(["systemctl", "start", "mariadb"], check=False)

    if result.returncode != 0:
        print_warning("Could not start MySQL service")
        return None

    print_success("MySQL service started")

    # Generate a secure password
    mysql_password = "hop3_" + secrets.token_hex(16)

    # First, test if we can connect to MySQL at all
    # Try different connection methods for MySQL root/admin access
    mysql_root_cmd = None

    # Build list of commands to try
    test_commands = [
        ["mysql"],  # Socket auth as current user (root)
        ["sudo", "mysql"],  # Socket auth via sudo
        ["mysql", "-u", "root"],  # Traditional root
    ]

    # Also try Debian maintenance user if available
    debian_creds = get_debian_mysql_credentials()
    if debian_creds:
        user, password = debian_creds
        test_commands.insert(0, ["mysql", f"-u{user}", f"-p{password}"])

    for test_cmd in test_commands:
        result = run_cmd(test_cmd + ["-e", "SELECT 1;"], check=False)
        if result.returncode == 0:
            mysql_root_cmd = test_cmd
            # Don't show password in logs
            display_cmd = " ".join(test_cmd)
            if debian_creds and debian_creds[1] in display_cmd:
                display_cmd = display_cmd.replace(debian_creds[1], "***")
            print_detail(f"MySQL admin access via: {display_cmd}")
            break

    if mysql_root_cmd is None:
        print_warning("Cannot connect to MySQL as root - attempting to reset authentication")

        # Try to reset MySQL root to use socket authentication
        # This is safe and allows the installer to proceed
        if reset_mysql_root_auth():
            # Retry connection after reset
            for test_cmd in [["mysql"], ["sudo", "mysql"]]:
                result = run_cmd(test_cmd + ["-e", "SELECT 1;"], check=False)
                if result.returncode == 0:
                    mysql_root_cmd = test_cmd
                    print_success("MySQL root access restored")
                    break

        if mysql_root_cmd is None:
            print_warning("Could not restore MySQL root access")
            print_detail("MySQL configuration may need manual intervention")
            return None

    def run_mysql_sql(sql: str) -> subprocess.CompletedProcess:
        """Run SQL using the working MySQL root connection."""
        return run_cmd(mysql_root_cmd + ["-e", sql], check=False)

    # Drop existing hop3 user if exists (clean slate)
    run_mysql_sql("DROP USER IF EXISTS 'hop3'@'localhost';")

    # Create hop3 user with password authentication
    result = run_mysql_sql(
        f"CREATE USER 'hop3'@'localhost' IDENTIFIED BY '{mysql_password}';"
    )
    if result.returncode != 0:
        print_warning("Failed to create MySQL user 'hop3'")
        if result.stderr:
            print_detail(result.stderr[:200])
        return None

    # Grant all privileges
    result = run_mysql_sql(
        "GRANT ALL PRIVILEGES ON *.* TO 'hop3'@'localhost' WITH GRANT OPTION;"
    )
    if result.returncode != 0:
        print_warning("Failed to grant privileges to hop3")
        if result.stderr:
            print_detail(result.stderr[:200])
        return None

    run_mysql_sql("FLUSH PRIVILEGES;")

    print_success("MySQL user 'hop3' created with privileges")

    # Verify the connection works with the new password
    verify_result = run_cmd(
        ["mysql", "-u", "hop3", f"-p{mysql_password}", "-e", "SELECT 1;"],
        check=False,
    )

    if verify_result.returncode != 0:
        print_warning("MySQL user created but connection verification failed")
        print_detail("This may be a password plugin issue. Trying to fix...")

        # Try to alter user to use mysql_native_password (compatibility)
        fix_sql = f"ALTER USER 'hop3'@'localhost' IDENTIFIED WITH mysql_native_password BY '{mysql_password}';"
        run_cmd(["sudo", "mysql", "-e", fix_sql], check=False)
        run_cmd(["sudo", "mysql", "-e", "FLUSH PRIVILEGES;"], check=False)

        # Retry verification
        verify_result = run_cmd(
            ["mysql", "-u", "hop3", f"-p{mysql_password}", "-e", "SELECT 1;"],
            check=False,
        )

        if verify_result.returncode != 0:
            print_warning("MySQL verification still failing")
            if verify_result.stderr:
                print_detail(verify_result.stderr[:200])
            return None

    print_success("MySQL connection verified successfully")
    return mysql_password


# =============================================================================
# PostgreSQL
# =============================================================================


def setup_postgres(config: ServerInstallerConfig, distro: str) -> str | None:
    """Configure PostgreSQL.

    Returns:
        The generated postgres superuser password, or None if skipped.
    """
    if config.skip_postgres:
        print_info("Skipping PostgreSQL setup (--skip-postgres)")
        return None

    # Initialize PostgreSQL on Fedora
    if distro == "fedora":
        if not Path("/var/lib/pgsql/data/pg_hba.conf").exists():
            run_cmd(["postgresql-setup", "--initdb"], check=False)

    run_cmd(["systemctl", "enable", "postgresql"], check=False)
    run_cmd(["systemctl", "start", "postgresql"], check=False)

    # Create role and database
    try:
        run_cmd(
            ["su", "-", "postgres", "-c", f"createuser --createdb {HOP3_USER}"],
            check=False,
        )
        run_cmd(
            ["su", "-", "postgres", "-c", f"createdb -O {HOP3_USER} hop3"],
            check=False,
        )
        print_success("PostgreSQL role and database created")
    except CommandError:
        print_info("PostgreSQL role/database may already exist")

    # Set a password for postgres superuser
    pg_password = "hop3_" + secrets.token_hex(16)

    # Use psql to set the password
    sql_cmd = f"ALTER USER postgres PASSWORD '{pg_password}';"
    result = run_cmd(
        ["su", "-", "postgres", "-c", f'psql -c "{sql_cmd}"'],
        check=False,
    )
    if result.returncode == 0:
        print_success("PostgreSQL superuser password configured")
    else:
        print_warning("Could not set PostgreSQL superuser password")
        return None

    return pg_password


# =============================================================================
# ACME / Let's Encrypt
# =============================================================================


def setup_acme(config: ServerInstallerConfig) -> None:
    """Install acme.sh for Let's Encrypt."""
    if config.skip_acme:
        print_info("Skipping ACME setup (--skip-acme)")
        return

    acme_sh = HOME_DIR / ".acme.sh" / "acme.sh"

    if acme_sh.exists():
        print_info("acme.sh already installed")
        return

    with Spinner("Installing acme.sh..."):
        run_as_hop3(
            "curl -fsSL https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh -o /tmp/acme.sh"
        )
        run_as_hop3("cd /tmp && bash acme.sh --install")
        run_cmd(["rm", "-f", "/tmp/acme.sh"])

    if acme_sh.exists():
        run_as_hop3(f"bash {acme_sh} --set-default-ca --server letsencrypt")
        print_success("acme.sh installed and configured")
    else:
        print_warning("acme.sh installation may have failed")


# =============================================================================
# Server Configuration
# =============================================================================


def write_server_config(
    pg_password: str | None,
    mysql_password: str | None,
    domain: str | None,
) -> None:
    """Write hop3-server.toml configuration file."""
    config_file = HOME_DIR / "hop3-server.toml"

    lines = [
        "# Hop3 Server Configuration",
        "# Auto-generated by installer",
        "",
    ]

    if domain:
        lines.extend(
            [
                "# Admin UI domain",
                f'ADMIN_DOMAIN = "{domain}"',
                "",
            ]
        )

    if pg_password:
        lines.extend(
            [
                "# PostgreSQL admin connection settings",
                'POSTGRES_HOST = "127.0.0.1"',
                f'POSTGRES_SUPERUSER_PASSWORD = "{pg_password}"',
                "",
            ]
        )

    if mysql_password:
        lines.extend(
            [
                "# MySQL admin connection settings",
                'MYSQL_HOST = "127.0.0.1"',
                'MYSQL_SUPERUSER = "hop3"',
                f'MYSQL_SUPERUSER_PASSWORD = "{mysql_password}"',
                "",
            ]
        )

    config_file.write_text("\n".join(lines))

    hop3_uid = pwd.getpwnam(HOP3_USER).pw_uid
    hop3_gid = grp.getgrnam(HOP3_GROUP).gr_gid
    os.chown(config_file, hop3_uid, hop3_gid)
    os.chmod(config_file, 0o600)

    print_success(f"Server configuration written to {config_file}")


# =============================================================================
# Verification
# =============================================================================


def verify_installation(config: ServerInstallerConfig) -> bool:
    """Verify the installation."""
    hop_server = VENV_DIR / "bin" / "hop-server"
    all_ok = True

    if not hop_server.exists():
        print_error("hop-server not found")
        return False

    # Check services
    for service, name in [
        ("hop3-server", "hop3-server service"),
        ("nginx", "nginx service"),
        ("uwsgi-hop3", "uwsgi-hop3 service"),
    ]:
        result = run_cmd(["systemctl", "is-active", service], capture=True, check=False)
        if result.stdout.strip() == "active":
            print_success(f"{name} is running")
        else:
            print_warning(f"{name} is not running")
            print_detail(f"Check with: sudo systemctl status {service}")

    # Check SSL
    if SSL_CERT.exists() and SSL_KEY.exists():
        print_success("SSL certificate is configured")
    else:
        print_warning("SSL certificate not found")

    # Check PostgreSQL if configured
    config_file = HOME_DIR / "hop3-server.toml"
    if config_file.exists():
        config_content = config_file.read_text()

        if "POSTGRES_SUPERUSER_PASSWORD" in config_content:
            result = run_cmd(
                ["systemctl", "is-active", "postgresql"],
                capture=True,
                check=False,
            )
            if result.stdout.strip() == "active":
                print_success("PostgreSQL service is running")
            else:
                print_warning("PostgreSQL service is not running")
                all_ok = False

        # Check MySQL if configured
        if "MYSQL_SUPERUSER_PASSWORD" in config_content:
            result = run_cmd(
                ["systemctl", "is-active", "mysql"],
                capture=True,
                check=False,
            )
            if result.returncode != 0:
                result = run_cmd(
                    ["systemctl", "is-active", "mariadb"],
                    capture=True,
                    check=False,
                )
            if result.stdout.strip() == "active":
                print_success("MySQL service is running and configured")
            else:
                print_warning("MySQL service is not running")
                all_ok = False

    return all_ok


def print_final_message(config: ServerInstallerConfig) -> None:
    """Print success message with next steps."""
    print()
    print(f"{Colors.GREEN}{Colors.BOLD}Installation complete!{Colors.RESET}")
    print()
    print(f"  {Colors.BOLD}User:{Colors.RESET}      {HOP3_USER}")
    print(f"  {Colors.BOLD}Home:{Colors.RESET}      {HOME_DIR}")
    print(f"  {Colors.BOLD}Venv:{Colors.RESET}      {VENV_DIR}")
    print()
    print(f"  {Colors.BOLD}Services:{Colors.RESET}")
    print("    sudo systemctl status hop3-server")
    print("    sudo systemctl status uwsgi-hop3")
    print("    sudo systemctl status nginx")
    print()
    print(f"  {Colors.BOLD}Logs:{Colors.RESET}")
    print("    sudo journalctl -u hop3-server -f")
    print()
    print(f"  {Colors.BOLD}Next steps:{Colors.RESET}")
    print("    1. Add your SSH key:  ssh-copy-id hop3@your-server")
    print("    2. Deploy an app:     hop3 deploy your-app.git")
    print()


# =============================================================================
# CLI Argument Parsing
# =============================================================================


def create_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    env_config = ServerInstallerConfig.from_env()

    parser = argparse.ArgumentParser(
        prog="install-server.py",
        description="Install the Hop3 Server. Must be run as root.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  sudo python3 install-server.py                  Install with PostgreSQL only
  sudo python3 install-server.py --with docker    Install with PostgreSQL + Docker
  sudo python3 install-server.py --with all       Install all optional features
  sudo python3 install-server.py --domain hop3.example.com
                                                  Install with Let's Encrypt cert

Optional Features (--with):
  docker      Docker container runtime
  mysql       MySQL database
  redis       Redis cache/store
  all         Install all optional features
""",
    )

    parser.add_argument(
        "--version",
        metavar="VERSION",
        default=env_config.version,
        help="Install a specific version (e.g., 0.4.0)",
    )
    parser.add_argument(
        "--git",
        action="store_true",
        default=env_config.use_git,
        help="Install from git repository",
    )
    parser.add_argument(
        "--branch",
        metavar="BRANCH",
        default=env_config.branch,
        help=f"Git branch to install from (default: {DEFAULT_BRANCH})",
    )
    parser.add_argument(
        "--local-path",
        metavar="PATH",
        default=env_config.local_path,
        help="Install from a local directory",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        default=env_config.force,
        help="Force reinstall",
    )
    parser.add_argument(
        "--skip-deps",
        action="store_true",
        default=env_config.skip_deps,
        help="Skip system dependency installation",
    )
    parser.add_argument(
        "--skip-nginx",
        action="store_true",
        default=env_config.skip_nginx,
        help="Skip nginx setup",
    )
    parser.add_argument(
        "--skip-postgres",
        action="store_true",
        default=env_config.skip_postgres,
        help="Skip PostgreSQL setup",
    )
    parser.add_argument(
        "--with",
        dest="with_features",
        metavar="FEATURES",
        default=",".join(env_config.features) if env_config.features else "",
        help="Comma-separated list of features (mysql,redis,docker,all)",
    )
    parser.add_argument(
        "--skip-acme",
        action="store_true",
        default=env_config.skip_acme,
        help="Skip ACME/Let's Encrypt setup",
    )
    parser.add_argument(
        "--domain",
        metavar="DOMAIN",
        default=env_config.domain,
        help="Domain name for Let's Encrypt certificate",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        default=env_config.verbose,
        help="Show verbose output",
    )

    return parser


# =============================================================================
# Main
# =============================================================================


def main() -> int:
    """Main entry point.

    Returns:
        Exit code (0 for success, non-zero for failure)
    """
    check_python_version()

    parser = create_parser()
    args = parser.parse_args()

    # Convert args to config
    features = parse_features(args.with_features)
    config = ServerInstallerConfig(
        version=args.version,
        use_git=args.git,
        branch=args.branch,
        local_path=args.local_path,
        force=args.force,
        skip_deps=args.skip_deps,
        skip_nginx=args.skip_nginx,
        skip_postgres=args.skip_postgres,
        skip_acme=args.skip_acme,
        domain=args.domain,
        verbose=args.verbose,
        features=features,
    )

    # Header
    print_header("Hop3 Server Installer")

    # Check root
    if os.geteuid() != 0:
        print_error("This installer must be run as root")
        print_detail("Use: sudo python3 install-server.py")
        return 1

    # Detect distro
    distro = detect_distro()
    print_info(f"Detected distribution: {distro}")

    if config.features:
        print_info(f"Optional features: {', '.join(sorted(config.features))}")

    total_steps = 12

    # Step 1: System dependencies
    print_step(1, total_steps, "Installing system dependencies...")
    try:
        install_system_deps(distro, config)
    except CommandError as e:
        print_error(f"Failed to install dependencies: {e.stderr[:200]}")
        return 1

    # Step 2: Create user
    print_step(2, total_steps, "Creating hop3 user and group...")
    try:
        create_user_and_group()
    except CommandError as e:
        print_error(f"Failed to create user: {e.stderr}")
        return 1

    # Step 3: Virtual environment
    print_step(3, total_steps, "Creating virtual environment...")
    try:
        create_virtual_environment()
    except CommandError as e:
        print_error(f"Failed to create venv: {e.stderr}")
        return 1

    # Step 4: Install package
    print_step(4, total_steps, "Installing hop3-server...")
    try:
        install_package(config)
    except CommandError as e:
        print_error("Failed to install hop3-server")
        # Always show error output
        if e.stdout:
            print_detail("--- stdout ---")
            for line in e.stdout.strip().split("\n")[-20:]:
                print_detail(line)
        if e.stderr:
            print_detail("--- stderr ---")
            for line in e.stderr.strip().split("\n")[-20:]:
                print_detail(line)
        return 1

    # Step 5: Run setup
    print_step(5, total_steps, "Running initial setup...")
    try:
        run_hop3_setup()
    except CommandError as e:
        print_error(f"Setup failed: {e.stderr[:200]}")
        return 1

    # Step 6: SSH keys
    print_step(6, total_steps, "Configuring SSH keys...")
    setup_ssh_keys()

    # Step 7: Systemd
    print_step(7, total_steps, "Setting up systemd services...")
    try:
        setup_systemd()
    except CommandError as e:
        print_warning(f"Systemd setup issue: {e.stderr[:100]}")

    # Step 8: SSL certificates
    print_step(8, total_steps, "Setting up SSL certificates...")
    try:
        setup_ssl_selfsigned()
    except CommandError as e:
        print_warning(f"SSL setup issue: {e.stderr[:100]}")

    # Step 9: Disable Apache2 (if running, to free up ports 80/443 for nginx)
    print_step(9, total_steps, "Ensuring nginx can bind to ports...")
    try:
        disable_apache2()
    except CommandError as e:
        print_warning(f"Apache2 disable issue: {e.stderr[:100]}")

    # Step 10: Nginx
    print_step(10, total_steps, "Configuring nginx...")
    try:
        setup_nginx(config)
    except CommandError as e:
        print_warning(f"Nginx setup issue: {e.stderr[:100]}")

    # Step 11: PostgreSQL
    print_step(11, total_steps, "Configuring PostgreSQL...")
    pg_password = None
    try:
        pg_password = setup_postgres(config, distro)
    except CommandError as e:
        print_warning(f"PostgreSQL setup issue: {e.stderr[:100]}")

    # Step 12: MySQL (if requested)
    mysql_password = None
    if config.with_mysql:
        print_step(12, total_steps, "Configuring MySQL...")
        try:
            mysql_password = setup_mysql(config, distro)
        except CommandError as e:
            print_warning(f"MySQL setup issue: {e.stderr[:100]}")

    # Write server config
    try:
        write_server_config(pg_password, mysql_password, config.domain)
    except Exception as e:
        print_warning(f"Config write issue: {e}")

    # ACME setup
    try:
        setup_acme(config)
    except CommandError as e:
        print_warning(f"ACME setup issue: {e.stderr[:100]}")

    # Verify
    print()
    verify_installation(config)

    # Success
    print_final_message(config)

    return 0




# =============================================================================
# Entry Point
# =============================================================================

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nInstallation cancelled.")
        sys.exit(130)
    except Exception as e:
        print(f"\n{Colors.RED}Error:{Colors.RESET} {e}", file=sys.stderr)
        sys.exit(1)
